import type { CraftService } from "../craft-service.ts";
import type { JsonObject } from "../../store.ts";
import { installKnowledgeMemoryMethods } from "./knowledge-memory.ts";
import { installTraceMethods } from "./trace.ts";
import { installCapabilityLifecycleMethods } from "./capability-lifecycle.ts";
import { installMemoryConsolidationMethods } from "./memory-consolidation.ts";
import { installRemoteInteropMethods } from "./remote-interop.ts";
import { installPlatformMethods } from "./platform.ts";
import { installTurnCognitiveMethods } from "./turn-cognitive.ts";
import { installHostSessionMethods } from "./host-session.ts";
import { installDurableExperienceMethods } from "./durable-experience.ts";
import { installLegacyKnowledgeMigrationMethods } from "./legacy-knowledge-migration.ts";

/** Thin application use cases that delegate to one owned domain kernel. */
declare module "../craft-service.ts" {
  interface CraftService {
    knowledgeMemoryInstallBuiltins(): JsonObject;
    knowledgeSourceRegister(args: JsonObject): JsonObject;
    knowledgeSourceList(args: JsonObject): JsonObject;
    knowledgeSourceTransition(args: JsonObject): JsonObject;
    memoryLedgerRemember(args: JsonObject): JsonObject;
    memoryLedgerTransition(args: JsonObject): JsonObject;
    memoryLedgerCompatBind(args: JsonObject): JsonObject;
    contextResolutionResolve(args: JsonObject): JsonObject;
    contextResolutionGet(args: JsonObject): JsonObject;
    retrievalAdapterConfigure(args: JsonObject): JsonObject;
    retrievalAdapterEvaluate(args: JsonObject): JsonObject;
    memoryCandidatePropose(args: JsonObject): JsonObject;
    memoryCandidateReview(args: JsonObject): JsonObject;
    memoryLedgerRememberApproved(args: JsonObject): JsonObject;
    memoryConflictList(args?: JsonObject): JsonObject;
    memoryConflictResolve(args: JsonObject): JsonObject;
    memoryExpirySweep(args?: JsonObject): JsonObject;
    memorySessionFinalize(args: JsonObject): JsonObject;
    memoryConsolidateGoverned(args: JsonObject): JsonObject;
    workflowDagValidate(args: JsonObject): JsonObject;
    workflowDagSave(args: JsonObject): JsonObject;
    workflowDagTransition(args: JsonObject): JsonObject;
    workflowDagCheckpoint(args: JsonObject): JsonObject;
    workflowDagResume(args: JsonObject): JsonObject;
    workflowDagCancel(args: JsonObject): JsonObject;
    workflowDagReplan(args: JsonObject): JsonObject;
    workflowDagExport(args: JsonObject): JsonObject;
    workflowDagImport(args: JsonObject): JsonObject;
    taskStateTransition(args: JsonObject): JsonObject;
    taskStateGet(args: JsonObject): JsonObject;
    taskStateReplay(args: JsonObject): JsonObject;
    legacyKnowledgeMigrationDiscover(args: JsonObject): Promise<JsonObject>;
    legacyKnowledgeMigrationCandidateImport(args: JsonObject): Promise<JsonObject>;
    legacyKnowledgeMigrationPublish(args: JsonObject): Promise<JsonObject>;
    legacyKnowledgeMigrationRetract(args: JsonObject): Promise<JsonObject>;
    legacyKnowledgeMigrationFailureReport(args: JsonObject): JsonObject;
    knowledgeSourceSnapshot(args: JsonObject): JsonObject;
    knowledgeSourceDiff(args: JsonObject): Promise<JsonObject>;
    knowledgeCandidateImport(args: JsonObject): Promise<JsonObject>;
    knowledgeCandidateReview(args: JsonObject): JsonObject;
    knowledgeCandidatePublish(args: JsonObject): Promise<JsonObject>;
    knowledgeCandidateRetract(args: JsonObject): Promise<JsonObject>;
    knowledgeMigrationFailureReport(args: JsonObject): JsonObject;
    knowledgeExpirySweep(args?: JsonObject): JsonObject;
    knowledgeConflictResolve(args: JsonObject): JsonObject;
    turnPolicySave(args: JsonObject): JsonObject;
    turnPolicyGet(args: JsonObject): JsonObject;
    turnProposalSubmit(args: JsonObject): JsonObject;
    turnHostAdapterSave(args: JsonObject): JsonObject;
    turnHookPlan(args: JsonObject): JsonObject;
    turnIntakeAssess(args: JsonObject): JsonObject;
    turnReceiptGet(args: JsonObject): JsonObject;
    turnMemoryCandidateList(args?: JsonObject): JsonObject;
    turnMemoryCandidateDecide(args: JsonObject): JsonObject;
    turnEvaluationCaseSave(args: JsonObject): JsonObject;
    turnEvaluationRun(args: JsonObject): JsonObject;
    traceStart(args: JsonObject): JsonObject;
    traceAppend(args: JsonObject): JsonObject;
    traceObserve(args: JsonObject): JsonObject;
    traceFeedback(args: JsonObject): JsonObject;
    traceFinalize(args: JsonObject): JsonObject;
    traceGet(args: JsonObject): JsonObject;
    traceQuery(args?: JsonObject): JsonObject;
    traceReplayBundle(args: JsonObject): JsonObject;
    traceCaseCompile(args: JsonObject): JsonObject;
    traceRetentionPlan(args: JsonObject): JsonObject;
    traceRetentionSweep(args?: JsonObject): JsonObject;
    traceArchiveStorageRegister(args: JsonObject): JsonObject;
    traceArchiveStorageList(args?: JsonObject): JsonObject;
    traceArchiveStorageActivate(args: JsonObject): JsonObject;
    capabilityLifecycleRegister(args: JsonObject): JsonObject;
    capabilityLifecycleInstall(args: JsonObject): JsonObject;
    capabilityLifecycleActivate(args: JsonObject): JsonObject;
    capabilityLifecycleDisable(args: JsonObject): JsonObject;
    capabilityLifecycleUpgrade(args: JsonObject): JsonObject;
    capabilityLifecycleRetire(args: JsonObject): JsonObject;
    capabilityLifecycleResolve(args: JsonObject): JsonObject;
    capabilityLifecycleList(): JsonObject;
    memoryConsolidationRemember(args: JsonObject): JsonObject;
    memoryConsolidationConsolidate(args: JsonObject): JsonObject;
    memoryConsolidationResolve(args: JsonObject): JsonObject;
    memoryConsolidationSearch(args: JsonObject): JsonObject;
    remoteInteropPrepare(args: JsonObject): JsonObject;
    remoteInteropReport(args: JsonObject): JsonObject;
    remoteInteropGet(args: JsonObject): JsonObject;
    platformMemberSave(args: JsonObject): JsonObject;
    platformAuthorize(args: JsonObject): JsonObject;
    platformObserve(args: JsonObject): JsonObject;
    platformObservabilityExport(args: JsonObject): JsonObject;
    hostSessionOpen(args: JsonObject): JsonObject;
    hostSessionAppend(args: JsonObject): JsonObject;
    hostSessionResume(args: JsonObject): JsonObject;
    hostSessionGet(args: JsonObject): JsonObject;
    outcomeObserverObserve(args: JsonObject): JsonObject;
    outcomeObserverGet(args: JsonObject): JsonObject;
    durableActionLoopCreate(args: JsonObject): JsonObject;
    durableActionLoopNext(args: JsonObject): JsonObject;
    durableActionLoopPropose(args: JsonObject): JsonObject;
    durableActionLoopDispatch(args: JsonObject): JsonObject;
    durableActionLoopReport(args: JsonObject): JsonObject;
    durableActionLoopResume(args: JsonObject): JsonObject;
    durableActionLoopGet(args: JsonObject): JsonObject;
    experienceLedgerObserve(args: JsonObject): JsonObject;
    experienceLedgerCompile(args: JsonObject): JsonObject;
    experienceLedgerPropose(args: JsonObject): JsonObject;
    experienceLedgerEvaluate(args: JsonObject): JsonObject;
    experienceLedgerDecide(args: JsonObject): JsonObject;
    experienceLedgerGet(args: JsonObject): JsonObject;
  }
}

export function installKernelDelegateMethods(serviceClass: typeof CraftService): void {
  installKnowledgeMemoryMethods(serviceClass);
  installTraceMethods(serviceClass);
  installCapabilityLifecycleMethods(serviceClass);
  installMemoryConsolidationMethods(serviceClass);
  installRemoteInteropMethods(serviceClass);
  installPlatformMethods(serviceClass);
  installTurnCognitiveMethods(serviceClass);
  installHostSessionMethods(serviceClass);
  installDurableExperienceMethods(serviceClass);
  installLegacyKnowledgeMigrationMethods(serviceClass);
  serviceClass.prototype.knowledgeSourceSnapshot = function (args) { return this.legacyKnowledgeMigration.sourceSnapshot(args); };
  serviceClass.prototype.knowledgeSourceDiff = function (args) { return this.legacyKnowledgeMigration.sourceDiff(args); };
  serviceClass.prototype.knowledgeCandidateImport = function (args) { return this.legacyKnowledgeMigrationCandidateImport(args); };
  serviceClass.prototype.knowledgeCandidateReview = function (args) {
    const candidate = this.store.get("legacy_knowledge_migration_candidate", String(args.candidate_id));
    return this.knowledgeClaimReview({ claim_id: candidate.claim_id, status: args.status, reviewer: args.reviewer, reason: args.reason });
  };
  serviceClass.prototype.knowledgeCandidatePublish = function (args) { return this.legacyKnowledgeMigrationPublish(args); };
  serviceClass.prototype.knowledgeCandidateRetract = function (args) { return this.legacyKnowledgeMigrationRetract(args); };
  serviceClass.prototype.knowledgeMigrationFailureReport = function (args) { return this.legacyKnowledgeMigrationFailureReport(args); };
  serviceClass.prototype.memoryCandidatePropose = function (args) { return this.memoryGovernance.propose(args); };
  serviceClass.prototype.memoryCandidateReview = function (args) { return this.memoryGovernance.review(args); };
  serviceClass.prototype.memoryLedgerRememberApproved = function (args) { return this.memoryGovernance.remember(args); };
  serviceClass.prototype.memoryConflictList = function (args = {}) { return this.memoryGovernance.listConflicts(args); };
  serviceClass.prototype.memoryConflictResolve = function (args) { return this.memoryGovernance.resolveConflict(args); };
  serviceClass.prototype.memoryExpirySweep = function (args = {}) { return this.memoryGovernance.expirySweep(args); };
  serviceClass.prototype.memorySessionFinalize = function (args) { return this.memoryGovernance.sessionFinalize(args); };
  serviceClass.prototype.memoryConsolidateGoverned = function (args) { return this.memoryGovernance.consolidate(args); };
  serviceClass.prototype.workflowDagValidate = function (args) { return this.workflowDag.validate(args); };
  serviceClass.prototype.workflowDagSave = function (args) { return this.workflowDag.save(args); };
  serviceClass.prototype.workflowDagTransition = function (args) { return this.workflowDag.transition(args); };
  serviceClass.prototype.workflowDagCheckpoint = function (args) { return this.workflowDag.checkpoint(args); };
  serviceClass.prototype.workflowDagResume = function (args) { return this.workflowDag.resume(args); };
  serviceClass.prototype.workflowDagCancel = function (args) { return this.workflowDag.cancel(args); };
  serviceClass.prototype.workflowDagReplan = function (args) { return this.workflowDag.replan(args); };
  serviceClass.prototype.workflowDagExport = function (args) { return this.workflowDag.export(args); };
  serviceClass.prototype.workflowDagImport = function (args) { return this.workflowDag.import(args); };
  serviceClass.prototype.taskStateTransition = function (args) { return this.taskState.transition(args); };
  serviceClass.prototype.taskStateGet = function (args) { return this.taskState.get(args); };
  serviceClass.prototype.taskStateReplay = function (args) { return this.taskState.replay(args); };
}
