import type { CraftService } from "../craft-service.ts";
import type { JsonObject } from "../../store.ts";
import { installKnowledgeMemoryMethods } from "./knowledge-memory.ts";
import { installTraceMethods } from "./trace.ts";
import { installCapabilityLifecycleMethods } from "./capability-lifecycle.ts";
import { installMemoryConsolidationMethods } from "./memory-consolidation.ts";
import { installRemoteInteropMethods } from "./remote-interop.ts";
import { installPlatformMethods } from "./platform.ts";
import { installTurnCognitiveMethods } from "./turn-cognitive.ts";
import { installHostSessionMethods } from "./host-session.ts";
import { installDurableExperienceMethods } from "./durable-experience.ts";

/** Thin application use cases that delegate to one owned domain kernel. */
declare module "../craft-service.ts" {
  interface CraftService {
    knowledgeMemoryInstallBuiltins(): JsonObject;
    knowledgeSourceRegister(args: JsonObject): JsonObject;
    knowledgeSourceList(args: JsonObject): JsonObject;
    knowledgeSourceTransition(args: JsonObject): JsonObject;
    memoryLedgerRemember(args: JsonObject): JsonObject;
    memoryLedgerTransition(args: JsonObject): JsonObject;
    memoryLedgerCompatBind(args: JsonObject): JsonObject;
    contextResolutionResolve(args: JsonObject): JsonObject;
    contextResolutionGet(args: JsonObject): JsonObject;
    retrievalAdapterConfigure(args: JsonObject): JsonObject;
    retrievalAdapterEvaluate(args: JsonObject): JsonObject;
    turnPolicySave(args: JsonObject): JsonObject;
    turnPolicyGet(args: JsonObject): JsonObject;
    turnProposalSubmit(args: JsonObject): JsonObject;
    turnHostAdapterSave(args: JsonObject): JsonObject;
    turnHookPlan(args: JsonObject): JsonObject;
    turnIntakeAssess(args: JsonObject): JsonObject;
    turnReceiptGet(args: JsonObject): JsonObject;
    turnMemoryCandidateList(args?: JsonObject): JsonObject;
    turnMemoryCandidateDecide(args: JsonObject): JsonObject;
    turnEvaluationCaseSave(args: JsonObject): JsonObject;
    turnEvaluationRun(args: JsonObject): JsonObject;
    traceStart(args: JsonObject): JsonObject;
    traceAppend(args: JsonObject): JsonObject;
    traceObserve(args: JsonObject): JsonObject;
    traceFeedback(args: JsonObject): JsonObject;
    traceFinalize(args: JsonObject): JsonObject;
    traceGet(args: JsonObject): JsonObject;
    traceQuery(args?: JsonObject): JsonObject;
    traceReplayBundle(args: JsonObject): JsonObject;
    traceCaseCompile(args: JsonObject): JsonObject;
    traceRetentionPlan(args: JsonObject): JsonObject;
    traceRetentionSweep(args?: JsonObject): JsonObject;
    traceArchiveStorageRegister(args: JsonObject): JsonObject;
    traceArchiveStorageList(args?: JsonObject): JsonObject;
    traceArchiveStorageActivate(args: JsonObject): JsonObject;
    capabilityLifecycleRegister(args: JsonObject): JsonObject;
    capabilityLifecycleInstall(args: JsonObject): JsonObject;
    capabilityLifecycleActivate(args: JsonObject): JsonObject;
    capabilityLifecycleDisable(args: JsonObject): JsonObject;
    capabilityLifecycleUpgrade(args: JsonObject): JsonObject;
    capabilityLifecycleRetire(args: JsonObject): JsonObject;
    capabilityLifecycleResolve(args: JsonObject): JsonObject;
    capabilityLifecycleList(): JsonObject;
    memoryConsolidationRemember(args: JsonObject): JsonObject;
    memoryConsolidationConsolidate(args: JsonObject): JsonObject;
    memoryConsolidationResolve(args: JsonObject): JsonObject;
    memoryConsolidationSearch(args: JsonObject): JsonObject;
    remoteInteropPrepare(args: JsonObject): JsonObject;
    remoteInteropReport(args: JsonObject): JsonObject;
    remoteInteropGet(args: JsonObject): JsonObject;
    platformMemberSave(args: JsonObject): JsonObject;
    platformAuthorize(args: JsonObject): JsonObject;
    platformObserve(args: JsonObject): JsonObject;
    platformObservabilityExport(args: JsonObject): JsonObject;
    hostSessionOpen(args: JsonObject): JsonObject;
    hostSessionAppend(args: JsonObject): JsonObject;
    hostSessionResume(args: JsonObject): JsonObject;
    hostSessionGet(args: JsonObject): JsonObject;
    outcomeObserverObserve(args: JsonObject): JsonObject;
    outcomeObserverGet(args: JsonObject): JsonObject;
    durableActionLoopCreate(args: JsonObject): JsonObject;
    durableActionLoopNext(args: JsonObject): JsonObject;
    durableActionLoopPropose(args: JsonObject): JsonObject;
    durableActionLoopDispatch(args: JsonObject): JsonObject;
    durableActionLoopReport(args: JsonObject): JsonObject;
    durableActionLoopResume(args: JsonObject): JsonObject;
    durableActionLoopGet(args: JsonObject): JsonObject;
    experienceLedgerObserve(args: JsonObject): JsonObject;
    experienceLedgerCompile(args: JsonObject): JsonObject;
    experienceLedgerPropose(args: JsonObject): JsonObject;
    experienceLedgerEvaluate(args: JsonObject): JsonObject;
    experienceLedgerDecide(args: JsonObject): JsonObject;
    experienceLedgerGet(args: JsonObject): JsonObject;
  }
}

export function installKernelDelegateMethods(serviceClass: typeof CraftService): void {
  installKnowledgeMemoryMethods(serviceClass);
  installTraceMethods(serviceClass);
  installCapabilityLifecycleMethods(serviceClass);
  installMemoryConsolidationMethods(serviceClass);
  installRemoteInteropMethods(serviceClass);
  installPlatformMethods(serviceClass);
  installTurnCognitiveMethods(serviceClass);
  installHostSessionMethods(serviceClass);
  installDurableExperienceMethods(serviceClass);
}
