import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdir, mkdtemp, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { evaluateCoverageReport, evaluateFileArtifact, evaluateMediaProbeReport, runAcceptanceAdapterTick, runBuiltinAcceptanceTicks } from "../src/acceptance-worker.ts";
import { craftPaths } from "../src/paths.ts";
import { CraftService } from "../src/service.ts";
import { McpServer } from "../src/mcp.ts";
import { CraftStore, type JsonObject } from "../src/store.ts";

function job(workspace: string, relativePath: string, configuration: JsonObject = {}, extra: JsonObject = {}): JsonObject { return { input: { workspace, relative_path: relativePath, ...extra }, evaluator_configuration: configuration }; }

test("file artifact evaluator checks portable paths, types, size, extension, and digest", async () => {
  const root = await mkdtemp(join(tmpdir(), "craft-file-evaluator-")); const content = Buffer.from("artifact"); await writeFile(join(root, "result.txt"), content); await mkdir(join(root, "folder")); await symlink(join(root, "folder"), join(root, "linked-folder"), "junction"); const digest = createHash("sha256").update(content).digest("hex");
  assert.equal((await evaluateFileArtifact(job(root, "missing.txt"))).result, "failed"); assert.equal((await evaluateFileArtifact(job(root, "."))).result, "failed"); assert.equal((await evaluateFileArtifact(job(root, "folder"))).result, "failed"); assert.equal((await evaluateFileArtifact(job(root, "linked-folder"))).result, "blocked"); assert.equal((await evaluateFileArtifact(job(root, "result.txt", { max_bytes: 1 }))).result, "failed"); assert.equal((await evaluateFileArtifact(job(root, "result.txt", { allowed_extensions: [".MP4"] }))).result, "failed"); assert.equal((await evaluateFileArtifact(job(root, "result.txt", {}, { expected_sha256: "0".repeat(64) }))).result, "failed");
  const passed = await evaluateFileArtifact(job(root, "result.txt", { allowed_extensions: [".TXT"] }, { expected_sha256: digest.toUpperCase() })); assert.equal(passed.result, "passed"); assert.equal((passed.receipt as JsonObject).digest_match, true); const defaultPass = await evaluateFileArtifact(job(root, "result.txt")); assert.equal((defaultPass.receipt as JsonObject).digest_match, null);
  await assert.rejects(() => evaluateFileArtifact(job(root, join(root, "result.txt"))), /relative/); await assert.rejects(() => evaluateFileArtifact(job(root, "../outside")), /escapes/); await assert.rejects(() => evaluateFileArtifact(job(root, "result.txt", { max_bytes: 0 })), /positive/); await assert.rejects(() => evaluateFileArtifact(job(root, "result.txt", { allowed_extensions: "txt" })), /extensions/); await assert.rejects(() => evaluateFileArtifact(job(root, "result.txt", { allowed_extensions: ["txt"] })), /extensions/);
});

test("adapter SDK tick reports successes and isolates evaluator failures", async () => {
  const root = await mkdtemp(join(tmpdir(), "craft-worker-")); const store = await new CraftStore(craftPaths(root)).open(); const service = new CraftService(store); try { const task = service.taskOpen({ title: "Files", goal: "Verify" }).task as JsonObject; store.create("host_run", "completed-run", { status: "completed" }); store.create("work_launch", "launch", { task_id: task.id, run_id: "completed-run" }); const evaluator = service.acceptanceEvaluatorSave({ evaluator_id: "file", name: "File", method: "program", adapter_id: "file-adapter" });
    for (const id of ["ok", "error", "string"]) { const plan = service.acceptancePlanSave({ plan_id: `plan-${id}`, task_id: task.id, launch_id: "launch", criteria: [{ id, name: id, method: "program" }] }).plan as JsonObject; service.acceptanceEvaluationPrepare({ job_id: `job-${id}`, plan_id: plan.id, criterion_id: id, evaluator_id: evaluator.id }); }
    let index = 0; const result = await runAcceptanceAdapterTick(service, "file-adapter", async () => { index += 1; if (index === 2) throw new TypeError("private detail"); if (index === 3) throw "private detail"; return { result: "passed", summary: "Verified", receipt: { check: "stub" } }; }, { limit: 3, leaseSeconds: 30 }); assert.equal(result.claimed, 3); const reports = result.reports as JsonObject[]; assert.equal(((reports[0].job as JsonObject).status), "completed"); assert.deepEqual(reports.slice(1).map((item) => (item.check as JsonObject).result), ["blocked", "blocked"]); assert.deepEqual(reports.slice(1).map((item) => ((item.evidence as JsonObject).metadata as JsonObject).receipt_digest !== undefined), [true, true]);
    const noReceiptPlan = service.acceptancePlanSave({ plan_id: "plan-no-receipt", task_id: task.id, launch_id: "launch", criteria: [{ id: "none", name: "none", method: "program" }] }).plan as JsonObject; service.acceptanceEvaluationPrepare({ job_id: "job-no-receipt", plan_id: noReceiptPlan.id, criterion_id: "none", evaluator_id: evaluator.id }); const noReceipt = await runAcceptanceAdapterTick(service, "file-adapter", async () => ({ result: "passed", summary: "No extra receipt" })); assert.equal(noReceipt.claimed, 1); assert.equal((await runAcceptanceAdapterTick(service, "file-adapter", async () => ({ result: "passed", summary: "none" }))).claimed, 0); await assert.rejects(() => runAcceptanceAdapterTick(service, " ", async () => ({ result: "passed", summary: "x" })), /adapter_id/);
  } finally { store.close(); }
});

test("coverage and media evaluators enforce machine-readable domain facts", async () => {
  const root = await mkdtemp(join(tmpdir(), "craft-domain-evaluator-")); const coverage = { total: { lines: { pct: 100 }, branches: { pct: 99 }, functions: { pct: 100 }, statements: { pct: 100 } } }; await writeFile(join(root, "coverage.json"), JSON.stringify(coverage)); const coverageJob = job(root, "coverage.json", { lines_threshold: 100, branches_threshold: 100, functions_threshold: 90, statements_threshold: 90 }); const coverageFailed = await evaluateCoverageReport(coverageJob); assert.equal(coverageFailed.result, "failed"); assert.deepEqual((coverageFailed.receipt as JsonObject).failed_metrics, ["branches"]); coverage.total.branches.pct = 100; await writeFile(join(root, "coverage.json"), JSON.stringify(coverage)); assert.equal((await evaluateCoverageReport(coverageJob)).result, "passed");
  const probe: JsonObject = { streams: [{ codec_type: "video", codec_name: "h264", width: 1920, height: 1080 }, { codec_type: "audio", codec_name: "aac" }], format: { duration: "12.5" } }; await writeFile(join(root, "probe.json"), JSON.stringify(probe)); const media = await evaluateMediaProbeReport(job(root, "probe.json", { min_duration_seconds: 10, min_width: 1280, min_height: 720 })); assert.equal(media.result, "passed"); assert.equal((media.receipt as JsonObject).audio_streams, 1); probe.streams = [{ codec_type: "audio", codec_name: "aac" }]; probe.format = { duration: "1" }; await writeFile(join(root, "probe.json"), JSON.stringify(probe)); assert.equal((await evaluateMediaProbeReport(job(root, "probe.json", { min_duration_seconds: 2, min_width: 1, min_height: 1 }))).result, "failed");
});

test("structured domain evidence fails closed on unsafe files and malformed metrics", async () => {
  const root = await mkdtemp(join(tmpdir(), "craft-domain-guards-")); await writeFile(join(root, "array.json"), "[]"); await writeFile(join(root, "null.json"), "null"); await writeFile(join(root, "bad.json"), "{"); await writeFile(join(root, "empty.json"), "{}"); await writeFile(join(root, "large.json"), Buffer.alloc(10 * 1024 * 1024 + 1)); await mkdir(join(root, "folder")); await symlink(join(root, "folder"), join(root, "link.json"), "junction");
  await assert.rejects(() => evaluateCoverageReport(job(root, join(root, "empty.json"))), /relative/); await assert.rejects(() => evaluateCoverageReport(job(root, "../outside.json")), /escapes/); for (const name of ["folder", "link.json", "large.json"]) await assert.rejects(() => evaluateCoverageReport(job(root, name)), /regular/); await assert.rejects(() => evaluateCoverageReport(job(root, "bad.json")), /JSON/); for (const name of ["array.json", "null.json"]) await assert.rejects(() => evaluateCoverageReport(job(root, name)), /object/); await assert.rejects(() => evaluateCoverageReport(job(root, "empty.json")), /total object/);
  for (const value of ["bad", -1]) { await writeFile(join(root, "metric.json"), JSON.stringify({ total: { lines: { pct: value }, branches: { pct: 1 }, functions: { pct: 1 }, statements: { pct: 1 } } })); await assert.rejects(() => evaluateCoverageReport(job(root, "metric.json")), /finite/); } for (const lines of [null, []]) { await writeFile(join(root, "metric.json"), JSON.stringify({ total: { lines, branches: { pct: 1 }, functions: { pct: 1 }, statements: { pct: 1 } } })); await assert.rejects(() => evaluateCoverageReport(job(root, "metric.json")), /missing/); } await writeFile(join(root, "metric.json"), JSON.stringify({ total: { lines: {}, branches: { pct: 1 }, functions: { pct: 1 }, statements: { pct: 1 } } })); await assert.rejects(() => evaluateCoverageReport(job(root, "metric.json")), /finite/); await writeFile(join(root, "metric.json"), JSON.stringify({ total: { lines: { pct: 1 }, branches: { pct: 1 }, functions: { pct: 1 }, statements: { pct: 1 } } })); await assert.rejects(() => evaluateCoverageReport(job(root, "metric.json", { lines_threshold: 101 })), /exceed/); await assert.rejects(() => evaluateCoverageReport(job(root, "metric.json", { lines_threshold: -1 })), /finite/);
  await assert.rejects(() => evaluateMediaProbeReport(job(root, "empty.json")), /streams and format/); await writeFile(join(root, "probe.json"), JSON.stringify({ streams: [], format: { duration: "bad" } })); await assert.rejects(() => evaluateMediaProbeReport(job(root, "probe.json")), /finite/); await writeFile(join(root, "probe.json"), JSON.stringify({ streams: [{ codec_type: "video", width: "bad", height: 1 }], format: { duration: 1 } })); await assert.rejects(() => evaluateMediaProbeReport(job(root, "probe.json")), /video.width/);
});

test("built-in acceptance runner keeps file, coverage, and media adapters isolated", async () => {
  const root = await mkdtemp(join(tmpdir(), "craft-builtins-")); const store = await new CraftStore(craftPaths(root)).open(); const service = new CraftService(store); try { const mcp = new McpServer(service, "full"); const task = service.taskOpen({ title: "Domains", goal: "Verify all" }).task as JsonObject; store.create("host_run", "done", { status: "completed" }); store.create("work_launch", "launch", { task_id: task.id, run_id: "done" }); const plan = service.acceptancePlanSave({ task_id: task.id, launch_id: "launch", name: "All", criteria: [{ id: "file", name: "file", method: "program" }, { id: "coverage", name: "coverage", method: "program" }, { id: "media", name: "media", method: "program" }] }).plan as JsonObject; await writeFile(join(root, "result.txt"), "ok"); await writeFile(join(root, "coverage.json"), JSON.stringify({ total: { lines: { pct: 100 }, branches: { pct: 100 }, functions: { pct: 100 }, statements: { pct: 100 } } })); await writeFile(join(root, "probe.json"), JSON.stringify({ streams: [{ codec_type: "video", width: 1, height: 1 }], format: { duration: 1 } })); service.acceptanceFileEvaluationPrepare({ plan_id: plan.id, criterion_id: "file", workspace: root, relative_path: "result.txt" }); await mcp.handlers.craft_acceptance_coverage_prepare({ plan_id: plan.id, criterion_id: "coverage", workspace: root, relative_path: "coverage.json", lines_threshold: 100 }); await mcp.handlers.craft_acceptance_media_probe_prepare({ plan_id: plan.id, criterion_id: "media", workspace: root, relative_path: "probe.json", min_width: 1 }); assert.throws(() => service.acceptanceCoverageEvaluationPrepare({ plan_id: plan.id, criterion_id: "coverage", workspace: root, relative_path: "coverage.json", lines_threshold: 101 }), /between/); assert.throws(() => service.acceptanceMediaProbePrepare({ plan_id: plan.id, criterion_id: "media", workspace: root, relative_path: "probe.json", min_width: -1 }), /non-negative/); const result = await runBuiltinAcceptanceTicks(service); assert.deepEqual([result.file, result.coverage, result.media].map((item) => (item as JsonObject).claimed), [1, 1, 1]); assert.equal((service.acceptanceAssess({ plan_id: plan.id }).assessment as JsonObject).status, "passed"); } finally { store.close(); }
});
