import assert from "node:assert/strict";
import { join } from "node:path";
import { tmpdir } from "node:os";
import test from "node:test";
import { McpServer } from "../src/mcp.ts";
import { craftPaths } from "../src/paths.ts";
import { CraftService } from "../src/service.ts";
import { CraftStore, type JsonObject } from "../src/store.ts";

async function fixture(name: string) { const store = await new CraftStore(craftPaths(join(tmpdir(), `craft-acceptance-runner-${name}-${process.pid}-${Date.now()}`))).open(); const service = new CraftService(store); const task = service.taskOpen({ title: "Domain delivery", goal: "Verify it" }).task as JsonObject; store.create("host_run", "completed-run", { status: "completed" }); store.create("work_launch", "launch", { task_id: task.id, run_id: "completed-run" }); return { store, service, task }; }

test("domain adapters lease exact evaluator jobs and turn receipts into acceptance evidence", async () => {
  const f = await fixture("happy"); try {
    const mcp = new McpServer(f.service, "full"); const generated = f.service.acceptanceEvaluatorSave({ name: "Generated", method: "program", adapter_id: "unused" }); assert.match(String(generated.id), /^acceptance_evaluator_/); const evaluator = await mcp.handlers.craft_acceptance_evaluator_save({ evaluator_id: "checker", name: "Format checker", method: "program", adapter_id: "media-worker", configuration: { format: "mp4" } }) as JsonObject;
    const plan = f.service.acceptancePlanSave({ task_id: f.task.id, launch_id: "launch", criteria: [{ id: "format", name: "Playable MP4", method: "program" }] }).plan as JsonObject; const file = await mcp.handlers.craft_acceptance_file_prepare({ job_id: "file-job", plan_id: plan.id, criterion_id: "format", workspace: f.store.paths.root, relative_path: "final.mp4", allowed_extensions: [".mp4"], max_bytes: 10_000, expected_sha256: "0".repeat(64) }) as JsonObject; assert.equal(file.idempotent, false); assert.equal((await mcp.handlers.craft_acceptance_file_prepare({ job_id: "file-job", plan_id: plan.id, criterion_id: "format", workspace: f.store.paths.root, relative_path: "final.mp4", allowed_extensions: [".mp4"], max_bytes: 10_000, expected_sha256: "0".repeat(64) }) as JsonObject).idempotent, true); assert.equal(f.service.acceptanceFileEvaluationPrepare({ plan_id: plan.id, criterion_id: "format", workspace: f.store.paths.root, relative_path: "other.mp4" }).idempotent, false);
    const prepared = await mcp.handlers.craft_acceptance_evaluation_prepare({ job_id: "job", plan_id: plan.id, criterion_id: "format", evaluator_id: evaluator.id, evaluator_version: evaluator.version, input: { artifact: "final.mp4" } }) as JsonObject; assert.equal(prepared.idempotent, false); assert.equal((await mcp.handlers.craft_acceptance_evaluation_prepare({ job_id: "job", plan_id: plan.id, criterion_id: "format", evaluator_id: evaluator.id, evaluator_version: evaluator.version, input: { artifact: "final.mp4" } }) as JsonObject).idempotent, true);
    assert.deepEqual((await mcp.handlers.craft_acceptance_evaluation_claim({ adapter_id: "other" }) as JsonObject).jobs, []); const claimed = await mcp.handlers.craft_acceptance_evaluation_claim({ adapter_id: "media-worker", plan_id: plan.id, limit: 1, lease_seconds: 30 }) as JsonObject; const job = (claimed.jobs as JsonObject[])[0];
    const artifact = f.service.artifactRegister({ artifact_id: "probe-receipt", kind: "acceptance_receipt", name: "Media probe", uri: "craft://probe/1" }); const reported = await mcp.handlers.craft_acceptance_evaluation_report({ job_id: job.id, lease_id: job.lease_id, adapter_id: "media-worker", result: "passed", summary: "Container probe decoded the output", receipt: { decoder: "probe-v1", artifact_id: artifact.id } }) as JsonObject; assert.equal((reported.job as JsonObject).status, "completed"); assert.equal((reported.evidence as JsonObject).confidence, "confirmed"); assert.equal((reported.evidence as JsonObject).artifact_id, artifact.id); assert.equal((reported.assessment as JsonObject).status, "passed"); assert.equal((reported.outcome as JsonObject).verdict, "passed");
    const replay = await mcp.handlers.craft_acceptance_evaluation_report({ job_id: job.id, lease_id: "already-consumed", adapter_id: "media-worker", result: "passed", summary: "Container probe decoded the output", receipt: { decoder: "probe-v1", artifact_id: artifact.id } }) as JsonObject; assert.equal(replay.idempotent, true); assert.throws(() => f.service.acceptanceEvaluationReport({ job_id: job.id, lease_id: "x", adapter_id: "media-worker", result: "passed", summary: "drift", receipt: {} }), /idempotency conflict/);
  } finally { f.store.close(); }
});

test("evaluation jobs preserve failed and blocked signals and reject ambiguous authority", async () => {
  const f = await fixture("guards"); try {
    assert.throws(() => f.service.acceptanceEvaluatorSave({ name: "Human", method: "human", adapter_id: "x" }), /must be/); assert.throws(() => f.service.acceptanceEvaluatorSave({ name: "Bad", method: "magic", adapter_id: "x" }), /must be/); assert.throws(() => f.service.acceptanceEvaluatorSave({ name: "Bad", method: "program", adapter_id: "x", configuration: [] }), /configuration/); assert.throws(() => f.service.acceptanceEvaluatorSave({ name: "Secret", method: "program", adapter_id: "x", configuration: { api_key: "secret-value" } }), /sensitive assignments/);
    const disabled = f.service.acceptanceEvaluatorSave({ evaluator_id: "disabled", name: "Disabled", method: "model", adapter_id: "judge", enabled: false }); const model = f.service.acceptanceEvaluatorSave({ evaluator_id: "model", name: "Rubric", method: "model", adapter_id: "judge" }); const signal = f.service.acceptanceEvaluatorSave({ evaluator_id: "signal", name: "Metric", method: "business_signal", adapter_id: "metrics", max_attempts: 2 });
    const plan = f.service.acceptancePlanSave({ task_id: f.task.id, launch_id: "launch", criteria: [{ id: "quality", name: "Quality", method: "model" }, { id: "impact", name: "Impact", method: "business_signal" }, { id: "owner", name: "Owner", method: "human", required: false }] }).plan as JsonObject;
    assert.throws(() => f.service.acceptanceEvaluationPrepare({ plan_id: plan.id, criterion_id: "missing", evaluator_id: model.id }), /unknown/); assert.throws(() => f.service.acceptanceEvaluationPrepare({ plan_id: plan.id, criterion_id: "owner", evaluator_id: model.id }), /Human/); assert.throws(() => f.service.acceptanceEvaluationPrepare({ plan_id: plan.id, criterion_id: "quality", evaluator_id: disabled.id }), /disabled/); assert.throws(() => f.service.acceptanceEvaluationPrepare({ plan_id: plan.id, criterion_id: "impact", evaluator_id: model.id }), /does not match/);
    const first = f.service.acceptanceEvaluationPrepare({ job_id: "model-job", plan_id: plan.id, criterion_id: "quality", evaluator_id: model.id }); assert.throws(() => f.service.acceptanceEvaluationPrepare({ job_id: "secret-job", plan_id: plan.id, criterion_id: "quality", evaluator_id: model.id, input: { token: "secret-value" } }), /sensitive assignments/); assert.throws(() => f.service.acceptanceEvaluationPrepare({ job_id: "model-job", plan_id: plan.id, criterion_id: "quality", evaluator_id: model.id, input: { drift: true } }), /idempotency conflict/); const signalJob = f.service.acceptanceEvaluationPrepare({ plan_id: plan.id, criterion_id: "impact", evaluator_id: signal.id }).job as JsonObject;
    const gateJob = { status: "ready", attempts: 0, max_attempts: 2, adapter_id: "gate", plan_id: "missing" }; f.store.create("acceptance_evaluation_job", "gate-missing-plan", gateJob); assert.deepEqual(f.service.acceptanceEvaluationClaim({ adapter_id: "gate" }).jobs, []); f.store.create("acceptance_plan", "gate-plan", { launch_id: "missing-launch" }); f.store.create("acceptance_evaluation_job", "gate-missing-launch", { ...gateJob, plan_id: "gate-plan" }); assert.deepEqual(f.service.acceptanceEvaluationClaim({ adapter_id: "gate" }).jobs, []); f.store.create("work_launch", "gate-launch", { task_id: f.task.id }); f.store.save("acceptance_plan", "gate-plan", { launch_id: "gate-launch" }); assert.deepEqual(f.service.acceptanceEvaluationClaim({ adapter_id: "gate" }).jobs, []); f.store.create("host_run", "gate-running", { status: "running" }); f.store.save("work_launch", "gate-launch", { task_id: f.task.id, run_id: "gate-running" }); assert.deepEqual(f.service.acceptanceEvaluationClaim({ adapter_id: "gate" }).jobs, []);
    assert.throws(() => f.service.acceptanceEvaluationReport({ job_id: (first.job as JsonObject).id, lease_id: "none", adapter_id: "judge", result: "maybe", summary: "x" }), /unsupported/); assert.throws(() => f.service.acceptanceEvaluationReport({ job_id: (first.job as JsonObject).id, lease_id: "none", adapter_id: "judge", result: "failed", summary: "x" }), /lease does not match/);
    const modelLease = (f.service.acceptanceEvaluationClaim({ adapter_id: "judge" }).jobs as JsonObject[])[0]; assert.throws(() => f.service.acceptanceEvaluationReport({ job_id: modelLease.id, lease_id: modelLease.lease_id, adapter_id: "judge", result: "failed", summary: "Rubric failed", receipt: { password: "secret-value" } }), /sensitive assignments/); assert.throws(() => f.service.acceptanceEvaluationReport({ job_id: modelLease.id, lease_id: modelLease.lease_id, adapter_id: "wrong", result: "failed", summary: "Rubric failed" }), /not authorized/); const failed = f.service.acceptanceEvaluationReport({ job_id: modelLease.id, lease_id: modelLease.lease_id, adapter_id: "judge", result: "failed", summary: "Rubric failed" }); assert.equal((failed.evidence as JsonObject).confidence, "rejected"); assert.equal((failed.assessment as JsonObject).status, "pending");
    const signalLease = (f.service.acceptanceEvaluationClaim({ adapter_id: "metrics" }).jobs as JsonObject[]).find((item) => item.id === signalJob.id) as JsonObject; f.store.save("acceptance_evaluation_job", String(signalLease.id), { ...signalLease, lease_expires_at: new Date(0).toISOString() }); assert.throws(() => f.service.acceptanceEvaluationReport({ job_id: signalLease.id, lease_id: signalLease.lease_id, adapter_id: "metrics", result: "blocked", summary: "No metric" }), /expired/); assert.throws(() => f.service.acceptanceEvaluationRecover({ now: "bad" }), /ISO/); assert.equal(f.service.acceptanceEvaluationRecover({ now: "1970-01-01T00:00:01.000Z", limit: 1 }).recovered, 1); const renewed = (f.service.acceptanceEvaluationClaim({ adapter_id: "metrics" }).jobs as JsonObject[])[0]; const blocked = f.service.acceptanceEvaluationReport({ job_id: renewed.id, lease_id: renewed.lease_id, adapter_id: "metrics", result: "blocked", summary: "No metric", receipt: {} }); assert.equal((blocked.evidence as JsonObject).confidence, "bounded"); assert.equal((blocked.assessment as JsonObject).status, "failed");
    const exhaustedEvaluator = f.service.acceptanceEvaluatorSave({ evaluator_id: "once", name: "Once", method: "model", adapter_id: "once", max_attempts: 1 }); const exhaustedPlan = f.service.acceptancePlanSave({ plan_id: "exhausted-plan", task_id: f.task.id, launch_id: "launch", criteria: [{ id: "once", name: "Once", method: "model" }] }).plan as JsonObject; f.service.acceptanceEvaluationPrepare({ plan_id: exhaustedPlan.id, criterion_id: "once", evaluator_id: exhaustedEvaluator.id }); const exhaustedLease = (f.service.acceptanceEvaluationClaim({ adapter_id: "once" }).jobs as JsonObject[])[0]; f.store.save("acceptance_evaluation_job", String(exhaustedLease.id), { ...exhaustedLease, lease_expires_at: new Date(0).toISOString() }); const recovery = await new McpServer(f.service, "full").handlers.craft_acceptance_evaluation_recover({ now: "1970-01-01T00:00:01.000Z" }) as JsonObject; assert.equal(recovery.exhausted, 1); assert.deepEqual(f.service.acceptanceEvaluationClaim({ adapter_id: "once" }).jobs, []); f.store.save("acceptance_evaluation_job", String(exhaustedLease.id), { ...exhaustedLease, status: "ready", attempts: 1, lease_id: null, lease_expires_at: null }); assert.deepEqual(f.service.acceptanceEvaluationClaim({ adapter_id: "once" }).jobs, []); assert.equal(f.service.acceptanceEvaluationRecover({}).recovered, 0); f.store.save("acceptance_evaluation_job", String(exhaustedLease.id), { ...exhaustedLease, status: "exhausted", lease_id: null, lease_expires_at: null }); f.service.attentionRefresh({}); assert.equal((f.service.attentionList({ audience: "operator" }).items as JsonObject[]).some((item) => item.action === "inspect_acceptance_evaluator"), true);
    f.store.save("acceptance_plan", String(plan.id), { ...plan, status: "retired" }); assert.throws(() => f.service.acceptanceEvaluationPrepare({ plan_id: plan.id, criterion_id: "quality", evaluator_id: model.id, job_id: "retired" }), /not active/);
  } finally { f.store.close(); }
});
