import assert from "node:assert/strict";
import { join } from "node:path";
import { tmpdir } from "node:os";
import test from "node:test";
import { McpServer } from "../src/mcp.ts";
import { craftPaths } from "../src/paths.ts";
import { CraftService } from "../src/service.ts";
import { CraftStore, type JsonObject } from "../src/store.ts";

async function fixture(name: string) { const store = await new CraftStore(craftPaths(join(tmpdir(), `craft-domain-kit-${name}-${process.pid}-${Date.now()}`))).open(); const service = new CraftService(store); return { store, service, mcp: new McpServer(service, "full") }; }
function launch(f: Awaited<ReturnType<typeof fixture>>, suffix: string) { f.store.create("task", `task-${suffix}`, { title: suffix, goal: "Deliver", status: "active" }); f.store.create("host_run", `run-${suffix}`, { status: "completed" }); return f.store.create("work_launch", `launch-${suffix}`, { task_id: `task-${suffix}`, run_id: `run-${suffix}`, workspace: f.store.paths.root }); }

test("versioned Domain Kits validate forms and bind built-in software and video acceptance", async () => {
  const f = await fixture("happy"); try {
    const installed = await f.mcp.handlers.craft_domain_kit_install_builtins({}) as JsonObject; assert.equal((installed.kits as JsonObject[]).length, 2); assert.equal(((await f.mcp.handlers.craft_domain_kit_install_builtins({}) as JsonObject).kits as JsonObject[]).every((kit) => kit.version === 1), true);
    assert.equal(((await f.mcp.handlers.craft_domain_kit_list({ limit: 10 }) as JsonObject).kits as JsonObject[]).length, 2); const developer = await f.mcp.handlers.craft_domain_kit_get({ kit_id: "builtin.developer-delivery", kit_version: 1 }) as JsonObject; assert.equal(developer.domain, "software");
    launch(f, "dev"); const applied = await f.mcp.handlers.craft_domain_kit_apply({ application_id: "dev-app", kit_id: developer.id, kit_version: 1, launch_id: "launch-dev", values: { artifact_path: "dist/app.js" } }) as JsonObject; assert.equal((applied.jobs as JsonObject[]).length, 1); assert.equal((applied.application as JsonObject).kit_version, 1); assert.equal((await f.mcp.handlers.craft_domain_kit_apply({ application_id: "dev-app", kit_id: developer.id, kit_version: 1, launch_id: "launch-dev", values: { artifact_path: "dist/app.js" } }) as JsonObject).idempotent, true); assert.throws(() => f.mcp.handlers.craft_domain_kit_apply({ application_id: "dev-app", kit_id: developer.id, launch_id: "launch-dev", values: { artifact_path: "other.js" } }), /idempotency conflict/);
    launch(f, "video"); const video = f.service.domainKitApply({ kit_id: "builtin.video-delivery", launch_id: "launch-video", values: { video_path: "output/final.mp4" } }); assert.equal((video.jobs as JsonObject[]).length, 1); const evaluator = f.store.get("acceptance_evaluator", String((video.jobs as JsonObject[])[0].evaluator_id)); assert.deepEqual(evaluator.configuration, { allowed_extensions: [".mp4", ".mov", ".webm"], max_bytes: 10_000_000_000 }); assert.equal(((video.plan as JsonObject).criteria as JsonObject[]).some((criterion) => criterion.method === "human"), true);
  } finally { f.store.close(); }
});

test("custom Domain Kit schemas cover typed fields, optional values, versioning, and MCP", async () => {
  const f = await fixture("custom"); try {
    const definition = { name: "Campaign", domain: "sales", description: "Prepare a campaign", fields: [{ id: "title", label: "Title", type: "text" }, { id: "folder", label: "Folder", type: "path" }, { id: "count", label: "Count", type: "integer" }, { id: "approved", label: "Approved", type: "boolean" }, { id: "channel", label: "Channel", type: "choice", options: ["email", "social"] }, { id: "note", label: "Note", type: "text", required: false }], criteria: [{ id: "owner", name: "Owner accepts", method: "human", required: false }] };
    const first = await f.mcp.handlers.craft_domain_kit_save({ kit_id: "campaign", ...definition }) as JsonObject; const second = f.service.domainKitSave({ kit_id: "campaign", ...definition }); assert.equal(first.version, 1); assert.equal(second.version, 2); assert.match(String(f.service.domainKitSave({ ...definition }).id), /^domain_kit_/); assert.equal(f.service.domainKitList({}).kits instanceof Array, true);
    launch(f, "custom"); const result = f.service.domainKitApply({ kit_id: "campaign", kit_version: 2, launch_id: "launch-custom", values: { title: "Launch", folder: "out", count: 0, approved: false, channel: "email" } }); assert.deepEqual((result.application as JsonObject).values, { title: "Launch", folder: "out", count: 0, approved: false, channel: "email" }); assert.deepEqual(result.jobs, []);
  } finally { f.store.close(); }
});

test("Domain Kit definitions and applications fail closed on ambiguous forms", async () => {
  const f = await fixture("guards"); try {
    const base = { name: "Kit", domain: "test", description: "Test", fields: [{ id: "path", label: "Path", type: "path" }], criteria: [{ id: "file", name: "File", method: "program", evaluator: { type: "file", path_field: "path" } }] };
    for (const fields of [[], [{ id: "x", label: "X", type: "magic" }], [{ id: "x", label: "X", type: "choice" }], [{ id: "x", label: "X", type: "text", options: ["x"] }], [{ id: "x", label: "X", type: "text" }, { id: "x", label: "Y", type: "text" }]]) assert.throws(() => f.service.domainKitSave({ ...base, fields }), /fields|unsupported|options/);
    for (const criteria of [[], [{ id: "x", name: "X", method: "magic" }], [{ id: "x", name: "X", method: "model", evaluator: { type: "file", path_field: "path" } }], [{ id: "x", name: "X", method: "program", evaluator: { type: "other", path_field: "path" } }], [{ id: "x", name: "X", method: "program", evaluator: { type: "file", path_field: "missing" } }], [{ id: "x", name: "X", method: "human" }, { id: "x", name: "Y", method: "human" }]]) assert.throws(() => f.service.domainKitSave({ ...base, criteria }), /criteria|unsupported|supports|path_field/);
    f.service.domainKitSave({ kit_id: "guard", name: "Guard", domain: "test", description: "Guard", fields: [{ id: "flag", label: "Flag", type: "boolean" }, { id: "count", label: "Count", type: "integer" }, { id: "choice", label: "Choice", type: "choice", options: ["a"] }], criteria: [{ id: "human", name: "Human", method: "human" }] }); launch(f, "guard");
    for (const values of [{ extra: "x", flag: true, count: 1, choice: "a" }, { count: 1, choice: "a" }, { flag: "yes", count: 1, choice: "a" }, { flag: true, count: -1, choice: "a" }, { flag: true, count: 1, choice: "b" }]) assert.throws(() => f.service.domainKitApply({ kit_id: "guard", launch_id: "launch-guard", values }), /Unknown|Missing|required|boolean|integer|choices/);
    f.service.domainKitSave({ kit_id: "path-guard", ...base }); launch(f, "path"); for (const path of ["../outside", "C:\\outside.txt"]) assert.throws(() => f.service.domainKitApply({ kit_id: "path-guard", launch_id: "launch-path", values: { path } }), /relative contained/);
    const conflict = await fixture("builtin-conflict"); try { conflict.store.create("domain_kit", "builtin.developer-delivery", { definition_digest: "wrong" }); assert.throws(() => conflict.service.domainKitInstallBuiltins(), /identity conflict/); } finally { conflict.store.close(); }
  } finally { f.store.close(); }
});

test("Domain Kits pin eligible capabilities, evaluation suites, sandbox tickets, budgets, objects, components, and actions", async () => {
  const f = await fixture("contract"); try {
    const asset = f.service.capabilityAssetSave({ asset_id: "renderer", name: "Renderer", asset_type: "tool", source_uri: "local://renderer", effect: "read_only", trust: "verified", health: "healthy" }); const suite = f.service.evaluationSuiteSave({ suite_id: "delivery-suite", name: "Delivery", cases: [] });
    f.store.create("sandbox_profile", "verified-sandbox", { lifecycle: "verified", adapter_id: "local", capability_digest: "digest", capabilities: { filesystem: "read_only", network: "denied", features: ["cancel"], limits: { cpu_seconds: 5 } } });
    const kit = f.service.domainKitSave({ kit_id: "full-kit", name: "Full", domain: "content", description: "Full contract", fields: [{ id: "artifact", label: "Artifact", type: "path" }], criteria: [{ id: "file", name: "File", method: "program", evaluator: { type: "file", path_field: "artifact" } }], capability_requirements: [{ asset_id: asset.id, asset_version: asset.version, required_trust: "verified", effect: "read_only" }], object_schemas: [{ id: "story", name: "Story", schema: { type: "object" } }], components: [{ id: "editor", type: "form", binds_to: "story", read_only: false }, { id: "preview", type: "artifact_preview", binds_to: "artifact" }, { id: "checks", type: "checklist", binds_to: "file" }, { id: "state", type: "status", binds_to: "file" }], action_contracts: [{ id: "inspect", effect: "read_only" }, { id: "publish", effect: "external_write", requires_approval: false }, { id: "write", effect: "local_write" }], budget_limits: { tokens: 1000, dollars: 2 }, sandbox_requirements: { filesystem: "read_only", network: "denied", features: ["cancel"], limits: { cpu_seconds: 2 } }, eval_suite_ref: { suite_id: suite.id, suite_version: suite.version } });
    assert.equal((kit.components as JsonObject[])[0].read_only, false); assert.equal((kit.components as JsonObject[])[1].read_only, true); assert.equal((kit.action_contracts as JsonObject[])[0].requires_approval, false); assert.equal((kit.action_contracts as JsonObject[])[1].requires_approval, false);
    launch(f, "contract"); f.service.budgetOpen({ budget_id: "contract-budget", owner_type: "task", owner_id: "task-contract", limits: { tokens: 2000, dollars: 4 } }); const applied = f.service.domainKitApply({ kit_id: kit.id, launch_id: "launch-contract", values: { artifact: "out.txt" }, sandbox_profile_id: "verified-sandbox", sandbox_profile_version: 1, budget_id: "contract-budget" }); assert.equal((applied.sandbox as JsonObject).compatible, true); assert.equal(((applied.application as JsonObject).resolved_assets as JsonObject[])[0].asset_version, 1); assert.deepEqual((applied.application as JsonObject).eval_suite, { suite_id: suite.id, suite_version: suite.version }); assert.equal(((applied.lock as JsonObject).assets as JsonObject[]).length, 1); assert.equal((applied.budget_reservation as JsonObject).status, "reserved"); const replay = f.service.domainKitApply({ kit_id: kit.id, launch_id: "launch-contract", values: { artifact: "out.txt" }, sandbox_profile_id: "verified-sandbox", sandbox_profile_version: 1, budget_id: "contract-budget" }); assert.equal((replay.sandbox as JsonObject).compatible, true); assert.equal((replay.budget_reservation as JsonObject).id, (applied.budget_reservation as JsonObject).id); const settled = await f.mcp.handlers.craft_domain_kit_settle({ application_id: "domain_kit_application_launch-contract", actual: { tokens: 800, dollars: 1 } }) as JsonObject; assert.equal((settled.reservation as JsonObject).status, "settled"); const settledAgain = f.service.domainKitSettle({ application_id: "domain_kit_application_launch-contract", actual: {} }); assert.equal((settledAgain.reservation as JsonObject).status, "settled"); assert.equal((settledAgain.application as JsonObject).version, (settled.application as JsonObject).version); assert.equal(settledAgain.idempotent, true);
  } finally { f.store.close(); }
});

test("Domain Kit execution contracts reject unsafe definitions and drifted runtime dependencies", async () => {
  const f = await fixture("contract-guards"); try {
    const base = { name: "Kit", domain: "test", description: "Test", fields: [{ id: "path", label: "Path", type: "path" }], criteria: [{ id: "human", name: "Human", method: "human" }] };
    for (const capability_requirements of [[{ asset_id: "x", asset_version: 1, required_trust: "untrusted", effect: "read_only" }], [{ asset_id: "x", asset_version: 1, required_trust: "trusted", effect: "magic" }], [{ asset_id: "x", asset_version: 1, effect: "read_only" }, { asset_id: "x", asset_version: 2, effect: "read_only" }]]) assert.throws(() => f.service.domainKitSave({ ...base, capability_requirements }), /trust|effect|unique/);
    for (const object_schemas of [[{ id: "x", name: "X", schema: [] }], [{ id: "x", name: "X", schema: {} }, { id: "x", name: "Y", schema: {} }]]) assert.throws(() => f.service.domainKitSave({ ...base, object_schemas }), /schema|unique/);
    for (const components of [[{ id: "x", type: "button", binds_to: "path" }], [{ id: "x", type: "form", binds_to: "path" }, { id: "x", type: "status", binds_to: "path" }]]) assert.throws(() => f.service.domainKitSave({ ...base, components }), /component|unique/);
    for (const action_contracts of [[{ id: "x", effect: "magic" }], [{ id: "x", effect: "read_only" }, { id: "x", effect: "external_write" }]]) assert.throws(() => f.service.domainKitSave({ ...base, action_contracts }), /effect|unique/);
    for (const budget_limits of [{ Bad: 1 }, { tokens: 0 }, { tokens: Number.POSITIVE_INFINITY }]) assert.throws(() => f.service.domainKitSave({ ...base, budget_limits }), /budget/);
    assert.throws(() => f.service.domainKitSave({ ...base, sandbox_requirements: [] }), /sandbox_requirements/); assert.throws(() => f.service.domainKitSave({ ...base, eval_suite_ref: [] }), /eval_suite_ref/); assert.throws(() => f.service.domainKitSave({ ...base, eval_suite_ref: { suite_id: "suite", suite_version: 0 } }), /suite_version/);
    const unhealthy = f.service.capabilityAssetSave({ asset_id: "unhealthy", name: "Bad", asset_type: "tool", source_uri: "local://bad", effect: "read_only", trust: "trusted", health: "failed" }); const kit = f.service.domainKitSave({ kit_id: "dependency-kit", ...base, capability_requirements: [{ asset_id: unhealthy.id, asset_version: unhealthy.version, effect: "read_only" }] }); launch(f, "dependency"); assert.throws(() => f.service.domainKitApply({ kit_id: kit.id, launch_id: "launch-dependency", values: { path: "out" } }), /not eligible/);
    const untrusted = f.service.capabilityAssetSave({ asset_id: "untrusted", name: "Untrusted", asset_type: "tool", source_uri: "local://untrusted", effect: "read_only", trust: "untrusted", health: "healthy" }); const untrustedKit = f.service.domainKitSave({ kit_id: "untrusted-kit", ...base, capability_requirements: [{ asset_id: untrusted.id, asset_version: untrusted.version, effect: "read_only" }] }); launch(f, "untrusted"); assert.throws(() => f.service.domainKitApply({ kit_id: untrustedKit.id, launch_id: "launch-untrusted", values: { path: "out" } }), /not eligible/);
    const trusted = f.service.capabilityAssetSave({ asset_id: "trusted", name: "Trusted", asset_type: "tool", source_uri: "local://trusted", effect: "read_only", trust: "trusted", health: "healthy" }); const verifiedKit = f.service.domainKitSave({ kit_id: "verified-kit", ...base, capability_requirements: [{ asset_id: trusted.id, asset_version: trusted.version, required_trust: "verified", effect: "read_only" }] }); launch(f, "verified"); assert.throws(() => f.service.domainKitApply({ kit_id: verifiedKit.id, launch_id: "launch-verified", values: { path: "out" } }), /not eligible/);
    const effectKit = f.service.domainKitSave({ kit_id: "effect-kit", ...base, capability_requirements: [{ asset_id: trusted.id, asset_version: trusted.version, effect: "external_write" }] }); launch(f, "effect"); assert.throws(() => f.service.domainKitApply({ kit_id: effectKit.id, launch_id: "launch-effect", values: { path: "out" } }), /not eligible/);
    f.store.create("sandbox_profile", "small", { lifecycle: "verified", capabilities: { filesystem: "read_only", network: "denied", features: [], limits: {} } }); const sandboxKit = f.service.domainKitSave({ kit_id: "sandbox-kit", ...base, sandbox_requirements: { filesystem: "read_only", network: "denied", features: ["cancel"], limits: {} } }); launch(f, "sandbox"); assert.throws(() => f.service.domainKitApply({ kit_id: sandboxKit.id, launch_id: "launch-sandbox", values: { path: "out" } }), /sandbox_profile_id/); assert.throws(() => f.service.domainKitApply({ kit_id: sandboxKit.id, launch_id: "launch-sandbox", values: { path: "out" }, sandbox_profile_id: "small", sandbox_profile_version: 1 }), /not satisfied/);
    const evalKit = f.service.domainKitSave({ kit_id: "eval-kit", ...base, eval_suite_ref: { suite_id: "missing", suite_version: 1 } }); launch(f, "eval"); assert.throws(() => f.service.domainKitApply({ kit_id: evalKit.id, launch_id: "launch-eval", values: { path: "out" } }), /Unknown evaluation_suite/);
    const budgetKit = f.service.domainKitSave({ kit_id: "budget-kit", ...base, budget_limits: { tokens: 2 } }); launch(f, "budget"); assert.throws(() => f.service.domainKitApply({ kit_id: budgetKit.id, launch_id: "launch-budget", values: { path: "out" } }), /budget_id/); f.service.budgetOpen({ budget_id: "foreign-budget", owner_type: "task", owner_id: "another-task", limits: { tokens: 2 } }); assert.throws(() => f.service.domainKitApply({ kit_id: budgetKit.id, launch_id: "launch-budget", values: { path: "out" }, budget_id: "foreign-budget" }), /belong/); f.service.budgetOpen({ budget_id: "owned-budget", owner_type: "task", owner_id: "task-budget", limits: { tokens: 2 } }); const budgeted = f.service.domainKitApply({ kit_id: budgetKit.id, launch_id: "launch-budget", values: { path: "out" }, budget_id: "owned-budget" }); assert.equal((f.service.domainKitSettle({ application_id: (budgeted.application as JsonObject).id }).reservation as JsonObject).status, "settled");
    launch(f, "no-budget"); f.service.budgetOpen({ budget_id: "unused-budget", owner_type: "task", owner_id: "task-no-budget", limits: { tokens: 1 } }); const noBudgetKit = f.service.domainKitSave({ kit_id: "no-budget-kit", ...base }); assert.throws(() => f.service.domainKitApply({ kit_id: noBudgetKit.id, launch_id: "launch-no-budget", values: { path: "out" }, budget_id: "unused-budget" }), /without budget limits/); const noBudget = f.service.domainKitApply({ kit_id: noBudgetKit.id, launch_id: "launch-no-budget", values: { path: "out" } }); assert.equal(f.service.domainKitSettle({ application_id: (noBudget.application as JsonObject).id }).reservation, null); assert.throws(() => f.service.domainKitSettle({ application_id: (noBudget.application as JsonObject).id, actual: { tokens: 1 } }), /no budget reservation/);
  } finally { f.store.close(); }
});

test("Domain Kit dependency locks resolve pinned transitive graphs and reject cycles or floating dependencies", async () => {
  const f = await fixture("dependency-lock"); try {
    const child = f.service.capabilityAssetSave({ asset_id: "child", name: "Child", asset_type: "tool", source_uri: "local://child", effect: "read_only", trust: "trusted", health: "healthy" }); const parent = f.service.capabilityAssetSave({ asset_id: "parent", name: "Parent", asset_type: "workflow", source_uri: "local://parent", effect: "read_only", trust: "verified", health: "healthy", dependencies: [`${child.id}@${child.version}`] }); const sibling = f.service.capabilityAssetSave({ asset_id: "sibling", name: "Sibling", asset_type: "workflow", source_uri: "local://sibling", effect: "read_only", trust: "trusted", health: "healthy", dependencies: [`${child.id}@${child.version}`] });
    const base = { name: "Graph", domain: "test", description: "Graph", fields: [{ id: "path", label: "Path", type: "path" }], criteria: [{ id: "human", name: "Human", method: "human" }] }; const kit = f.service.domainKitSave({ kit_id: "graph-kit", ...base, capability_requirements: [{ asset_id: parent.id, asset_version: parent.version, required_trust: "verified", effect: "read_only" }, { asset_id: sibling.id, asset_version: sibling.version, effect: "read_only" }] }); launch(f, "graph"); const applied = f.service.domainKitApply({ kit_id: kit.id, launch_id: "launch-graph", values: { path: "out" } }); assert.deepEqual(((applied.lock as JsonObject).assets as JsonObject[]).map((item) => item.asset_id), ["child", "parent", "sibling"]); assert.equal((((applied.lock as JsonObject).assets as JsonObject[]).find((item) => item.asset_id === "child") as JsonObject).required_by, "parent@1");
    const floating = f.service.capabilityAssetSave({ asset_id: "floating", name: "Floating", asset_type: "workflow", source_uri: "local://floating", effect: "read_only", trust: "trusted", health: "healthy", dependencies: ["child"] }); const floatingKit = f.service.domainKitSave({ kit_id: "floating-kit", ...base, capability_requirements: [{ asset_id: floating.id, asset_version: floating.version, effect: "read_only" }] }); launch(f, "floating"); assert.throws(() => f.service.domainKitApply({ kit_id: floatingKit.id, launch_id: "launch-floating", values: { path: "out" } }), /pin asset@version/);
    const a = f.service.capabilityAssetSave({ asset_id: "cycle-a", name: "A", asset_type: "tool", source_uri: "local://a", effect: "read_only", trust: "trusted", health: "healthy", dependencies: ["cycle-b@1"] }); f.service.capabilityAssetSave({ asset_id: "cycle-b", name: "B", asset_type: "tool", source_uri: "local://b", effect: "read_only", trust: "trusted", health: "healthy", dependencies: ["cycle-a@1"] }); const cycleKit = f.service.domainKitSave({ kit_id: "cycle-kit", ...base, capability_requirements: [{ asset_id: a.id, asset_version: a.version, effect: "read_only" }] }); launch(f, "cycle"); assert.throws(() => f.service.domainKitApply({ kit_id: cycleKit.id, launch_id: "launch-cycle", values: { path: "out" } }), /dependency cycle/);
    const writer = f.service.capabilityAssetSave({ asset_id: "writer", name: "Writer", asset_type: "tool", source_uri: "local://writer", effect: "external_write", trust: "trusted", health: "healthy" }); const hidden = f.service.capabilityAssetSave({ asset_id: "hidden", name: "Hidden", asset_type: "workflow", source_uri: "local://hidden", effect: "read_only", trust: "trusted", health: "healthy", dependencies: [`${writer.id}@${writer.version}`] }); const hiddenKit = f.service.domainKitSave({ kit_id: "hidden-kit", ...base, capability_requirements: [{ asset_id: hidden.id, asset_version: hidden.version, effect: "read_only" }] }); launch(f, "hidden"); assert.throws(() => f.service.domainKitApply({ kit_id: hiddenKit.id, launch_id: "launch-hidden", values: { path: "out" } }), /transitive capability/);
  } finally { f.store.close(); }
});

test("Domain Kits compose deterministic coverage and media evidence without model guesses", async () => {
  const f = await fixture("domain-evidence"); try { const kit = f.service.domainKitSave({ kit_id: "evidence-kit", name: "Evidence", domain: "mixed", description: "Machine facts", fields: [{ id: "coverage", label: "Coverage", type: "path" }, { id: "probe", label: "Probe", type: "path" }], criteria: [{ id: "coverage_gate", name: "Coverage", method: "program", evaluator: { type: "coverage_report", path_field: "coverage", lines_threshold: 100, branches_threshold: 100 } }, { id: "media_gate", name: "Media", method: "program", evaluator: { type: "media_probe", path_field: "probe", min_duration_seconds: 1, min_width: 1280, min_height: 720 } }] }); launch(f, "evidence"); const applied = f.service.domainKitApply({ kit_id: kit.id, launch_id: "launch-evidence", values: { coverage: "coverage-summary.json", probe: "ffprobe.json" } }); assert.deepEqual((applied.jobs as JsonObject[]).map((job) => job.adapter_id), ["builtin:coverage-report", "builtin:media-probe"]); assert.deepEqual((applied.jobs as JsonObject[]).map((job) => (job.input as JsonObject).relative_path), ["coverage-summary.json", "ffprobe.json"]); assert.throws(() => f.service.domainKitSave({ kit_id: "wrong-method", name: "Wrong", domain: "mixed", description: "Wrong", fields: [{ id: "path", label: "Path", type: "path" }], criteria: [{ id: "bad", name: "Bad", method: "model", evaluator: { type: "media_probe", path_field: "path" } }] }), /built-in evaluators/);
  } finally { f.store.close(); }
});

test("Domain Kit actions pin independently published verified Contracts before authorization", async () => {
  const f = await fixture("contract-actions"); try { const reviewed = { input_schema: { type: "object" }, output_schema: { type: "object" }, effect: "external_write", idempotency: true, compensation: true, credential_handles_required: ["crm-token"] }; f.store.create("contract_candidate", "send-contract", { status: "verified", reviewed_contract: reviewed }); const asset = f.service.capabilityAssetSave({ asset_id: "send-adapter", name: "Send", asset_type: "adapter", source_uri: "craft://contracts/send-contract/1", effect: "external_write", trust: "verified", health: "healthy", contract_id: "send-contract", contract_version: 1 }); f.store.create("contract_publication", "send-publication", { status: "active", candidate_id: "send-contract", candidate_version: 1, asset_id: asset.id, asset_version: asset.version }); const base = { name: "CRM", domain: "sales", description: "Send reviewed outreach", fields: [{ id: "draft", label: "Draft", type: "path" }], criteria: [{ id: "review", name: "Review", method: "human" }] }; const ref = { contract_id: "send-contract", contract_version: 1, asset_id: asset.id, asset_version: asset.version }; const kit = f.service.domainKitSave({ kit_id: "crm-kit", ...base, capability_requirements: [{ asset_id: asset.id, asset_version: asset.version, required_trust: "verified", effect: "external_write" }], action_contracts: [{ id: "send", effect: "external_write", contract_ref: ref }] }); launch(f, "crm"); const applied = f.service.domainKitApply({ kit_id: kit.id, launch_id: "launch-crm", values: { draft: "draft.md" } }); const lock = await f.mcp.handlers.craft_domain_kit_action_lock_get({ application_id: (applied.application as JsonObject).id }) as JsonObject; const action = (lock.actions as JsonObject[])[0]; assert.equal(action.executable, true); assert.deepEqual(action.input_schema, reviewed.input_schema); const prepared = await f.mcp.handlers.craft_domain_kit_action_prepare({ application_id: (applied.application as JsonObject).id, action_id: "send", input_digest: "sha256:input" }) as JsonObject; assert.equal((prepared.request as JsonObject).status, "awaiting_authorization"); assert.equal((prepared.request as JsonObject).execution_authority, false); assert.equal((await f.mcp.handlers.craft_domain_kit_action_prepare({ application_id: (applied.application as JsonObject).id, action_id: "send", input_digest: "sha256:input" }) as JsonObject).idempotent, true); assert.throws(() => f.service.domainKitActionPrepare({ application_id: (applied.application as JsonObject).id, action_id: "send", input_digest: "changed" }), /idempotency conflict/); assert.throws(() => f.service.domainKitActionPrepare({ application_id: (applied.application as JsonObject).id, action_id: "missing", input_digest: "x" }), /unknown/);
    const legacy = f.service.domainKitSave({ kit_id: "legacy-action", ...base, action_contracts: [{ id: "inspect", effect: "read_only" }] }); launch(f, "legacy-action"); const legacyApplied = f.service.domainKitApply({ kit_id: legacy.id, launch_id: "launch-legacy-action", values: { draft: "x" } }); assert.throws(() => f.service.domainKitActionPrepare({ application_id: (legacyApplied.application as JsonObject).id, action_id: "inspect", input_digest: "x" }), /no verified/); f.store.save("domain_kit_application", String((applied.application as JsonObject).id), { ...(applied.application as JsonObject), status: "settled" }); assert.throws(() => f.service.domainKitActionPrepare({ application_id: (applied.application as JsonObject).id, action_id: "send", input_digest: "x" }), /not active/);
    for (const [id, mutate, expected] of [["unverified", { contract_status: "reviewed" }, /not verified/], ["effect", { contract_effect: "read_only" }, /effect mismatch/], ["unpublished", { publication_status: "rolled_back" }, /not actively published/], ["unpinned", { omit_requirement: true }, /not pinned/], ["drift", { asset_contract: "other" }, /drifted/]] as const) { const contractId = `contract-${id}`; const assetId = `asset-${id}`; f.store.create("contract_candidate", contractId, { status: mutate.contract_status ?? "verified", reviewed_contract: { ...reviewed, effect: mutate.contract_effect ?? "external_write" } }); const candidateAsset = f.service.capabilityAssetSave({ asset_id: assetId, name: assetId, asset_type: "adapter", source_uri: `craft://${assetId}`, effect: "external_write", trust: "verified", health: "healthy", contract_id: mutate.asset_contract ?? contractId, contract_version: 1 }); f.store.create("contract_publication", `publication-${id}`, { status: mutate.publication_status ?? "active", candidate_id: contractId, candidate_version: 1, asset_id: assetId, asset_version: 1 }); const badKit = f.service.domainKitSave({ kit_id: `kit-${id}`, ...base, capability_requirements: mutate.omit_requirement ? [] : [{ asset_id: candidateAsset.id, asset_version: candidateAsset.version, required_trust: "verified", effect: "external_write" }], action_contracts: [{ id: "send", effect: "external_write", contract_ref: { contract_id: contractId, contract_version: 1, asset_id: assetId, asset_version: 1 } }] }); launch(f, id); assert.throws(() => f.service.domainKitApply({ kit_id: badKit.id, launch_id: `launch-${id}`, values: { draft: "x" } }), expected); }
  } finally { f.store.close(); }
});

test("a reviewed contract action may be prepared without an approval gate when policy declares it", async () => {
  const f = await fixture("contract-action-ungated"); try { const reviewed = { input_schema: {}, output_schema: {}, effect: "read_only", idempotency: true, compensation: false, credential_handles_required: [] }; f.store.create("contract_candidate", "read-contract", { status: "verified", reviewed_contract: reviewed }); const asset = f.service.capabilityAssetSave({ asset_id: "read-adapter", name: "Read", asset_type: "adapter", source_uri: "craft://read", effect: "read_only", trust: "verified", health: "healthy", contract_id: "read-contract", contract_version: 1 }); f.store.create("contract_publication", "read-publication", { status: "active", candidate_id: "read-contract", candidate_version: 1, asset_id: asset.id, asset_version: asset.version }); const kit = f.service.domainKitSave({ kit_id: "read-kit", name: "Read", domain: "research", description: "Read data", fields: [{ id: "query", label: "Query", type: "text" }], criteria: [{ id: "review", name: "Review", method: "human" }], capability_requirements: [{ asset_id: asset.id, asset_version: asset.version, required_trust: "verified", effect: "read_only" }], action_contracts: [{ id: "read", effect: "read_only", contract_ref: { contract_id: "read-contract", contract_version: 1, asset_id: asset.id, asset_version: asset.version } }] }); launch(f, "read-action"); const applied = f.service.domainKitApply({ kit_id: kit.id, launch_id: "launch-read-action", values: { query: "status" } }); assert.equal((f.service.domainKitActionPrepare({ application_id: (applied.application as JsonObject).id, action_id: "read", input_digest: "sha256:read" }).request as JsonObject).status, "prepared"); } finally { f.store.close(); }
});

test("Domain action validates ephemeral I/O and closes only after exact authorization consumption", async () => {
  const f = await fixture("action-lifecycle"); try { const reviewed = { input_schema: { type: "object", required: ["query"], additionalProperties: false, properties: { query: { type: "string", minLength: 1 } } }, output_schema: { type: "object", required: ["result"], additionalProperties: false, properties: { result: { type: "string" } } }, effect: "read_only", idempotency: true, compensation: false, credential_handles_required: [] }; f.store.create("contract_candidate", "lookup-contract", { status: "verified", reviewed_contract: reviewed }); const asset = f.service.capabilityAssetSave({ asset_id: "lookup-adapter", name: "Lookup", asset_type: "adapter", source_uri: "craft://lookup", effect: "read_only", trust: "verified", health: "healthy", contract_id: "lookup-contract", contract_version: 1 }); f.store.create("contract_publication", "lookup-publication", { status: "active", candidate_id: "lookup-contract", candidate_version: 1, asset_id: asset.id, asset_version: asset.version }); const kit = f.service.domainKitSave({ kit_id: "lookup-kit", name: "Lookup", domain: "research", description: "Lookup", fields: [{ id: "query", label: "Query", type: "text" }], criteria: [{ id: "quality", name: "Quality", method: "human" }], capability_requirements: [{ asset_id: asset.id, asset_version: asset.version, required_trust: "verified", effect: "read_only" }], action_contracts: [{ id: "lookup", effect: "read_only", contract_ref: { contract_id: "lookup-contract", contract_version: 1, asset_id: asset.id, asset_version: asset.version } }] }); launch(f, "lookup"); const applied = f.service.domainKitApply({ kit_id: kit.id, launch_id: "launch-lookup", values: { query: "x" } }); const policy = f.service.autonomyPolicySave({ policy_id: "lookup-policy", task_id: "task-lookup", name: "Lookup", rules: { read: { level: "automatic" } } }).policy as JsonObject; const args = { application_id: (applied.application as JsonObject).id, action_id: "lookup", input: { query: "private-query-value" }, target: "catalog", policy_id: policy.id, policy_version: policy.version, requested_by: "tester" }; const prepared = await f.mcp.handlers.craft_domain_kit_action_prepare(args) as JsonObject; const request = prepared.request as JsonObject; const authorization = prepared.authorization as JsonObject; assert.equal(request.raw_input_stored, false); assert.equal(JSON.stringify(request).includes("private-query-value"), false); assert.equal(authorization.status, "authorized"); assert.equal((await f.mcp.handlers.craft_domain_kit_action_prepare(args) as JsonObject).idempotent, true); assert.throws(() => f.service.domainKitActionPrepare({ ...args, request_id: "bad-input", input: {} }), /required/); assert.throws(() => f.service.domainKitActionPrepare({ ...args, request_id: "missing-input", input: undefined }), /required for Schema/);
    f.service.autonomyConsume({ request_id: authorization.id, task_id: "task-lookup", action: "read", target: "catalog", request_digest: request.request_digest, idempotency_key: "domain-action:lookup" }); const evidence = f.service.evidenceRecord({ source_type: "program", confidence: "confirmed", claim: "Lookup returned a structured result" }); assert.throws(() => f.service.domainKitActionReport({ request_id: request.id, outcome: "succeeded", output: {}, evidence_ids: [evidence.id] }), /required/); assert.throws(() => f.service.domainKitActionReport({ request_id: request.id, outcome: "maybe", output: {}, evidence_ids: [evidence.id] }), /outcome/); assert.throws(() => f.service.domainKitActionReport({ request_id: request.id, outcome: "succeeded", output: { result: "ok" }, evidence_ids: [] }), /requires evidence/); const reported = await f.mcp.handlers.craft_domain_kit_action_report({ request_id: request.id, outcome: "succeeded", output: { result: "ok" }, evidence_ids: [evidence.id] }) as JsonObject; assert.equal((reported.request as JsonObject).status, "completed"); assert.equal((reported.request as JsonObject).raw_output_stored, false); assert.equal((f.service.domainKitActionReport({ request_id: request.id, outcome: "succeeded", output: { result: "ok" }, evidence_ids: [evidence.id] })).idempotent, true); assert.throws(() => f.service.domainKitActionReport({ request_id: request.id, outcome: "succeeded", output: { result: "changed" }, evidence_ids: [evidence.id] }), /idempotency conflict/);
    const pendingPolicy = f.service.autonomyPolicySave({ policy_id: "pending-policy", task_id: "task-lookup", name: "Pending", rules: { read: { level: "human_approval" } } }).policy as JsonObject; const pending = f.service.domainKitActionPrepare({ ...args, request_id: "pending-action", input: { query: "other" }, policy_id: pendingPolicy.id, policy_version: pendingPolicy.version }).request as JsonObject; assert.throws(() => f.service.domainKitActionReport({ request_id: pending.id, outcome: "failed", evidence_ids: [evidence.id] }), /not been consumed/);
  } finally { f.store.close(); }
});

test("Domain actions derive every effect class and close failed attempts without persisting payloads", async () => {
  const f = await fixture("action-effect-classes"); try {
    const reviewed = { input_schema: { type: "object" }, output_schema: { type: "object" }, effect: "read_only", idempotency: true, compensation: false, credential_handles_required: [] };
    f.store.create("contract_candidate", "effect-contract", { status: "verified", reviewed_contract: reviewed });
    const asset = f.service.capabilityAssetSave({ asset_id: "effect-adapter", name: "Effect", asset_type: "adapter", source_uri: "craft://effect", effect: "read_only", trust: "verified", health: "healthy", contract_id: "effect-contract", contract_version: 1 });
    f.store.create("contract_publication", "effect-publication", { status: "active", candidate_id: "effect-contract", candidate_version: 1, asset_id: asset.id, asset_version: asset.version });
    const ref = { contract_id: "effect-contract", contract_version: 1, asset_id: asset.id, asset_version: asset.version };
    const kit = f.service.domainKitSave({ kit_id: "effect-kit", name: "Effects", domain: "operations", description: "Effect mapping", fields: [{ id: "query", label: "Query", type: "text" }], criteria: [{ id: "review", name: "Review", method: "human" }], capability_requirements: [{ asset_id: asset.id, asset_version: asset.version, required_trust: "verified", effect: "read_only" }], action_contracts: [{ id: "read", effect: "read_only", contract_ref: ref }] });
    launch(f, "effect"); const applied = f.service.domainKitApply({ kit_id: kit.id, launch_id: "launch-effect", values: { query: "x" } }); const application = applied.application as JsonObject; const lock = f.service.domainKitActionLockGet({ application_id: application.id }); const read = (lock.actions as JsonObject[])[0];
    f.store.save("domain_kit_action_lock", String(lock.id), { ...lock, actions: [read, { ...read, action_id: "local", effect: "local_write" }, { ...read, action_id: "external", effect: "external_write" }] });
    const policy = f.service.autonomyPolicySave({ policy_id: "effect-policy", task_id: "task-effect", name: "Effects", rules: { sandbox_write: { level: "automatic" }, external_write: { level: "automatic" } } }).policy as JsonObject;
    const common = { application_id: application.id, input: {}, target: "target", policy_id: policy.id, policy_version: policy.version };
    const local = f.service.domainKitActionPrepare({ ...common, action_id: "local", request_id: "local-effect" }); const localRequest = local.request as JsonObject; const localAuthorization = local.authorization as JsonObject; assert.equal(localAuthorization.action, "sandbox_write"); assert.equal(localAuthorization.requested_by, "domain_kit");
    f.service.autonomyConsume({ request_id: localAuthorization.id, task_id: "task-effect", action: "sandbox_write", target: "target", request_digest: localRequest.request_digest, idempotency_key: "domain-action:local" }); const evidence = f.service.evidenceRecord({ source_type: "program", confidence: "confirmed", claim: "Adapter failed safely" }); const failed = f.service.domainKitActionReport({ request_id: localRequest.id, outcome: "failed", evidence_ids: [evidence.id] }); assert.equal((failed.request as JsonObject).status, "failed"); assert.equal((f.service.domainKitActionReport({ request_id: localRequest.id, outcome: "failed", evidence_ids: [evidence.id] })).idempotent, true);
    const external = f.service.domainKitActionPrepare({ ...common, action_id: "external", request_id: "external-effect" }); assert.equal((external.authorization as JsonObject).action, "external_write");
  } finally { f.store.close(); }
});
