import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { McpServer } from "../src/mcp.ts";
import { craftPaths } from "../src/paths.ts";
import { CraftService, VERSION } from "../src/service.ts";
import { CraftStore, type JsonObject } from "../src/store.ts";

test("safety preflight pins a verified boundary and Host resource contract before approval", async () => {
  const root = await mkdtemp(join(tmpdir(), "craft-safety-")); const store = await new CraftStore(craftPaths(root)).open(); const service = new CraftService(store);
  try {
    const task = service.taskOpen({ title: "Safe edit", goal: "Use proved limits" }).task as JsonObject; const evidence = service.evidenceRecord({ source_type: "program", confidence: "confirmed", claim: "Boundary probe passed" }) as JsonObject;
    const capabilities = { filesystem: "workspace_overlay", network: "denied", features: ["cancel", "process_isolation", "snapshot"], limits: {} };
    service.sandboxProfileSave({ profile_id: "local", name: "Local boundary", backend: "local_process", adapter_id: "local-host", capabilities }); service.sandboxProfileVerify({ profile_id: "local", profile_version: 1, verifier: "probe", observed_capabilities: capabilities, evidence_ids: [evidence.id] });
    const input = { preflight_id: "safe", task_id: task.id, host: "claude-code", workspace: root, sandbox: "workspace-write", profile_id: "local", profile_version: 2, timeout_ms: 30_000, output_limit: 8_192, max_turns: 3, max_budget_usd: 1 };
    const first = service.executionSafetyPreflight(input); const preflight = first.preflight as JsonObject; assert.equal(preflight.os_sandbox_guaranteed, false); assert.equal((service.executionSafetyPreflight(input) as JsonObject).idempotent, true); assert.equal((service.executionSafetyGet({ preflight_id: preflight.id }).contract as JsonObject).timeout_ms, 30_000); assert.throws(() => service.executionSafetyPreflight({ ...input, output_limit: 100 }), /output_limit/); assert.throws(() => service.executionSafetyPreflight({ ...input, host: "other" }), /host/); assert.throws(() => service.executionSafetyPreflight({ ...input, profile_version: 1, preflight_id: "old" }), /verified/);
    const prepared = service.safetyWorkLaunchPrepare({ ...input, launch_id: "safe-launch", prompt: "Edit the draft" }); const launch = prepared.launch as JsonObject; assert.equal((launch.safety_preflight as JsonObject).preflight_id, preflight.id); assert.equal((prepared.dispatch as JsonObject).timeout_ms, 30_000); assert.equal((service.safetyWorkLaunchPrepare({ ...input, launch_id: "safe-launch", prompt: "Edit the draft" }) as JsonObject).idempotent, true);
    service.platformExecutionProfileSave({ profile_id: "platform-write", platform: process.platform, isolation: "verified", network: "deny", verified_by: "independent-probe" }); service.platformExecutionProfileSave({ profile_id: "platform-write-other", platform: process.platform, isolation: "verified", network: "deny", verified_by: "independent-probe" }); const platformInput = { ...input, preflight_id: "platform-safe", launch_id: "platform-safe-launch", prompt: "Edit with platform receipt", platform: process.platform, platform_profile_id: "platform-write", platform_effect: "local_write" }; const platformPrepared = service.safetyWorkLaunchPrepare(platformInput); const platformLaunch = platformPrepared.launch as JsonObject; assert.equal(((platformLaunch.platform_execution_preflight as JsonObject).profile_id), "platform-write"); assert.equal(service.safetyWorkLaunchPrepare(platformInput).idempotent, true); assert.equal(service.safetyWorkLaunchDecide({ launch_id: platformLaunch.id, actor: "human", approved: false }).started, false); assert.throws(() => service.safetyWorkLaunchPrepare({ ...platformInput, platform_profile_id: "platform-write-other" }), /another platform/); assert.throws(() => service.safetyWorkLaunchPrepare({ ...input, preflight_id: "platform-incomplete", launch_id: "platform-incomplete-launch", prompt: "Edit", platform: process.platform }), /requires/); assert.throws(() => service.safetyWorkLaunchPrepare({ ...input, preflight_id: "platform-bad", launch_id: "platform-bad-launch", prompt: "Edit", platform: process.platform, platform_profile_id: "platform-write", platform_effect: "read_only" }), /effect/);
    assert.throws(() => service.safetyWorkLaunchDecide({ launch_id: launch.id, actor: "human", approved: true, prompt: "changed" }), /digest/); const denied = service.safetyWorkLaunchDecide({ launch_id: launch.id, actor: "human", approved: false }); assert.equal(denied.started, false); assert.throws(() => service.safetyWorkLaunchDecide({ launch_id: launch.id, actor: "human", approved: false }), /awaiting/); const dispatchRecord = store.get("claude_dispatch", String(launch.dispatch_id)); const { id: _id, version: _version, created_at: _created, updated_at: _updated, ...dispatchPayload } = dispatchRecord; store.save("claude_dispatch", String(dispatchRecord.id), { ...dispatchPayload, timeout_ms: 31_000 }); assert.throws(() => service.safetyWorkLaunchDecide({ launch_id: launch.id, actor: "human", approved: false }), /resource contract/);
    const otherTask = service.taskOpen({ title: "Other", goal: "Other" }).task as JsonObject; const other = service.workLaunchPrepare({ launch_id: "other", task_id: otherTask.id, host: "claude-code", workspace: root, sandbox: "workspace-write", prompt: "Other" }).launch as JsonObject; assert.throws(() => service.executionSafety.bind({ preflight_id: preflight.id, launch_id: other.id }), /does not match/);
    assert.equal((service.executionSafety.bind({ preflight_id: preflight.id, launch_id: launch.id }) as JsonObject).idempotent, true); assert.throws(() => service.executionSafetyPreflight({ ...input, timeout_ms: 31_000 }), /idempotency/); const second = service.executionSafetyPreflight({ ...input, preflight_id: "second" }).preflight as JsonObject; assert.throws(() => service.executionSafety.bind({ preflight_id: second.id, launch_id: launch.id }), /another safety preflight/); const noBudgetInput = { preflight_id: "no-budget", task_id: task.id, host: "claude-code", workspace: root, sandbox: "workspace-write", profile_id: "local", profile_version: 2, timeout_ms: 30_000, output_limit: 8_192, max_turns: 3 }; assert.equal(((service.executionSafetyPreflight(noBudgetInput).preflight as JsonObject).resources as JsonObject).max_budget_usd, null); const noBudgetLaunch = service.safetyWorkLaunchPrepare({ ...noBudgetInput, launch_id: "no-budget-launch", prompt: "No budget" }).launch as JsonObject; assert.equal(service.safetyWorkLaunchDecide({ launch_id: noBudgetLaunch.id, actor: "human", approved: false }).started, false);
    assert.throws(() => service.executionSafetyPreflight({ ...input, task_id: " " }), /task_id/); assert.throws(() => service.executionSafetyPreflight({ ...input, sandbox: "unsafe" }), /sandbox/); assert.throws(() => service.executionSafetyPreflight({ ...input, max_budget_usd: 0 }), /budget/); assert.throws(() => service.executionSafetyGet({ preflight_id: "missing" }), /Unknown/); assert.equal((service.executionSafetyGet({ preflight_id: preflight.id, version: 1 }).preflight as JsonObject).id, preflight.id);
    service.sandboxProfileSave({ profile_id: "read", name: "Read boundary", backend: "local_process", adapter_id: "read-host", capabilities: { filesystem: "read_only", network: "denied", features: ["cancel", "process_isolation"], limits: {} } }); service.sandboxProfileVerify({ profile_id: "read", profile_version: 1, verifier: "probe", observed_capabilities: { filesystem: "read_only", network: "denied", features: ["cancel", "process_isolation"], limits: {} }, evidence_ids: [evidence.id] }); const read = service.executionSafetyPreflight({ preflight_id: "read", task_id: task.id, host: "codex-cli", workspace: root, sandbox: "read-only", profile_id: "read", profile_version: 2, timeout_ms: 30_000, output_limit: 8_192 }).preflight as JsonObject; assert.equal((read.resources as JsonObject).max_turns, null); const codex = service.safetyWorkLaunchPrepare({ preflight_id: "codex", task_id: task.id, host: "codex-cli", workspace: root, sandbox: "workspace-write", profile_id: "local", profile_version: 2, timeout_ms: 30_000, output_limit: 8_192, launch_id: "codex-safe", prompt: "Edit" }).launch as JsonObject; assert.equal(service.safetyWorkLaunchDecide({ launch_id: codex.id, actor: "human", approved: false }).started, false);
    assert.match(String((service.executionSafetyPreflight({ task_id: task.id, host: "codex-cli", workspace: root, sandbox: "read-only", profile_id: "read", profile_version: 2, timeout_ms: 30_000, output_limit: 8_192 }).preflight as JsonObject).id), /^execution_safety_preflight_/); assert.throws(() => service.executionSafetyPreflight({ preflight_id: "incompatible", task_id: task.id, host: "codex-cli", workspace: root, sandbox: "workspace-write", profile_id: "read", profile_version: 2, timeout_ms: 30_000, output_limit: 8_192 }), /requirements are not satisfied/);
    store.create("execution_safety_preflight", "failed", { task_id: task.id, profile_id: "local", profile_version: 2, profile_digest: "x", status: "failed" }); assert.throws(() => service.executionSafety.validate({ preflight_id: "failed" }), /not passed/); store.create("execution_safety_preflight", "drift", { task_id: task.id, profile_id: "local", profile_version: 2, profile_digest: "wrong", status: "passed" }); assert.throws(() => service.executionSafety.validate({ preflight_id: "drift" }), /changed/);
    const mcp = new McpServer(service, "full"); for (const [name, arguments_] of [["craft_execution_safety_get", { preflight_id: preflight.id }], ["craft_execution_safety_preflight", input], ["craft_safety_work_launch_prepare", { ...input, preflight_id: "mcp-safe", launch_id: "mcp-launch", prompt: "MCP edit" }], ["craft_safety_work_launch_decide", { launch_id: "mcp-launch", actor: "human", approved: false }]] as [string, JsonObject][]) assert.equal(((await mcp.handle({ id: name, method: "tools/call", params: { name, arguments: arguments_ } }))?.result as JsonObject).isError, false);
    assert.equal(VERSION, "0.11.59");
  } finally { store.close(); await rm(root, { recursive: true, force: true }); }
});
