import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { McpServer } from "../src/mcp.ts";
import { craftPaths } from "../src/paths.ts";
import { CraftService, VERSION } from "../src/service.ts";
import { CraftStore, type JsonObject } from "../src/store.ts";

test("guided work keeps goal, material references, decisions, and Host launch distinct", async () => {
  const root = await mkdtemp(join(tmpdir(), "craft-guided-work-")); const store = await new CraftStore(craftPaths(root)).open(); const service = new CraftService(store);
  try {
    const input = { brief_id: "brief", title: "Prepare lesson", goal: "Produce a reviewed lesson", materials: [{ kind: "file", label: "Outline", reference: "outline.md" }], decisions: [{ id: "audience", question: "Who is this for?" }, { id: "format", question: "Which format?", required: false }] };
    const created = service.guidedWorkCreate(input); const brief = created.brief as JsonObject; assert.equal(brief.status, "awaiting_decisions"); assert.equal((service.guidedWorkCreate(input) as JsonObject).idempotent, true); assert.equal((service.guidedWork.create({ ...input, task_id: brief.task_id }) as JsonObject).idempotent, true); assert.throws(() => service.guidedWork.create({ ...input, task_id: brief.task_id, materials: [] }), /idempotency/); assert.throws(() => service.guidedWorkCreate({ ...input, goal: "Other" }), /idempotency/);
    assert.throws(() => service.guidedWorkLaunchPrepare({ brief_id: brief.id, host: "codex-cli", workspace: root, prompt: "work", sandbox: "workspace-write" }), /decisions/); assert.throws(() => service.guidedWorkDecide({ brief_id: brief.id, decision_id: "missing", answer: "x", actor: "user" }), /unknown/);
    const decided = service.guidedWorkDecide({ brief_id: brief.id, decision_id: "audience", answer: "Beginners", actor: "user" }).brief as JsonObject; assert.equal(decided.status, "ready_to_launch"); assert.equal(JSON.stringify(decided).includes("Beginners"), false); assert.throws(() => service.guidedWorkDecide({ brief_id: brief.id, decision_id: "audience", answer: "Again", actor: "user" }), /not awaiting|already answered/);
    const launched = service.guidedWorkLaunchPrepare({ brief_id: brief.id, launch_id: "guided-launch", host: "codex-cli", workspace: root, prompt: "Create the lesson", sandbox: "workspace-write" }); assert.equal((launched.brief as JsonObject).status, "launched"); assert.equal((launched.launch as JsonObject).status, "awaiting_approval"); assert.equal((service.guidedWorkGet({ brief_id: brief.id, version: 3 }).launch as JsonObject).id, "guided-launch");
    const noDecision = service.guidedWorkCreate({ brief_id: "ready", title: "Read", goal: "Review", materials: [] }).brief as JsonObject; assert.equal(noDecision.status, "ready_to_launch"); store.create("work_launch", "wrong-task", { task_id: "other", status: "prepared" }); assert.throws(() => service.guidedWork.bindLaunch({ brief_id: noDecision.id, launch_id: "wrong-task" }), /does not belong/); store.create("work_launch", "right-task", { task_id: noDecision.task_id, status: "prepared" }); assert.equal((service.guidedWork.bindLaunch({ brief_id: noDecision.id, launch_id: "right-task" }) as JsonObject).idempotent, false); assert.equal((service.guidedWork.bindLaunch({ brief_id: noDecision.id, launch_id: "right-task" }) as JsonObject).idempotent, true); store.create("work_launch", "other-launch", { task_id: noDecision.task_id, status: "prepared" }); assert.throws(() => service.guidedWork.bindLaunch({ brief_id: noDecision.id, launch_id: "other-launch" }), /another launch/);
    const generated = service.guidedWorkCreate({ title: "Generated", goal: "No identifier or optional arrays" }).brief as JsonObject; assert.match(String(generated.id), /^guided_work_/); assert.equal((service.guidedWorkGet({ brief_id: generated.id }).launch), null);
    const multi = service.guidedWorkCreate({ brief_id: "multi", title: "Multi", goal: "Answer both", decisions: [{ id: "first", question: "First?" }, { id: "second", question: "Second?" }] }).brief as JsonObject; store.create("work_launch", "multi-launch", { task_id: multi.task_id, status: "prepared" }); assert.throws(() => service.guidedWork.bindLaunch({ brief_id: multi.id, launch_id: "multi-launch" }), /decisions/); service.guidedWorkDecide({ brief_id: multi.id, decision_id: "first", answer: "one", actor: "user" }); assert.throws(() => service.guidedWorkDecide({ brief_id: multi.id, decision_id: "first", answer: "again", actor: "user" }), /already answered/); service.guidedWorkDecide({ brief_id: multi.id, decision_id: "second", answer: "two", actor: "user" });
    assert.throws(() => service.guidedWork.create({ task_id: "", materials: [] }), /task_id/); assert.throws(() => service.guidedWork.create({ task_id: String(generated.task_id), materials: "bad" }), /array/); assert.throws(() => service.guidedWork.create({ task_id: String(generated.task_id), materials: [null] }), /objects/); assert.throws(() => service.guidedWorkDecide({ brief_id: generated.id, decision_id: "x", answer: "api_key=x", actor: "user" }), /not awaiting|sensitive/);
    for (const bad of [{ ...input, brief_id: "bad-kind", materials: [{ kind: "unknown", label: "x", reference: "x" }] }, { ...input, brief_id: "bad-required", decisions: [{ id: "x", question: "x", required: "yes" }] }, { ...input, brief_id: "duplicate", decisions: [{ id: "x", question: "x" }, { id: "x", question: "y" }] }, { ...input, brief_id: "secret", materials: [{ kind: "note", label: "api_key=x", reference: "x" }] }]) assert.throws(() => service.guidedWorkCreate(bad), /unsupported|sensitive/);
    const mcp = new McpServer(service, "full"); for (const [name, arguments_] of [["craft_guided_work_create", { brief_id: "mcp", title: "MCP", goal: "Goal" }], ["craft_guided_work_get", { brief_id: "mcp" }], ["craft_guided_work_create", { brief_id: "mcp-decision", title: "MCP decision", goal: "Goal", decisions: [{ id: "go", question: "Proceed?" }] }], ["craft_guided_work_decide", { brief_id: "mcp-decision", decision_id: "go", answer: "yes", actor: "user" }], ["craft_guided_work_launch_prepare", { brief_id: "mcp-decision", launch_id: "mcp-launch", host: "codex-cli", workspace: root, prompt: "Run", sandbox: "workspace-write" }]] as [string, JsonObject][]) assert.equal(((await mcp.handle({ id: name, method: "tools/call", params: { name, arguments: arguments_ } }))?.result as JsonObject).isError, false);
    assert.equal(VERSION, "0.11.46");
  } finally { store.close(); await rm(root, { recursive: true, force: true }); }
});
