import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { McpServer } from "../src/mcp.ts";
import { craftPaths } from "../src/paths.ts";
import { CraftService } from "../src/service.ts";
import { CraftStore, type JsonObject } from "../src/store.ts";

test("platform execution permits portable reads and fails closed for writes without a verified boundary", async () => {
  const root = await mkdtemp(join(tmpdir(), "craft-platform-")); const store = await new CraftStore(craftPaths(root)).open(); const service = new CraftService(store);
  try {
    assert.equal(service.platformExecutionPreflight({ platform: "win32", effect: "read_only" }).mode, "portable_read"); assert.equal(service.platformExecutionPreflight({ platform: "darwin", effect: "read_only", profile_id: "missing" }).receipt instanceof Object, true);
    assert.throws(() => service.platformExecutionPreflight({ platform: "win32", effect: "local_write" }), /verified/);
    const none = service.platformExecutionProfileSave({ profile_id: "none", platform: "win32", isolation: "none", network: "deny" }).profile as JsonObject; assert.equal(none.verified_by, null); assert.throws(() => service.platformExecutionPreflight({ platform: "win32", effect: "local_write", profile_id: "none" }), /verified/);
    const verified = service.platformExecutionProfileSave({ profile_id: "verified", platform: "win32", isolation: "verified", network: "deny", verified_by: "probe" }).profile as JsonObject; assert.equal(service.platformExecutionProfileSave({ profile_id: "verified", platform: "win32", isolation: "verified", network: "deny", verified_by: "probe" }).idempotent, true);
    const preflight = service.platformExecutionPreflight({ platform: "win32", effect: "local_write", profile_id: verified.id, preflight_id: "fixed" }).preflight as JsonObject; assert.equal(preflight.allowed, true); assert.equal(service.platformExecutionPreflight({ platform: "win32", effect: "local_write", profile_id: verified.id, preflight_id: "fixed" }).idempotent, true); assert.throws(() => service.platformExecutionPreflight({ platform: "win32", effect: "external_write", profile_id: verified.id, preflight_id: "fixed" }), /conflict/);
    const mcp = new McpServer(service, "full"); assert.equal((((await mcp.handlers.craft_platform_execution_preflight({ platform: "win32", effect: "external_write", profile_id: verified.id })).preflight as JsonObject).allowed), true); assert.equal(((await mcp.handlers.craft_platform_execution_profile_save({ profile_id: "mcp-profile", platform: "darwin", isolation: "verified", network: "deny", verified_by: "probe" })).profile as JsonObject).id, "mcp-profile");
    const probe = service.platformExecutionProbe({ probe_id: "local" }).probe as JsonObject; assert.equal(probe.platform, process.platform); assert.equal(probe.verified, false); assert.equal(service.platformExecutionProbe({ probe_id: "local" }).idempotent, true); assert.match(String((service.platformExecutionProbe({}).probe as JsonObject).id), /^platform_execution_probe_/); assert.equal((service.platformExecutionProbe({ platform: process.platform, probe_id: "explicit" }).probe as JsonObject).platform, process.platform); assert.equal((service.platformExecutionProbeGet({ probe_id: "local" }).probe as JsonObject).id, "local"); assert.equal(((await mcp.handlers.craft_platform_execution_probe({ probe_id: "mcp-probe" })).probe as JsonObject).verified, false); assert.equal(((await mcp.handlers.craft_platform_execution_probe_get({ probe_id: "mcp-probe" })).probe as JsonObject).id, "mcp-probe"); const inactive = service.platformExecutionProfileSave({ profile_id: "inactive", platform: process.platform, isolation: "verified", network: "deny", verified_by: "probe", active: false }).profile as JsonObject; assert.throws(() => service.platformExecutionPreflight({ platform: process.platform, effect: "local_write", profile_id: inactive.id }), /verified/); assert.equal(service.platformExecution.validate({ preflight_id: "fixed" }).valid, true); store.create("platform_execution_preflight", "invalid", { profile_id: inactive.id, profile_version: inactive.version, platform: process.platform, effect: "local_write", allowed: true }); assert.throws(() => service.platformExecution.validate({ preflight_id: "invalid", version: 1 }), /valid/); const corrupt = store.get("platform_execution_probe", "local"); const { id: _id, version: _version, created_at: _created, updated_at: _updated, ...corruptPayload } = corrupt; store.save("platform_execution_probe", "local", { ...corruptPayload, probe_digest: "tampered" }); assert.throws(() => service.platformExecutionProbe({ probe_id: "local" }), /conflict/); const otherPlatform = process.platform === "win32" ? "linux" : "win32"; assert.throws(() => service.platformExecutionProbe({ platform: otherPlatform, probe_id: "wrong-platform" }), /current/);
    assert.throws(() => service.platformExecutionProfileSave({ profile_id: "bad", platform: "x", isolation: "bad", network: "deny" }), /unsupported/); assert.throws(() => service.platformExecutionProfileSave({ profile_id: "unverified", platform: "x", isolation: "verified", network: "deny" }), /verified_by/); assert.throws(() => service.platformExecutionPreflight({ platform: "darwin", effect: "local_write", profile_id: verified.id }), /verified/); assert.throws(() => service.platformExecutionPreflight({ platform: "win32", effect: "local_write", profile_id: "missing" }), /Unknown/); assert.throws(() => service.platformExecutionProfileSave({ profile_id: "verified", platform: "win32", isolation: "verified", network: "allow", verified_by: "probe" }), /conflict/); assert.throws(() => service.platformExecutionPreflight({ platform: " ", effect: "read_only" }), /platform/);
  } finally { store.close(); await rm(root, { recursive: true, force: true }); }
});

test("platform conformance binds verifier evidence to a profile without treating a health probe as proof", async () => {
  const root = await mkdtemp(join(tmpdir(), "craft-platform-conformance-")); const store = await new CraftStore(craftPaths(root)).open(); const service = new CraftService(store);
  try {
    const checks = { network_denied: true, workspace_contained: true, credentials_absent: true, cancel_cleanup: true, resource_limits: true };
    const conformance = service.platformExecutionConformanceRecord({ conformance_id: "darwin", platform: "darwin", verifier: "conformance-suite", checks }).conformance as JsonObject;
    assert.equal(service.platformExecutionConformanceRecord({ conformance_id: "darwin", platform: "darwin", verifier: "conformance-suite", checks }).idempotent, true);
    assert.equal(((await new McpServer(service, "full").handlers.craft_platform_execution_conformance_record({ conformance_id: "mcp", platform: "linux", verifier: "conformance-suite", checks })).conformance as JsonObject).id, "mcp");
    assert.throws(() => service.platformExecutionConformanceRecord({ conformance_id: "darwin", platform: "darwin", verifier: "other-suite", checks }), /conflict/);
    const implicit = service.platformExecutionConformanceRecord({ platform: "win32", verifier: "conformance-suite", checks }).conformance as JsonObject;
    assert.equal((service.platformExecutionProfileSave({ profile_id: "implicit", platform: "win32", isolation: "verified", network: "deny", verified_by: "conformance-suite", conformance_id: implicit.id }).profile as JsonObject).conformance instanceof Object, true);
    const profile = service.platformExecutionProfileSave({ profile_id: "bound", platform: "darwin", isolation: "verified", network: "deny", verified_by: "conformance-suite", conformance_id: conformance.id, conformance_version: conformance.version }).profile as JsonObject;
    const preflight = service.platformExecutionPreflight({ platform: "darwin", effect: "local_write", profile_id: profile.id }).preflight as JsonObject; assert.equal(service.platformExecution.validate({ preflight_id: preflight.id }).valid, true);
    assert.throws(() => service.platformExecutionConformanceRecord({ platform: "darwin", verifier: "bad", checks: { ...checks, network_denied: false } }), /every/);
    assert.throws(() => service.platformExecutionConformanceRecord({ platform: "darwin", verifier: "bad", checks: [] }), /object/);
    assert.throws(() => service.platformExecutionProfileSave({ profile_id: "wrong", platform: "win32", isolation: "verified", network: "deny", verified_by: "x", conformance_id: conformance.id }), /platform/);
    const invalid = store.create("platform_execution_conformance", "invalid", { platform: "darwin", status: "invalid" }); const invalidProfile = store.create("platform_execution_profile", "invalid-profile", { platform: "darwin", active: true, isolation: "verified", network: "deny", conformance: { id: invalid.id, version: invalid.version } }); store.create("platform_execution_preflight", "invalid-preflight", { profile_id: invalidProfile.id, profile_version: invalidProfile.version, platform: "darwin", effect: "local_write", allowed: true }); assert.throws(() => service.platformExecution.validate({ preflight_id: "invalid-preflight" }), /no longer valid/);
  } finally { store.close(); await rm(root, { recursive: true, force: true }); }
});
