import { Catalog } from "./catalog.ts";
import { CraftStore, type JsonObject } from "./store.ts";
import type { EmbeddingProvider } from "./semantic.ts";
import { LocalIsolatedAdapter } from "./isolated.ts";
import { WorkspaceState } from "./workspace.ts";
import { TransactionCoordinator } from "./transaction.ts";
import { TrajectoryCompiler } from "./trajectory.ts";
import { VerifiedScriptRunner } from "./script-run.ts";
import { WorkbenchKernel } from "./workbench.ts";
import { ChangeSetKernel } from "./changeset.ts";
import { ControlPlaneKernel } from "./control-plane.ts";
import { SecurityBrokerKernel } from "./security.ts";
import { DataOnlyParserAdapter } from "./untrusted-parser.ts";
import { ParserProcessAdapter } from "./parser-process.ts";
import { SandboxKernel } from "./sandbox.ts";
import { DockerSandboxAdapter } from "./docker-sandbox.ts";
import { TrustedEgressBroker } from "./egress.ts";
import { ExternalEffectKernel } from "./effects.ts";
import { RecoveryQueueKernel } from "./recovery.ts";
import { TriggerKernel } from "./trigger.ts";
import { SpeculativeKernel } from "./speculative.ts";
import { LineageKernel } from "./lineage.ts";
import { HydrationKernel } from "./hydration.ts";
import { AutonomyKernel } from "./autonomy.ts";
import { ContractInferenceKernel } from "./contracts.ts";
import { CapabilityCanaryKernel } from "./capability-canary.ts";
import { CapabilityFederationKernel } from "./federation.ts";
import { HubSyncKernel } from "./hub-sync.ts";
import { MaterializationKernel } from "./materialization.ts";
import { CapabilityCertificationKernel } from "./certification.ts";
import { SupplyChainKernel } from "./supply-chain.ts";
import { AttentionKernel } from "./attention.ts";
import { HomeKernel } from "./home.ts";
import { CodexHostKernel } from "./codex-driver.ts";
import { ClaudeHostKernel } from "./claude-driver.ts";
import { GenericCliHostKernel } from "./generic-driver.ts";
import { HostRunKernel } from "./host-run.ts";
import { type HostProfile, mergeHostProfiles } from "./host-registry.ts";
import { DEFAULT_INTERNAL_TOOLS, InternalHostDriver } from "./internal-host-driver.ts";
import { MetricsKernel } from "./metrics.ts";
import { PROVIDER_CATALOG, type ModelProviderSpec, type ModelTransport } from "./model-gateway.ts";
import type { HostDriver } from "./host-driver.ts";
import { KnowledgeBoundLaunchKernel } from "./knowledge-bound-launch.ts";
import { KnowledgeWorkbenchKernel } from "./knowledge-workbench.ts";
import { WikiCandidateGovernanceKernel } from "./wiki-candidate-governance.ts";
import { GuidedWorkKernel } from "./guided-work.ts";
import { ExecutionSafetyKernel } from "./execution-safety.ts";
import { LocalCandidateImportKernel } from "./local-candidate-import.ts";
import { A2ADiscoveryKernel } from "./a2a-discovery.ts";
import { WorkDeliveryKernel } from "./work-delivery.ts";
import { DeliveryEvaluationKernel } from "./delivery-evaluation.ts";
import { PlatformExecutionKernel } from "./platform-execution.ts";
import { DeliveryLoopKernel } from "./delivery-loop.ts";
import { TaskControlKernel } from "./task-control.ts";
import { TaskRunKernel } from "./task-run.ts";
import { TaskBenchmarkKernel } from "./task-benchmark.ts";
import { StateWorkspaceKernel } from "./state-workspace.ts";
import { VerifiedWorkLoopKernel } from "./verified-work-loop.ts";
import { EvalCampaignKernel } from "./eval-campaign.ts";
import { ProjectKnowledgeKernel } from "./project-knowledge.ts";
import { CapabilityConnectorKernel } from "./capability-connector.ts";
import { CapabilityAccessKernel } from "./capability-access.ts";
import { HostActivationManifestKernel } from "./host-activation-manifest.ts";
import { ExecutionFabricKernel } from "./execution-fabric.ts";
import { HostBridgeKernel } from "./host-bridge.ts";
import { ManagedWriteKernel } from "./managed-write.ts";
import { EvalCampaignReportKernel } from "./eval-campaign-report.ts";
import { AdaptiveHarnessKernel } from "./adaptive-harness.ts";
import { ManagedRunKernel } from "./managed-run.ts";
import { CampaignRunnerKernel } from "./campaign-runner.ts";
import { AutonomyLadderKernel } from "./autonomy-ladder.ts";
import { WorkspaceObserverKernel } from "./workspace-observer.ts";
import { WorkCoordinatorKernel } from "./work-coordinator.ts";
import { AgentEvalLabKernel } from "./agent-eval-lab.ts";
import { EvaluationOperationsKernel } from "./evaluation-operations.ts";
import { EnterpriseAccessKernel } from "./enterprise-access.ts";
import { A2ADelegationKernel } from "./a2a-delegation.ts";
import { AutonomousRuntimeKernel } from "./autonomous-runtime.ts";
import { CapabilityLifecycleKernel } from "./capability-lifecycle.ts";
import { MemoryConsolidationKernel } from "./memory-consolidation.ts";
import { RemoteInteropKernel } from "./remote-interop.ts";
import { PlatformOperationsKernel } from "./platform-operations.ts";
import { UsageKernel } from "./usage.ts";
import { IntentCompilerKernel } from "./intent-compiler.ts";
import { TraceKernel } from "./trace-kernel.ts";
import { RuntimeTruthKernel } from "./runtime-truth-kernel.ts";
import { OsSecurityKernel } from "./os-security.ts";
import { McpRegistryKernel } from "./mcp-registry.ts";
import { A2ATransportKernel } from "./a2a-transport.ts";
import { OrgSyncKernel } from "./org-sync.ts";
import { ProjectBrainKernel } from "./project-brain.ts";
import { WorkSessionKernel } from "./work-session.ts";
import { WorkbenchExperienceKernel } from "./workbench-experience.ts";
import { LongTaskWorkerKernel } from "./long-task-worker.ts";
import { ContextPlaneKernel, ReplayRunnerKernel, LocalRuntimeServiceKernel, ProjectBundleKernel, FeedbackLearningKernel, DomainEvaluatorKernel, HandoffManifestKernel, CostLedgerKernel } from "./v01211-runtime.ts";
import { VerifiedAutonomousWorkKernel, SandboxConformanceKernel, TraceExplorerKernel } from "./v01212-verified-work.ts";
import { ActionGatewayKernel, AcceptanceGateKernel, DurableWorkerKernel, ProviderRouterKernel, A2AProtocolKernel } from "./v01213-runtime.ts";
import { RuntimeAssuranceKernel } from "./runtime-assurance.ts";
import { FederatedDelegationKernel } from "./federated-delegation.ts";
import { HarnessTopologyKernel } from "./harness-topology.ts";
import { RuntimeReadinessKernel } from "./runtime-readiness.ts";
import { AssuredPilotKernel } from "./assured-pilot.ts";
import { CapabilityKitRuntime } from "./capability-kit-runtime.ts";
import { KnowledgeMemoryRuntime } from "./knowledge-memory-runtime.ts";
import { WorkRuntimeModeKernel } from "./work-runtime-mode.ts";
import { ContinualHarnessKernel } from "./continual-harness.ts";
import { StatefulComputeKernel } from "./stateful-compute.ts";
import { UncertaintyPolicyKernel } from "./uncertainty-policy.ts";
import { ReleaseQualificationKernel } from "./release-qualification.ts";
import { VerificationPlane } from "./verification-plane.ts";
import { EvaluationModelProfileKernel } from "./evaluation-model-profile.ts";
import { WorkflowEvolutionKernel } from "./workflow-evolution.ts";

/**
 * Stable composition root for the service. Domain behavior stays in focused
 * kernels; CraftService is the backwards-compatible API facade.
 */
export abstract class ServiceFoundation {
  readonly store: CraftStore;
  readonly catalog: Catalog;
  readonly isolatedAdapter: LocalIsolatedAdapter;
  readonly workspace: WorkspaceState;
  readonly transaction: TransactionCoordinator;
  readonly trajectory: TrajectoryCompiler;
  readonly scriptRunner: VerifiedScriptRunner;
  readonly workbench: WorkbenchKernel;
  readonly changeSets: ChangeSetKernel;
  readonly controlPlane: ControlPlaneKernel;
  readonly security: SecurityBrokerKernel;
  readonly dataOnlyParser: DataOnlyParserAdapter;
  readonly parserProcess: ParserProcessAdapter;
  readonly sandbox: SandboxKernel;
  readonly dockerSandbox: DockerSandboxAdapter;
  readonly egressBroker: TrustedEgressBroker;
  readonly effects: ExternalEffectKernel;
  readonly recovery: RecoveryQueueKernel;
  readonly triggers: TriggerKernel;
  readonly speculative: SpeculativeKernel;
  readonly lineage: LineageKernel;
  readonly hydration: HydrationKernel;
  readonly autonomy: AutonomyKernel;
  readonly contracts: ContractInferenceKernel;
  readonly capabilityCanary: CapabilityCanaryKernel;
  readonly federation: CapabilityFederationKernel;
  readonly hubSync: HubSyncKernel;
  readonly materialization: MaterializationKernel;
  readonly certification: CapabilityCertificationKernel;
  readonly supplyChain: SupplyChainKernel;
  readonly attention: AttentionKernel;
  readonly home: HomeKernel;
  readonly codexHost: CodexHostKernel;
  readonly claudeHost: ClaudeHostKernel;
  readonly hostProfiles: readonly HostProfile[];
  readonly hostDrivers: Map<string, HostDriver>;
  readonly hostRuns: HostRunKernel;

  hostDriver(host: string): HostDriver | undefined { return this.hostDrivers.get(host); }
  readonly knowledgeLaunch: KnowledgeBoundLaunchKernel;
  readonly knowledgeWorkbench: KnowledgeWorkbenchKernel;
  readonly wikiCandidateGovernance: WikiCandidateGovernanceKernel;
  readonly guidedWork: GuidedWorkKernel;
  readonly executionSafety: ExecutionSafetyKernel;
  readonly localCandidateImport: LocalCandidateImportKernel;
  readonly a2aDiscovery: A2ADiscoveryKernel;
  readonly workDelivery: WorkDeliveryKernel;
  readonly deliveryEvaluation: DeliveryEvaluationKernel;
  readonly platformExecution: PlatformExecutionKernel;
  readonly deliveryLoop: DeliveryLoopKernel;
  readonly taskControl: TaskControlKernel;
  readonly taskRuns: TaskRunKernel;
  readonly taskBenchmarks: TaskBenchmarkKernel;
  readonly stateWorkspace: StateWorkspaceKernel;
  readonly verifiedWorkLoops: VerifiedWorkLoopKernel;
  readonly evalCampaigns: EvalCampaignKernel;
  readonly projectKnowledge: ProjectKnowledgeKernel;
  readonly capabilityConnectors: CapabilityConnectorKernel;
  readonly capabilityAccess: CapabilityAccessKernel;
  readonly capabilityKits: CapabilityKitRuntime;
  readonly knowledgeMemory: KnowledgeMemoryRuntime;
  readonly workRuntimeModes: WorkRuntimeModeKernel;
  readonly continualHarness: ContinualHarnessKernel;
  readonly statefulCompute: StatefulComputeKernel;
  readonly uncertaintyPolicies: UncertaintyPolicyKernel;
  readonly releaseQualifications: ReleaseQualificationKernel;
  readonly verificationPlane: VerificationPlane;
  readonly evaluationModelProfiles: EvaluationModelProfileKernel;
  readonly workflowEvolution: WorkflowEvolutionKernel;
  readonly hostActivationManifests: HostActivationManifestKernel;
  readonly executionFabric: ExecutionFabricKernel;
  readonly hostBridge: HostBridgeKernel;
  readonly managedWrites: ManagedWriteKernel;
  readonly evalCampaignReports: EvalCampaignReportKernel;
  readonly adaptiveHarnesses: AdaptiveHarnessKernel;
  readonly managedRuns: ManagedRunKernel;
  readonly campaignRunners: CampaignRunnerKernel;
  readonly runtimeAssurance: RuntimeAssuranceKernel;
  readonly federatedDelegation: FederatedDelegationKernel;
  readonly harnessTopologies: HarnessTopologyKernel;
  readonly runtimeReadiness: RuntimeReadinessKernel;
  readonly assuredPilot: AssuredPilotKernel;
  readonly autonomyLadder: AutonomyLadderKernel;
  readonly workspaceObserver: WorkspaceObserverKernel;
  readonly workCoordinators: WorkCoordinatorKernel;
  readonly agentEvalLab: AgentEvalLabKernel;
  readonly evaluationOperations: EvaluationOperationsKernel;
  readonly enterpriseAccess: EnterpriseAccessKernel;
  readonly a2aDelegation: A2ADelegationKernel;
  readonly autonomousRuntime: AutonomousRuntimeKernel;
  readonly capabilityLifecycle: CapabilityLifecycleKernel;
  readonly memoryConsolidation: MemoryConsolidationKernel;
  readonly remoteInterop: RemoteInteropKernel;
  readonly platformOperations: PlatformOperationsKernel;
  readonly modelProviders: readonly ModelProviderSpec[];
  readonly internalHost: InternalHostDriver;
  readonly metrics: MetricsKernel;
  readonly usage: UsageKernel;
  readonly intentCompiler: IntentCompilerKernel;
  readonly trace: TraceKernel;
  readonly runtimeTruth: RuntimeTruthKernel;
  readonly osSecurity: OsSecurityKernel;
  readonly mcpRegistry: McpRegistryKernel;
  readonly a2aTransport: A2ATransportKernel;
  readonly orgSync: OrgSyncKernel;
  readonly projectBrain: ProjectBrainKernel;
  readonly workSessions: WorkSessionKernel;
  readonly workbenchExperience: WorkbenchExperienceKernel;
  readonly longTaskWorker: LongTaskWorkerKernel;
  readonly contextPlane: ContextPlaneKernel;
  readonly replayRunner: ReplayRunnerKernel;
  readonly localRuntimeService: LocalRuntimeServiceKernel;
  readonly projectBundles: ProjectBundleKernel;
  readonly feedbackLearning: FeedbackLearningKernel;
  readonly domainEvaluators: DomainEvaluatorKernel;
  readonly handoffManifests: HandoffManifestKernel;
  readonly costLedger: CostLedgerKernel;
  readonly verifiedAutonomousWork: VerifiedAutonomousWorkKernel;
  readonly sandboxConformance: SandboxConformanceKernel;
  readonly traceExplorer: TraceExplorerKernel;
  readonly actionGateway: ActionGatewayKernel;
  readonly acceptanceGates: AcceptanceGateKernel;
  readonly durableWorker: DurableWorkerKernel;
  readonly providerRouter: ProviderRouterKernel;
  readonly a2aProtocol: A2AProtocolKernel;

  constructor(store: CraftStore, semanticProvider?: EmbeddingProvider, isolatedAdapter = new LocalIsolatedAdapter(),
    dockerSandbox = new DockerSandboxAdapter(), egressBroker = new TrustedEgressBroker(), hostOwnerId?: string,
    hostProfiles?: readonly HostProfile[], modelProviders?: readonly ModelProviderSpec[],
    modelTransport?: ModelTransport) {
    this.store = store; this.catalog = new Catalog(store, semanticProvider); this.isolatedAdapter = isolatedAdapter;
    this.workspace = new WorkspaceState(store, store.paths);
    this.transaction = new TransactionCoordinator(store, this.workspace); this.trajectory = new TrajectoryCompiler(store);
    this.scriptRunner = new VerifiedScriptRunner(store); this.workbench = new WorkbenchKernel(store);
    this.changeSets = new ChangeSetKernel(store, this.workbench); this.controlPlane = new ControlPlaneKernel(store);
    this.security = new SecurityBrokerKernel(store); this.dataOnlyParser = new DataOnlyParserAdapter(this.security);
    this.parserProcess = new ParserProcessAdapter(this.security); this.sandbox = new SandboxKernel(store);
    this.dockerSandbox = dockerSandbox; this.egressBroker = egressBroker; this.effects = new ExternalEffectKernel(store);
    this.recovery = new RecoveryQueueKernel(store); this.triggers = new TriggerKernel(store, egressBroker.env);
    this.speculative = new SpeculativeKernel(store); this.lineage = new LineageKernel(store);
    this.hydration = new HydrationKernel(store); this.autonomy = new AutonomyKernel(store);
    this.contracts = new ContractInferenceKernel(store); this.capabilityCanary = new CapabilityCanaryKernel(store);
    this.federation = new CapabilityFederationKernel(store); this.hubSync = new HubSyncKernel(store);
    this.materialization = new MaterializationKernel(store); this.certification = new CapabilityCertificationKernel(store);
    this.supplyChain = new SupplyChainKernel(store); this.attention = new AttentionKernel(store);
    this.home = new HomeKernel(store, this.attention); this.codexHost = new CodexHostKernel(store);
    this.claudeHost = new ClaudeHostKernel(store);
    this.hostProfiles = mergeHostProfiles([...(hostProfiles ?? [])]);
    this.modelProviders = modelProviders && modelProviders.length ? modelProviders : PROVIDER_CATALOG;
    this.internalHost = new InternalHostDriver(store, { providers: this.modelProviders, transport: modelTransport,
      tools: DEFAULT_INTERNAL_TOOLS,
      invokeAction: (action, args) => this.invokeInternalAction(action, args) });
    const drivers: [string, HostDriver][] = [
      ["codex-cli", this.codexHost],
      ["claude-code", this.claudeHost],
      ["internal", this.internalHost],
      ...this.hostProfiles.filter((profile) => !profile.builtin && profile.kind === "agent-cli")
        .map((profile): [string, HostDriver] => [profile.host, new GenericCliHostKernel(store, profile)]),
    ];
    this.hostDrivers = new Map(drivers);
    this.knowledgeLaunch = new KnowledgeBoundLaunchKernel(store);
    this.knowledgeWorkbench = new KnowledgeWorkbenchKernel(store);
    this.wikiCandidateGovernance = new WikiCandidateGovernanceKernel(store);
    this.guidedWork = new GuidedWorkKernel(store);
    this.executionSafety = new ExecutionSafetyKernel(store, this.sandbox);
    this.localCandidateImport = new LocalCandidateImportKernel(store);
    this.a2aDiscovery = new A2ADiscoveryKernel(store);
    this.workDelivery = new WorkDeliveryKernel(store);
    this.deliveryEvaluation = new DeliveryEvaluationKernel(store);
    this.platformExecution = new PlatformExecutionKernel(store);
    this.deliveryLoop = new DeliveryLoopKernel(store, this.workDelivery);
    this.taskControl = new TaskControlKernel(store, this.deliveryLoop);
    this.taskRuns = new TaskRunKernel(store);
    this.taskBenchmarks = new TaskBenchmarkKernel(store, this.deliveryEvaluation);
    this.stateWorkspace = new StateWorkspaceKernel(store);
    this.verifiedWorkLoops = new VerifiedWorkLoopKernel(store);
    this.evalCampaigns = new EvalCampaignKernel(store, this.taskBenchmarks);
    this.projectKnowledge = new ProjectKnowledgeKernel(store);
    this.capabilityConnectors = new CapabilityConnectorKernel(store);
    this.capabilityAccess = new CapabilityAccessKernel(store, this.catalog);
    this.capabilityKits = new CapabilityKitRuntime(store);
    this.knowledgeMemory = new KnowledgeMemoryRuntime(store);
    this.workRuntimeModes = new WorkRuntimeModeKernel(store, this.hostDrivers.keys());
    this.continualHarness = new ContinualHarnessKernel(store);
    this.statefulCompute = new StatefulComputeKernel(store);
    this.uncertaintyPolicies = new UncertaintyPolicyKernel(store);
    this.releaseQualifications = new ReleaseQualificationKernel(store);
    this.verificationPlane = new VerificationPlane(store);
    this.evaluationModelProfiles = new EvaluationModelProfileKernel(store, this.modelProviders);
    this.workflowEvolution = new WorkflowEvolutionKernel(store);
    this.hostActivationManifests = new HostActivationManifestKernel(store, this.hostProfiles);
    this.executionFabric = new ExecutionFabricKernel(store);
    this.hostBridge = new HostBridgeKernel(store);
    this.managedWrites = new ManagedWriteKernel(store, this.transaction, this.workspace);
    this.evalCampaignReports = new EvalCampaignReportKernel(store);
    this.adaptiveHarnesses = new AdaptiveHarnessKernel(store);
    this.managedRuns = new ManagedRunKernel(store);
    this.campaignRunners = new CampaignRunnerKernel(store, this.evalCampaigns);
    this.runtimeAssurance = new RuntimeAssuranceKernel(store, this.platformExecution, this.campaignRunners);
    this.federatedDelegation = new FederatedDelegationKernel(store);
    this.harnessTopologies = new HarnessTopologyKernel(store);
    this.runtimeReadiness = new RuntimeReadinessKernel(store, this.platformExecution);
    this.assuredPilot = new AssuredPilotKernel(store);
    this.autonomyLadder = new AutonomyLadderKernel(store);
    this.workspaceObserver = new WorkspaceObserverKernel(store, this.stateWorkspace);
    this.workCoordinators = new WorkCoordinatorKernel(store, this.managedRuns);
    this.agentEvalLab = new AgentEvalLabKernel(store);
    this.evaluationOperations = new EvaluationOperationsKernel(store, this.evalCampaigns);
    this.enterpriseAccess = new EnterpriseAccessKernel(store);
    this.a2aDelegation = new A2ADelegationKernel(store);
    this.autonomousRuntime = new AutonomousRuntimeKernel(store);
    this.capabilityLifecycle = new CapabilityLifecycleKernel(store);
    this.memoryConsolidation = new MemoryConsolidationKernel(store);
    this.remoteInterop = new RemoteInteropKernel(store);
    this.platformOperations = new PlatformOperationsKernel(store);
    this.metrics = new MetricsKernel(store);
    this.usage = new UsageKernel(store);
    this.intentCompiler = new IntentCompilerKernel(store);
    this.trace = new TraceKernel(store);
    this.runtimeTruth = new RuntimeTruthKernel(store);
    this.osSecurity = new OsSecurityKernel(store);
    this.mcpRegistry = new McpRegistryKernel(store);
    this.a2aTransport = new A2ATransportKernel();
    this.orgSync = new OrgSyncKernel(store);
    this.projectBrain = new ProjectBrainKernel(store);
    this.workSessions = new WorkSessionKernel(store, this.projectBrain);
    this.workbenchExperience = new WorkbenchExperienceKernel(store);
    this.longTaskWorker = new LongTaskWorkerKernel(store);
    this.contextPlane = new ContextPlaneKernel(store);
    this.replayRunner = new ReplayRunnerKernel(store);
    this.localRuntimeService = new LocalRuntimeServiceKernel(store);
    this.projectBundles = new ProjectBundleKernel(store);
    this.feedbackLearning = new FeedbackLearningKernel(store);
    this.domainEvaluators = new DomainEvaluatorKernel(store);
    this.handoffManifests = new HandoffManifestKernel(store);
    this.costLedger = new CostLedgerKernel(store);
    this.verifiedAutonomousWork = new VerifiedAutonomousWorkKernel(store);
    this.sandboxConformance = new SandboxConformanceKernel(store);
    this.traceExplorer = new TraceExplorerKernel(store);
    this.actionGateway = new ActionGatewayKernel(store);
    this.acceptanceGates = new AcceptanceGateKernel(store);
    this.durableWorker = new DurableWorkerKernel(store);
    this.providerRouter = new ProviderRouterKernel(store);
    this.a2aProtocol = new A2AProtocolKernel();
    this.hostRuns = new HostRunKernel(store, [...this.hostDrivers.values()], hostOwnerId,
      (run, receipt) => this.finalizeWorkLaunch(run, receipt), this.trace);
  }

  // Implemented by the public facade after the corresponding domain method exists.
  protected abstract finalizeWorkLaunch(run: JsonObject, receipt: JsonObject | null): void;

  /**
   * The bounded action surface the internal host may call.
   *
   * This is a whitelist on purpose: a self-hosted loop that can reach any Craft
   * operation would be a privilege escalation relative to the governed host
   * path. Abstract so the facade owns the list, exactly like finalizeWorkLaunch.
   */
  protected abstract invokeInternalAction(action: string, args: JsonObject): JsonObject | Promise<JsonObject>;
}
