import { discoverContextTools } from "../../mcp/context-tools.ts";
import type { CraftService } from "../craft-service.ts";
import type { JsonObject } from "../../infrastructure/store.ts";
import type { ComponentName } from "../../component-readiness.ts";
import type { McpHandlerGroup } from "./handler-types.js";
import { createRuntimeHandlers } from "./runtime-handlers.ts";
import { createWorkHandlers } from "./work-handlers.ts";
import { createEvaluationHandlers } from "./evaluation-handlers.ts";
import { createWorkspaceHandlers } from "./workspace-handlers.ts";

/** Caller identity is local; transport construction does not change internal dispatch. */
export function createActionHandlers(service: CraftService, mountedComponent?: ComponentName): McpHandlerGroup {
  const componentArgs = (args: JsonObject): JsonObject => {
    if (!mountedComponent) return args;
    if (args.members !== undefined && (!Array.isArray(args.members) || args.members.length !== 1 || args.members[0] !== mountedComponent)) throw new Error("Context members must match the mounted component");
    return { ...args, members: [mountedComponent] };
  };
  return {
      ...createRuntimeHandlers(service),
      ...createWorkHandlers(service),
      ...createEvaluationHandlers(service),
      ...createWorkspaceHandlers(service),
      craft_info: () => service.info(),
      craft_context_tools_discover: (a) => discoverContextTools(a),
      craft_context_open: (a) => service.contextOpen(a),
      craft_codebase_repository_ensure: (a) => service.codebaseRepositoryEnsure(a),
      craft_component_readiness_get: (a) => service.componentReadinessGet(a, mountedComponent),
      craft_component_diagnose: (a) => service.componentDiagnose(a, mountedComponent),
      craft_activation_proof_doctor: (a) => service.activationProofDoctor(a),
      craft_codebase_workspace_open: (a) => service.codebaseWorkspaceOpen(a),
      craft_codebase_refresh: (a) => service.codebaseRefresh(a),
      craft_codebase_activate: (a) => service.codebaseActivate(a),
      craft_codebase_deactivate: (a) => service.codebaseDeactivate(a),
      craft_codebase_status: (a) => service.codebaseStatus(a),
      craft_codebase_analysis_import: (a) => service.codebaseAnalysisImport(a),
      craft_codebase_index_build: (a) => service.codebaseIndexBuild(a),
      craft_codebase_symbol_find: (a) => service.codebaseSymbolFind(a),
      craft_codebase_callers_find: (a) => service.codebaseCallersFind(a),
      craft_codebase_impact_query: (a) => service.codebaseImpactQuery(a),
      craft_codebase_context_slice: (a) => service.codebaseContextSlice(a),
      craft_component_history_knowledge_migrate: (a) => service.componentHistoryKnowledgeReviewedMigrate(a),
      craft_component_history_experience_migrate: (a) => service.componentHistoryExperienceMigrate(a),
      craft_adapter_manifest_save: (a) => service.adapterManifestSave(a), craft_adapter_manifest_get: (a) => service.adapterManifestGet(a), craft_adapter_manifest_list: (a) => service.adapterManifestList(a),
      craft_adapter_health: (a) => service.adapterHealth(a), craft_adapter_conformance: (a) => service.adapterConformance(a), craft_adapter_quarantine: (a) => service.adapterQuarantine(a), craft_adapter_rollback: (a) => service.adapterRollback(a),
      craft_command_plan: (a) => service.commandPlan(a), craft_command_run: (a) => service.commandRun(a), craft_command_observe: (a) => service.commandObserve(a), craft_command_cancel: (a) => service.commandCancel(a),
      craft_capability_projection: (a) => service.capabilityProjection(a),
      craft_durable_run_start: (a) => service.durableRunStart(a), craft_durable_run_tick: (a) => service.durableRunTick(a), craft_durable_run_complete: (a) => service.durableRunComplete(a), craft_durable_run_recover: (a) => service.durableRunRecover(a),
      craft_trust_curve_record: (a) => service.trustCurveRecord(a), craft_model_route: (a) => service.modelRouteV01226(a), craft_delivery_gate: (a) => service.deliveryGateV01226(a),
      craft_task_handoff_manifest: (a) => service.taskHandoffManifest(a), craft_domain_evaluator_run: (a) => service.domainEvaluatorRun(a), craft_openapi_import: (a) => service.openApiImport(a),
      craft_trust_profile_record: (a) => service.trustProfileRecord(a), craft_trust_profile_recommend: (a) => service.trustProfileRecommend(a),
      craft_trust_profile_get: (a) => service.trustProfileGet(a), craft_trust_profile_list: (a) => service.trustProfileList(a), craft_trust_profile_revoke: (a) => service.trustProfileRevoke(a),
      craft_web_fetch: (a) => service.webFetch(a), craft_web_action_prepare: (a) => service.webActionPrepare(a),
      craft_web_action_complete: (a) => service.webActionComplete(a), craft_web_operation_get: (a) => service.webOperationGet(a),
      craft_source_add: (a) => service.sourceAdd(a),
      craft_source_list: () => service.sourceList(), craft_source_update: (a) => service.sourceUpdate(a),
      craft_source_remove: (a) => service.sourceRemove(a), craft_source_scan: (a) => service.sourceScan(a),
      craft_capability_search: (a) => service.capabilitySearch(a), craft_logical_capability_list: () => service.logicalCapabilityList(),
      craft_logical_activation_plan: (a) => service.logicalActivationPlan(a),
      craft_logical_activation_plan_get: (a) => service.get("logical_activation_plan", "plan_id", a),
      craft_logical_activation_plan_list: (a) => service.list("logical_activation_plan", "plans", a),
      craft_logical_activation_audit: (a) => service.logicalActivationAudit(a), craft_semantic_status: () => service.semanticSearchStatus(),
      craft_logical_activation_resolve: (a) => service.logicalActivationResolve(a),
      craft_logical_activation_resolution_get: (a) => service.get("logical_activation_resolution", "resolution_id", a),
      craft_logical_activation_resolution_list: (a) => service.list("logical_activation_resolution", "resolutions", a),
      craft_execution_policy_decide: service.executionPolicyDecide.bind(service),
      craft_first_run_readiness: service.firstRunReadiness.bind(service),
      craft_credential_resolve: service.credentialResolve.bind(service),
      craft_mcp_protocol_negotiate: service.mcpProtocolNegotiate.bind(service),
      craft_mcp_migration_assess: service.mcpMigrationAssess.bind(service),
      craft_isolation_capability_get: service.isolationCapabilityGet.bind(service),
      craft_distribution_plan_get: service.distributionPlanGet.bind(service),
      craft_context_project: service.contextProject.bind(service),
      craft_context_restore: service.contextRestore.bind(service),
      craft_context_projection_get: service.contextProjectionGet.bind(service),
      craft_state_view_get: service.stateViewGet.bind(service),
      craft_bm25_search: service.bm25Search.bind(service),
      craft_retrieval_fuse: service.retrievalFuse.bind(service),
      craft_experience_capture_decide: service.experienceCaptureDecide.bind(service),
      craft_experience_capture_build: service.experienceCaptureBuild.bind(service),
      craft_memory_decay_get: service.memoryDecayWeightGet.bind(service),
      craft_memory_capture_propose: service.memoryProposePolicy.bind(service),
      craft_memory_promotion_preview: service.memoryLegacyPromote.bind(service),
      craft_memory_hybrid_scores: service.memoryHybridScores.bind(service),
      craft_memory_usage_record: service.memoryUsageEvidenceRecord.bind(service),
      craft_verification_check: service.verificationCheck.bind(service),
      craft_verification_evaluate: service.verificationRun.bind(service),
      craft_verification_capture_signals_get: service.verificationCaptureSignals.bind(service),
      craft_trajectory_signature_get: service.trajectorySignatureGet.bind(service),
      craft_abstraction_evaluate: service.abstractionEvaluate.bind(service),
      craft_abstraction_build: service.abstractionBuild.bind(service),
      craft_failure_attribution_get: service.failureAttributionGet.bind(service),
      craft_failure_attribution_summary_get: service.failureAttributionSummaryGet.bind(service),
      craft_mcp_declarations_get: () => service.mcpDeclarationsGet(),
      craft_consistency_check: service.consistencyCheck.bind(service),
      craft_governance_pin_get: service.governancePinGet.bind(service),
      craft_governance_pin_check: service.governancePinCheck.bind(service),
      craft_governance_compaction_evaluate: service.governanceCompactionEvaluate.bind(service),
      craft_governance_constraint_define: service.governanceConstraintDefine.bind(service),
      craft_mcp_discover_get: service.mcpDiscoverGet.bind(service),
      craft_mcp_forward_compat_get: service.mcpForwardCompatGet.bind(service),
      craft_capability_get: (a) => service.capabilityGet(a),
      craft_default_route: (a) => service.defaultRouteWithSemanticSearch(a), craft_default_route_execute: (a) => service.defaultRouteExecute(a),
      craft_default_route_resume: (a) => service.defaultRouteResume(a), craft_default_route_find: (a) => service.defaultRouteFind(a),
      craft_project_policy_save: (a) => service.projectPolicySave(a),
      craft_project_policy_get: (a) => service.get("project_policy", "policy_id", a),
      craft_project_policy_list: (a) => service.list("project_policy", "policies", a),
      craft_route_receipt_record: (a) => service.routeReceiptRecord(a),
      craft_host_adapter_save: (a) => service.hostAdapterSave(a),
      craft_host_adapter_get: (a) => service.get("host_adapter", "host_adapter_id", a),
      craft_host_adapter_list: (a) => service.list("host_adapter", "host_adapters", a),
      craft_host_adapter_dispatch: (a) => service.hostAdapterDispatch(a),
      craft_host_adapter_report: (a) => service.hostAdapterReport(a),
      craft_local_isolated_execute: service.localIsolatedExecute.bind(service),
      craft_route_workflow_proposal_create: (a) => service.routeWorkflowProposalCreate(a),
      craft_default_route_update: (a) => service.defaultRouteUpdate(a),
      craft_task_open: (a) => service.taskOpen(a), craft_task_list: (a) => service.taskList(a),
      craft_intent_compile: (a) => service.intentCompile(a), craft_intent_get: (a) => service.intentGet(a),
      craft_acceptance_compile: (a) => service.acceptanceCompile(a), craft_acceptance_contract_get: (a) => service.acceptanceContractGet(a),
      craft_task_checkpoint: (a) => service.taskCheckpoint(a), craft_feedback_record: (a) => service.feedbackRecord(a),
      craft_task_control_save: (a) => service.taskControlSave(a), craft_task_control_bind_launch: (a) => service.taskControlBindLaunch(a),
      craft_campaign_runner_create: (a) => service.campaignRunnerCreate(a), craft_campaign_runner_claim: (a) => service.campaignRunnerClaim(a), craft_campaign_runner_bind: (a) => service.campaignRunnerBind(a), craft_campaign_runner_advance: (a) => service.campaignRunnerAdvance(a), craft_campaign_runner_get: (a) => service.campaignRunnerGet(a),
      craft_evaluation_model_profile_save: (a) => service.evaluationModelProfileSave(a), craft_evaluation_model_profile_get: (a) => service.evaluationModelProfileGet(a), craft_evaluation_model_profile_list: (a) => service.evaluationModelProfileList(a), craft_evaluation_model_ticket_issue: (a) => service.evaluationModelTicketIssue(a),
      craft_experience_observe: (a) => service.workflowEvolutionObserve(a), craft_experience_patterns_list: (a) => service.workflowEvolutionObservations(a), craft_experience_procedure_draft: (a) => service.workflowEvolutionPropose(a), craft_experience_procedure_submit: (a) => service.workflowEvolutionProposalSubmit(a), craft_experience_procedure_get: (a) => service.workflowEvolutionProposalGet(a),
      craft_experience_procedure_projection_draft: (a) => service.experienceProcedureDraft(a), craft_experience_procedure_gate: (a) => service.experienceProcedureGate(a), craft_experience_procedure_projection_get: (a) => service.experienceProcedureGet(a), craft_experience_procedure_projection_list: (a) => service.experienceProcedureList(a), craft_experience_procedure_skill_export: (a) => service.experienceProcedureSkillExport(a),
      craft_procedure_configuration_save: (a) => service.procedureConfigurationSave(a),
      craft_experience_graph_inspect: (a) => service.experienceGraphInspect(a),
      craft_experience_graph_edit: (a) => service.experienceGraphEdit(a),
      craft_knowledge_asset_inspect: (a) => service.componentAssetInspect("knowledge", a),
      craft_knowledge_asset_restore: (a) => service.componentAssetRestore("knowledge", a),
      craft_memory_asset_inspect: (a) => service.componentAssetInspect("memory", a),
      craft_memory_asset_restore: (a) => service.componentAssetRestore("memory", a),
      craft_experience_asset_inspect: (a) => service.componentAssetInspect("experience", a),
      craft_experience_asset_restore: (a) => service.componentAssetRestore("experience", a),
      craft_codebase_asset_inspect: (a) => service.componentAssetInspect("codebase", a),
      craft_codebase_asset_restore: (a) => service.componentAssetRestore("codebase", a),
      craft_procedure_host_control: (a) => service.procedureHostControl(a),
      craft_procedure_decision_evaluate: (a) => service.procedureDecisionEvaluate(a),
      craft_procedure_invocation_bind: (a) => service.procedureInvocationBind(a),
      craft_procedure_invocation_dispatch: (a) => service.procedureInvocationDispatch(a),
      craft_procedure_invocation_report: (a) => service.procedureInvocationReport(a),
      craft_procedure_invocation_resume: (a) => service.procedureInvocationResume(a),
      craft_procedure_invocation_transition: (a) => service.procedureInvocationTransition(a),
      craft_procedure_invocation_get: (a) => service.procedureInvocationGet(a),
      craft_procedure_invocation_evaluate: (a) => service.procedureInvocationEvaluate(a),
      craft_procedure_plan: (a) => service.experienceProcedurePlan(a),
      craft_procedure_create: (a) => service.experienceProcedureDraft(a), craft_procedure_gate: (a) => service.experienceProcedureGate(a), craft_procedure_get: (a) => service.experienceProcedureGet(a), craft_procedure_list: (a) => service.experienceProcedureList(a), craft_procedure_export_skill: (a) => service.experienceProcedureSkillExport(a),
      craft_durable_action_loop_create: service.durableActionLoopCreate.bind(service), craft_durable_action_loop_next: service.durableActionLoopNext.bind(service), craft_durable_action_loop_propose: service.durableActionLoopPropose.bind(service), craft_durable_action_loop_dispatch: service.durableActionLoopDispatch.bind(service), craft_durable_action_loop_report: service.durableActionLoopReport.bind(service), craft_durable_action_loop_resume: service.durableActionLoopResume.bind(service), craft_durable_action_loop_get: service.durableActionLoopGet.bind(service),
      craft_experience_ledger_observe: service.experienceLedgerObserve.bind(service), craft_experience_ledger_compile: service.experienceLedgerCompile.bind(service), craft_experience_ledger_propose: service.experienceLedgerPropose.bind(service), craft_experience_ledger_evaluate: service.experienceLedgerEvaluate.bind(service), craft_experience_ledger_decide: service.experienceLedgerDecide.bind(service), craft_experience_ledger_get: service.experienceLedgerGet.bind(service),
      craft_runtime_assurance_attest: (a) => service.runtimeAssuranceAttest(a), craft_runtime_assurance_intervene: (a) => service.runtimeAssuranceIntervene(a), craft_runtime_assurance_campaign_advance: (a) => service.runtimeAssuranceCampaignAdvance(a), craft_runtime_assurance_get: (a) => service.runtimeAssuranceGet(a),
      craft_assured_pilot_seal_case: (a) => service.assuredPilotSealCase(a), craft_assured_pilot_access_issue: (a) => service.assuredPilotIssueSealedAccess(a), craft_assured_pilot_access_consume: (a) => service.assuredPilotConsumeSealedAccess(a), craft_assured_pilot_recovery_record: (a) => service.assuredPilotRecordRecovery(a), craft_assured_pilot_prepare: (a) => service.assuredPilotPrepare(a), craft_assured_pilot_reassess: (a) => service.assuredPilotReassess(a), craft_assured_pilot_get: (a) => service.assuredPilotGet(a),
      craft_agent_eval_lab_create: (a) => service.agentEvalLabCreate(a), craft_agent_eval_lab_start: (a) => service.agentEvalLabStart(a), craft_agent_eval_lab_observe: (a) => service.agentEvalLabObserve(a), craft_agent_eval_lab_get: (a) => service.agentEvalLabGet(a),
      craft_project_knowledge_discover: (a) => service.projectKnowledgeDiscover(a), craft_project_knowledge_resolve: (a) => service.projectKnowledgeResolve(a), craft_project_knowledge_propose_update: (a) => service.projectKnowledgeProposeUpdate(a),
      craft_memory_remember: (a) => service.memoryRemember(a), craft_memory_transition: (a) => service.memoryTransition(a),
      craft_context_assemble: (a) => service.contextAssemble(a),
      craft_context_profile_save: (a) => service.contextProfileSave(a),
      craft_context_profile_get: (a) => service.get("context_profile", "profile_id", a),
      craft_context_profile_list: (a) => service.list("context_profile", "profiles", a),
      craft_context_profile_assemble: (a) => service.contextProfileAssemble(a),
      craft_task_graph_create: (a) => service.taskGraphCreate(a),
      craft_task_graph_get: (a) => service.get("task_graph", "graph_id", a),
      craft_task_graph_list: (a) => service.list("task_graph", "graphs", a),
      craft_task_graph_advance: (a) => service.taskGraphAdvance(a),
      craft_change_set_create: (a) => service.changeSetCreate(a), craft_change_set_preview: (a) => service.changeSetPreview(a),
      craft_change_set_apply: (a) => service.changeSetApply(a), craft_budget_open: (a) => service.budgetOpen(a),
      craft_budget_reserve: (a) => service.budgetReserve(a), craft_budget_settle: (a) => service.budgetSettle(a),
      craft_budget_close: (a) => service.budgetClose(a),
      craft_durable_wait_create: (a) => service.durableWaitCreate(a), craft_durable_wait_resume: (a) => service.durableWaitResume(a),
      craft_external_event_ingest: (a) => service.externalEventIngest(a),
      craft_durable_wait_sweep: (a) => service.durableWaitSweep(a),
      craft_fallback_contract_save: (a) => service.fallbackContractSave(a), craft_fallback_evaluate: (a) => service.fallbackEvaluate(a),
      craft_fallback_complete: (a) => service.fallbackComplete(a),
      craft_credential_handle_register: (a) => service.credentialHandleRegister(a),
      craft_enterprise_identity_provider_register: (a) => service.enterpriseIdentityProviderRegister(a), craft_enterprise_identity_provider_verify: (a) => service.enterpriseIdentityProviderVerify(a), craft_enterprise_principal_bind: (a) => service.enterprisePrincipalBind(a), craft_enterprise_adapter_bind: (a) => service.enterpriseAdapterBind(a), craft_enterprise_access_ticket_issue: (a) => service.enterpriseAccessTicketIssue(a), craft_enterprise_access_ticket_consume: (a) => service.enterpriseAccessTicketConsume(a), craft_enterprise_access_ticket_get: (a) => service.enterpriseAccessTicketGet(a),
      craft_credential_lease_issue: (a) => service.credentialLeaseIssue(a),
      craft_credential_lease_revoke: (a) => service.credentialLeaseRevoke(a),
      craft_egress_authorize: (a) => service.egressAuthorize(a),
      craft_egress_request_digest: (a) => service.egressRequestDigest(a), craft_egress_execute: (a) => service.egressExecute(a),
      craft_sandbox_egress_deliver: (a) => service.sandboxEgressDeliver(a),
      craft_external_effect_prepare: (a) => service.externalEffectPrepare(a), craft_external_effect_start: (a) => service.externalEffectStart(a),
      craft_external_effect_report: (a) => service.externalEffectReport(a), craft_external_effect_resolve: (a) => service.externalEffectResolve(a),
      craft_effect_reconciliation_execute: (a) => service.effectReconciliationExecute(a),
      craft_effect_compensation_issue: (a) => service.effectCompensationIssue(a), craft_effect_compensation_report: (a) => service.effectCompensationReport(a),
      craft_effect_compensation_execute: (a) => service.effectCompensationExecute(a),
      craft_effect_saga_create: (a) => service.effectSagaCreate(a), craft_effect_saga_get: (a) => service.effectSagaGet(a),
      craft_recovery_queue_refresh: (a) => service.recoveryQueueRefresh(a), craft_recovery_work_claim: (a) => service.recoveryWorkClaim(a),
      craft_attention_refresh: (a) => service.attentionRefresh(a), craft_attention_list: (a) => service.attentionList(a),
      craft_attention_decide: (a) => service.attentionDecide(a),
      craft_home_view: (a) => service.homeView(a),
      craft_codex_dispatch_prepare: (a) => service.codexDispatchPrepare(a),
      craft_codex_dispatch_execute: (a) => service.codexDispatchExecute(a),
      craft_claude_dispatch_prepare: (a) => service.claudeDispatchPrepare(a),
      craft_claude_dispatch_execute: (a) => service.claudeDispatchExecute(a),
      craft_capability_context_dispatch_prepare: (a) => service.capabilityContextDispatchPrepare(a),
      craft_capability_context_dispatch_execute: (a) => service.capabilityContextDispatchExecute(a),
      craft_host_run_start: (a) => service.hostRunStart(a),
      craft_host_run_get: (a) => service.hostRunGet(a),
      craft_host_run_cancel: (a) => service.hostRunCancel(a),
      craft_host_run_recover: (a) => service.hostRunRecover(a),
      craft_delivery_loop_refresh: (a) => service.deliveryLoopRefresh(a), craft_delivery_loop_get: (a) => service.deliveryLoopGet(a),
      craft_delivery_evaluation_case_save: (a) => service.deliveryEvaluationCaseSave(a), craft_delivery_evaluation_compare: (a) => service.deliveryEvaluationCompare(a), craft_delivery_evaluation_run: (a) => service.deliveryEvaluationRun(a),
      craft_task_benchmark_create: (a) => service.taskBenchmarkCreate(a), craft_task_benchmark_evaluate: (a) => service.taskBenchmarkEvaluate(a), craft_task_benchmark_aggregate: (a) => service.taskBenchmarkAggregate(a), craft_task_benchmark_candidate_propose: (a) => service.taskBenchmarkCandidatePropose(a), craft_task_benchmark_candidate_authorize_canary: (a) => service.taskBenchmarkCandidateAuthorizeCanary(a), craft_task_benchmark_candidate_canary_start: (a) => service.taskBenchmarkCandidateCanaryStart(a), craft_task_benchmark_candidate_canary_observe: (a) => service.taskBenchmarkCandidateCanaryObserve(a), craft_task_benchmark_candidate_canary_conclude: (a) => service.taskBenchmarkCandidateCanaryConclude(a),
      craft_platform_execution_profile_save: (a) => service.platformExecutionProfileSave(a), craft_platform_execution_conformance_record: (a) => service.platformExecutionConformanceRecord(a), craft_platform_execution_preflight: (a) => service.platformExecutionPreflight(a),
      craft_platform_execution_probe: (a) => service.platformExecutionProbe(a), craft_platform_execution_probe_get: (a) => service.platformExecutionProbeGet(a),
      craft_execution_safety_preflight: (a) => service.executionSafetyPreflight(a),
      craft_execution_safety_get: (a) => service.executionSafetyGet(a),
      craft_safety_work_launch_prepare: (a) => service.safetyWorkLaunchPrepare(a),
      craft_safety_work_launch_decide: (a) => service.safetyWorkLaunchDecide(a),
      craft_wiki_candidate_local_import: (a) => service.wikiCandidateLocalImport(a),
      craft_wiki_candidate_local_import_get: (a) => service.wikiCandidateLocalImportGet(a),
      craft_a2a_agent_card_discover: (a) => service.a2aAgentCardDiscover(a), craft_a2a_agent_card_get: (a) => service.a2aAgentCardGet(a), craft_a2a_agent_card_list: (a) => service.a2aAgentCardList(a), craft_a2a_agent_trust_approve: (a) => service.a2aAgentTrustApprove(a), craft_a2a_collaboration_session_create: (a) => service.a2aCollaborationSessionCreate(a), craft_a2a_delegation_prepare: (a) => service.a2aDelegationPrepare(a), craft_a2a_delegation_dispatch: (a) => service.a2aDelegationDispatch(a), craft_a2a_delegation_report: (a) => service.a2aDelegationReport(a), craft_a2a_delegation_get: (a) => service.a2aDelegationGet(a),
      craft_federated_agent_health_record: (a) => service.federatedAgentHealthRecord(a), craft_federated_delegation_grant_issue: (a) => service.federatedDelegationGrantIssue(a), craft_federated_delegation_grant_consume: (a) => service.federatedDelegationGrantConsume(a), craft_federated_remote_receipt_record: (a) => service.federatedDelegationReceiptRecord(a), craft_federated_delegation_revoke: (a) => service.federatedDelegationRevoke(a), craft_federated_delegation_reconcile: (a) => service.federatedDelegationReconcile(a), craft_federated_delegation_get: (a) => service.federatedDelegationGet(a),
      craft_harness_topology_define: (a) => service.harnessTopologyDefine(a), craft_harness_topology_promote: (a) => service.harnessTopologyPromote(a), craft_harness_topology_select: (a) => service.harnessTopologySelect(a), craft_harness_topology_suspend: (a) => service.harnessTopologySuspend(a), craft_harness_topology_get: (a) => service.harnessTopologyGet(a), craft_runtime_readiness_assess: (a) => service.runtimeReadinessAssess(a), craft_runtime_readiness_get: (a) => service.runtimeReadinessGet(a), craft_runtime_model_status: () => service.runtimeReadinessProviderStatus(), craft_runtime_model_probe: (a) => service.runtimeReadinessModelProbe(a), craft_mcp_task_create: (a) => service.mcpTaskCreate(a), craft_mcp_task_get: (a) => service.mcpTaskGet(a), craft_mcp_task_update: (a) => service.mcpTaskUpdate(a), craft_mcp_task_cancel: (a) => service.mcpTaskCancel(a), craft_mcp_task_expire: (a) => service.mcpTaskExpire(a), craft_runtime_proof_manifest: (a) => service.runtimeProofManifest(a), craft_runtime_proof_probe: (a) => service.runtimeProofProbe(a), craft_runtime_proof_conformance: (a) => service.runtimeProofConformance(a), craft_runtime_proof_attest: (a) => service.runtimeProofAttest(a), craft_runtime_proof_rehydrate: (a) => service.runtimeProofRehydrate(a),
      craft_capability_context_work_launch_prepare: (a) => service.capabilityContextWorkLaunchPrepare(a),
      craft_capability_context_work_launch_decide: (a) => service.capabilityContextWorkLaunchDecide(a),
      craft_knowledge_context_work_launch_prepare: (a) => service.knowledgeContextWorkLaunchPrepare(a),
      craft_knowledge_context_work_launch_decide: (a) => service.knowledgeContextWorkLaunchDecide(a),
      craft_knowledge_context_work_launch_retry: (a) => service.knowledgeContextWorkLaunchRetry(a),
      craft_verified_iteration_create: (a) => service.verifiedIterationCreate(a),
      craft_verified_iteration_get: (a) => service.verifiedIterationGet(a),
      craft_verified_iteration_assess: (a) => service.verifiedIterationAssess(a),
      craft_strategy_recommend: (a) => service.strategyRecommend(a),
      craft_knowledge_claim_save: (a) => service.knowledgeClaimSave(a), craft_knowledge_claim_get: (a) => service.knowledgeClaimGet(a), craft_knowledge_claim_list: (a) => service.knowledgeClaimList(a), craft_knowledge_claim_review: (a) => service.knowledgeClaimReview(a), craft_knowledge_promotion_policy_get: () => service.knowledgePromotionPolicyGet(), craft_knowledge_promotion_policy_save: (a) => service.knowledgePromotionPolicySave(a), craft_knowledge_support_record: (a) => service.knowledgeClaimSupportRecord(a), craft_knowledge_semantic_review_packet: (a) => service.knowledgeSemanticReviewPacket(a), craft_knowledge_semantic_provider_review: (a) => service.knowledgeSemanticProviderReview(a), craft_knowledge_host_review: (a) => service.knowledgeHostReview(a), craft_knowledge_auto_review: (a) => service.knowledgeAutoReview(a),
      craft_knowledge_candidate_model_review: (a) => service.knowledgeCandidateModelReview(a),
      craft_content_status: () => service.contentStatus(), craft_content_verify: (a) => service.contentVerify(a), craft_content_migrate: (a) => service.contentMigrate(a),
      craft_wiki_page_save: (a) => service.wikiPageSave(a), craft_wiki_page_get: (a) => service.wikiPageGet(a), craft_wiki_page_list: (a) => service.wikiPageList(a), craft_wiki_page_refresh: (a) => service.wikiPageRefresh(a), craft_knowledge_relation_save: (a) => service.knowledgeRelationSave(a),
      craft_relation_relate: (a) => service.relationSave(a), craft_relation_retract: (a) => service.relationRetract(a), craft_relation_get: (a) => service.relationGet(a),
      craft_relation_neighbors: (a) => service.relationNeighbors(a), craft_relation_traverse: (a) => service.relationTraverse(a),
      craft_knowledge_workbench_view: (a) => service.knowledgeWorkbenchView(a), craft_knowledge_context_bundle_preview: (a) => service.knowledgeContextBundlePreview(a),
      craft_wiki_context_compile: (a) => service.wikiContextCompile(a), craft_wiki_context_bundle_get: (a) => service.wikiContextBundleGet(a), craft_wiki_context_bundle_list: (a) => service.wikiContextBundleList(a),
      craft_wiki_skill_candidate_create: (a) => service.wikiSkillCandidateCreate(a), craft_wiki_skill_candidate_get: (a) => service.wikiSkillCandidateGet(a), craft_wiki_skill_candidate_list: (a) => service.wikiSkillCandidateList(a), craft_wiki_skill_candidate_review: (a) => service.wikiSkillCandidateReview(a),
      craft_wiki_skill_candidate_evaluation_attest: (a) => service.wikiSkillCandidateEvaluationAttest(a), craft_wiki_skill_candidate_publication_authorize: (a) => service.wikiSkillCandidatePublicationAuthorize(a),
      craft_wiki_skill_candidate_publication_package_prepare: (a) => service.wikiSkillCandidatePublicationPackagePrepare(a), craft_wiki_skill_candidate_publication_package_get: (a) => service.wikiSkillCandidatePublicationPackageGet(a), craft_wiki_skill_candidate_publication_package_list: (a) => service.wikiSkillCandidatePublicationPackageList(a),
      craft_guided_work_create: (a) => service.guidedWorkCreate(a), craft_guided_work_decide: (a) => service.guidedWorkDecide(a), craft_guided_work_get: (a) => service.guidedWorkGet(a), craft_guided_work_launch_prepare: (a) => service.guidedWorkLaunchPrepare(a),
      craft_knowledge_evaluation_case_save: (a) => service.knowledgeEvaluationCaseSave(a), craft_knowledge_evaluation_case_list: (a) => service.knowledgeEvaluationCaseList(a), craft_knowledge_evaluation_run: (a) => service.knowledgeEvaluationRun(a), craft_knowledge_evaluation_run_get: (a) => service.knowledgeEvaluationRunGet(a), craft_knowledge_evaluation_run_list: (a) => service.knowledgeEvaluationRunList(a),
      craft_domain_kit_save: (a) => service.domainKitSave(a), craft_domain_kit_get: (a) => service.domainKitGet(a), craft_domain_kit_list: (a) => service.domainKitList(a),
      craft_domain_kit_install_builtins: () => service.domainKitInstallBuiltins(), craft_domain_kit_apply: (a) => service.domainKitApply(a),
      craft_domain_kit_settle: (a) => service.domainKitSettle(a),
      craft_domain_kit_action_lock_get: (a) => service.domainKitActionLockGet(a), craft_domain_kit_action_prepare: (a) => service.domainKitActionPrepare(a),
      craft_domain_kit_action_report: (a) => service.domainKitActionReport(a),
      craft_home_task: (a) => service.homeTask(a),
      craft_recovery_work_report: (a) => service.recoveryWorkReport(a), craft_recovery_lease_recover: (a) => service.recoveryLeaseRecover(a),
      craft_trigger_subscription_save: (a) => service.triggerSubscriptionSave(a), craft_webhook_trigger_ingest: (a) => service.webhookTriggerIngest(a),
      craft_speculative_policy_save: (a) => service.speculativePolicySave(a), craft_speculative_enqueue: (a) => service.speculativeEnqueue(a),
      craft_speculative_claim: (a) => service.speculativeClaim(a), craft_speculative_submit: (a) => service.speculativeSubmit(a),
      craft_speculative_decide: (a) => service.speculativeDecide(a), craft_speculative_expire: (a) => service.speculativeExpire(a),
      craft_lineage_record: (a) => service.lineageRecord(a), craft_lineage_trace: (a) => service.lineageTrace(a),
      craft_lineage_verify: (a) => service.lineageVerify(a),
      craft_dehydration_capture: (a) => service.dehydrationCapture(a), craft_hydration_inspect: (a) => service.hydrationInspect(a),
      craft_hydration_claim: (a) => service.hydrationClaim(a), craft_hydration_report: (a) => service.hydrationReport(a),
      craft_hydration_lease_recover: (a) => service.hydrationLeaseRecover(a),
      craft_autonomy_policy_save: (a) => service.autonomyPolicySave(a), craft_autonomy_request: (a) => service.autonomyRequest(a),
      craft_autonomy_decide: (a) => service.autonomyDecide(a), craft_autonomy_consume: (a) => service.autonomyConsume(a),
      craft_contract_observation_record: (a) => service.contractObservationRecord(a), craft_contract_candidate_infer: (a) => service.contractCandidateInfer(a),
      craft_contract_candidate_review: (a) => service.contractCandidateReview(a), craft_contract_candidate_verify: (a) => service.contractCandidateVerify(a),
      craft_contract_diff: (a) => service.contractDiff(a), craft_contract_publish: (a) => service.contractPublish(a),
      craft_contract_publication_rollback: (a) => service.contractPublicationRollback(a),
      craft_capability_canary_start: (a) => service.capabilityCanaryStart(a), craft_capability_canary_route: (a) => service.capabilityCanaryRoute(a),
      craft_capability_canary_observe: (a) => service.capabilityCanaryObserve(a), craft_capability_canary_evaluate: (a) => service.capabilityCanaryEvaluate(a),
      craft_capability_bundle_propose: (a) => service.capabilityBundlePropose(a), craft_capability_bundle_review: (a) => service.capabilityBundleReview(a),
      craft_capability_bundle_publish: (a) => service.capabilityBundlePublish(a), craft_capability_release_subscribe: (a) => service.capabilityReleaseSubscribe(a),
      craft_capability_subscription_resolve: (a) => service.capabilitySubscriptionResolve(a), craft_capability_release_revoke: (a) => service.capabilityReleaseRevoke(a),
      craft_hub_source_register: (a) => service.hubSourceRegister(a), craft_hub_catalog_ingest: (a) => service.hubCatalogIngest(a),
      craft_hub_catalog_search: (a) => service.hubCatalogSearch(a), craft_hub_source_disable: (a) => service.hubSourceDisable(a),
      craft_capability_materialize_stage: (a) => service.capabilityMaterializeStage(a), craft_capability_materialize_review: (a) => service.capabilityMaterializeReview(a),
      craft_capability_materialize_activate: (a) => service.capabilityMaterializeActivate(a),
      craft_capability_certification_assess: (a) => service.capabilityCertificationAssess(a), craft_capability_certification_promote: (a) => service.capabilityCertificationPromote(a),
      craft_supply_chain_advisory_record: (a) => service.supplyChainAdvisoryRecord(a), craft_supply_chain_advisory_resolve: (a) => service.supplyChainAdvisoryResolve(a),
      craft_supply_chain_reconcile: (a) => service.supplyChainReconcile(a),
      craft_supply_chain_publisher_register: (a) => service.supplyChainPublisherRegister(a), craft_supply_chain_attest: (a) => service.supplyChainAttest(a), craft_supply_chain_attestation_assert: (a) => service.supplyChainAttestationAssert(a), craft_supply_chain_attestation_revoke: (a) => service.supplyChainAttestationRevoke(a),
      craft_untrusted_content_register: (a) => service.untrustedContentRegister(a),
      craft_untrusted_extraction_record: (a) => service.untrustedExtractionRecord(a),
      craft_decision_projection_release: (a) => service.decisionProjectionRelease(a),
      craft_decision_projection_explain: (a) => service.decisionProjectionExplain(a),
      craft_untrusted_content_parse: (a) => service.untrustedContentParse(a),
      craft_parser_security_evaluate: (a) => service.parserSecurityEvaluate(a),
      craft_untrusted_content_parse_process: (a) => service.untrustedContentParseProcess(a),
      craft_sandbox_profile_save: (a) => service.sandboxProfileSave(a),
      craft_sandbox_profile_verify: (a) => service.sandboxProfileVerify(a),
      craft_sandbox_plan: (a) => service.sandboxPlan(a),
      craft_sandbox_receipt: (a) => service.sandboxReceipt(a),
      craft_docker_sandbox_request_digest: (a) => service.dockerSandboxRequestDigest(a),
      craft_docker_sandbox_probe: (a) => service.dockerSandboxProbe(a),
      craft_docker_sandbox_conformance: (a) => service.dockerSandboxConformance(a),
      craft_docker_sandbox_execute: (a) => service.dockerSandboxExecute(a),
      craft_trajectory_script_compile: (a) => service.trajectoryScriptCompile(a), craft_trajectory_script_authorize: (a) => service.trajectoryScriptAuthorize(a),
      craft_trajectory_script_get: (a) => service.get("trajectory_script_proposal", "proposal_id", a),
      craft_trajectory_script_list: (a) => service.list("trajectory_script_proposal", "proposals", a),
      craft_verified_script_issue: (a) => service.verifiedScriptIssue(a), craft_verified_script_receipt: (a) => service.verifiedScriptReceipt(a),
      craft_verified_script_run_get: (a) => service.get("verified_script_run", "run_id", a),
      craft_artifact_register: (a) => service.artifactRegister(a),
      craft_artifact_get: (a) => service.get("artifact", "artifact_id", a),
      craft_artifact_list: (a) => service.list("artifact", "artifacts", a),
      craft_evidence_record: (a) => service.evidenceRecord(a),
      craft_evidence_get: (a) => service.get("evidence", "evidence_id", a),
      craft_evidence_list: (a) => service.list("evidence", "evidence", a),
      craft_workflow_save: (a) => service.workflowSave(a),
      craft_workflow_get: (a) => service.get("workflow", "workflow_id", a),
      craft_workflow_search: (a) => service.list("workflow", "workflows", a),
      craft_workflow_plan: (a) => service.workflowPlan(a), craft_workflow_run: (a) => service.workflowRun(a),
      craft_workflow_trial_run: (a) => service.workflowTrialRun(a),
      craft_workflow_run_get: (a) => service.get("workflow_run", "run_id", a),
      craft_workflow_transition: (a) => service.workflowTransition(a),
      craft_workflow_rollback: (a) => service.workflowRollback(a),
      craft_workflow_checkpoint: service.workflowDagCheckpoint.bind(service), craft_workflow_resume: service.workflowDagResume.bind(service), craft_workflow_run_cancel: service.workflowDagCancel.bind(service), craft_workflow_replan: service.workflowDagReplan.bind(service), craft_workflow_export: service.workflowDagExport.bind(service), craft_workflow_import: service.workflowDagImport.bind(service),
      craft_graph_compile: service.graphCompile.bind(service),
      craft_task_state_transition: service.taskStateTransition.bind(service), craft_task_state_get: service.taskStateGet.bind(service), craft_task_state_replay: service.taskStateReplay.bind(service),
      craft_experience_pattern_create: (a) => service.experiencePatternCreate(a),
      craft_experience_pattern_get: (a) => service.get("experience_pattern", "pattern_id", a),
      craft_experience_pattern_list: (a) => service.list("experience_pattern", "patterns", a),
      craft_experience_candidate_list: (a) => service.experienceCandidateList(a),
      craft_experience_mine: (a) => service.experienceMine(a),
      craft_experience_shadow_experiment_create: (a) => service.experienceShadowExperimentCreate(a),
      craft_experience_shadow_experiment_evaluate: (a) => service.experienceShadowExperimentEvaluate(a),
      craft_operational_signal_record: (a) => service.operationalSignalRecord(a),
      craft_operational_drift_evaluate: (a) => service.operationalDriftEvaluate(a),
      craft_skill_proposal_create: (a) => service.skillProposalCreate(a),
      craft_skill_proposal_get: (a) => service.get("skill_proposal", "proposal_id", a),
      craft_skill_proposal_list: (a) => service.list("skill_proposal", "proposals", a),
      craft_skill_proposal_transition: (a) => service.skillProposalTransition(a),
      craft_skill_proposal_rollback: (a) => service.skillProposalRollback(a),
      craft_skill_proposal_publish: (a) => service.skillProposalPublish(a),
      craft_skill_publication_get: (a) => service.get("skill_publication", "publication_id", a),
      craft_skill_publication_list: (a) => service.list("skill_publication", "publications", a),
      craft_skill_publication_rollback: (a) => service.skillPublicationRollback(a),
      craft_eval_suite_save: (a) => service.evaluationSuiteSave(a),
      craft_eval_suite_get: (a) => service.get("evaluation_suite", "suite_id", a),
      craft_eval_suite_list: (a) => service.list("evaluation_suite", "suites", a),
      craft_harness_configuration_save: (a) => service.harnessConfigurationSave(a),
      craft_harness_configuration_get: (a) => service.get("harness_configuration", "configuration_id", a),
      craft_harness_configuration_list: (a) => service.list("harness_configuration", "configurations", a),
      craft_harness_select: (a) => service.harnessSelect(a), craft_agent_ir_compile: (a) => service.agentIrCompile(a),
      craft_agent_ir_lower: (a) => service.agentIrLower(a),
      craft_trial_start: (a) => service.trialStart(a),
      craft_trial_trace_append: (a) => service.trialTraceAppend(a),
      craft_trial_get: (a) => service.trialGet(a),
      craft_trial_list: (a) => service.list("trial", "trials", a),
      craft_trace_start: (a) => service.traceStart(a),
      craft_trace_append: (a) => service.traceAppend(a),
      craft_trace_observe: (a) => service.traceObserve(a),
      craft_trace_feedback: (a) => service.traceFeedback(a),
      craft_trace_finalize: (a) => service.traceFinalize(a),
      craft_trace_get: (a) => service.traceGet(a),
      craft_trace_query: (a) => service.traceQuery(a),
      craft_trace_replay_bundle: (a) => service.traceReplayBundle(a),
      craft_trace_review: (a) => service.traceReview(a),
      craft_trace_review_get: (a) => service.traceReviewGet(a),
      craft_trace_review_list: (a) => service.traceReviewList(a),
      craft_trace_case_compile: (a) => service.traceCaseCompile(a),
      craft_trace_retention_plan: (a) => service.traceRetentionPlan(a),
      craft_trace_retention_sweep: (a) => service.traceRetentionSweep(a),
      craft_trace_archive_storage_register: (a) => service.traceArchiveStorageRegister(a),
      craft_trace_archive_storage_list: (a) => service.traceArchiveStorageList(a),
      craft_trace_archive_storage_activate: (a) => service.traceArchiveStorageActivate(a),
      craft_host_session_open: (a) => service.hostSessionOpen(a), craft_host_session_append: (a) => service.hostSessionAppend(a), craft_host_session_resume: (a) => service.hostSessionResume(a), craft_host_session_get: (a) => service.hostSessionGet(a),
      craft_outcome_observer_observe: (a) => service.outcomeObserverObserve(a), craft_outcome_observer_get: (a) => service.outcomeObserverGet(a),
      craft_outcome_record: (a) => service.outcomeRecord(a),
      craft_evaluation_run_record: (a) => service.evaluationRunRecord(a),
      craft_evaluation_run_get: (a) => service.get("evaluation_run", "run_id", a),
      craft_evaluation_run_list: (a) => service.list("evaluation_run", "runs", a),
      craft_evaluation_run_aggregate: (a) => service.evaluationRunAggregate(a),
      craft_evaluation_compare: (a) => service.evaluationCompare(a),
      craft_evaluation_runner_run: (a) => service.evaluationRunnerRun(a),
      craft_evaluation_program_grade: (a) => service.evaluationProgramGrade(a),
      craft_evaluation_promotion_assess: (a) => service.evaluationPromotionAssess(a),
      craft_evaluation_comparison_get: (a) => service.get("evaluation_comparison", "comparison_id", a),
      craft_evaluation_comparison_list: (a) => service.list("evaluation_comparison", "comparisons", a),
      craft_grader_save: (a) => service.graderSave(a),
      craft_grader_get: (a) => service.get("grader", "grader_id", a),
      craft_grader_list: (a) => service.list("grader", "graders", a),
      craft_grade_record: (a) => service.gradeRecord(a),
      craft_grade_get: (a) => service.get("grade", "grade_id", a),
      craft_grade_list: (a) => service.list("grade", "grades", a),
      craft_signoff_policy_save: (a) => service.signoffPolicySave(a),
      craft_signoff_policy_get: (a) => service.get("signoff_policy", "policy_id", a),
      craft_signoff_policy_list: (a) => service.list("signoff_policy", "policies", a),
      craft_signoff_evaluate: (a) => service.signoffEvaluate(a),
      craft_signoff_get: (a) => service.get("signoff", "signoff_id", a),
      craft_signoff_list: (a) => service.list("signoff", "signoffs", a),
      craft_agent_profile_save: (a) => service.saveVersioned("agent_profile", "profile", a,
        ["name", "role", "host", "model"]),
      craft_agent_profile_get: (a) => service.get("agent_profile", "profile_id", a),
      craft_agent_profile_list: (a) => service.list("agent_profile", "profiles", a),
      craft_orchestration_plan_create: (a) => service.orchestrationCreate(a),
      craft_orchestration_trial_start: (a) => service.orchestrationTrialStart(a),
      craft_orchestration_plan_get: (a) => service.get("orchestration_plan", "plan_id", a),
      craft_orchestration_plan_list: (a) => service.list("orchestration_plan", "plans", a),
      craft_orchestration_dispatch: (a) => service.orchestrationDispatch(a),
      craft_orchestration_renew: (a) => service.orchestrationRenew(a),
      craft_orchestration_submit: (a) => service.orchestrationSubmit(a),
      craft_orchestration_trial_finalize: (a) => service.orchestrationTrialFinalize(a),
      craft_capability_asset_save: service.capabilityAssetSave.bind(service), craft_capability_access_plan: service.capabilityAccessPlan.bind(service),
      craft_capability_call_issue: service.capabilityCallIssue.bind(service), craft_capability_call_consume: service.capabilityCallConsume.bind(service),
      craft_capability_kit_install: service.capabilityKitInstall.bind(service), craft_capability_kit_install_builtins: service.capabilityKitInstallBuiltins.bind(service),
      craft_capability_kit_get: service.capabilityKitGet.bind(service), craft_capability_kit_list: service.capabilityKitList.bind(service),
      craft_capability_kit_activate: service.capabilityKitActivate.bind(service), craft_capability_kit_contribution_record: service.capabilityKitContributionRecord.bind(service),
      craft_capability_kit_set_state: service.capabilityKitSetState.bind(service), craft_capability_kit_conformance: service.capabilityKitConformance.bind(service),
      craft_capability_kit_distribution: service.capabilityKitDistribution.bind(service),
      craft_engineering_quality_profile_install: service.engineeringQualityProfileInstall.bind(service),
      craft_engineering_quality_profile_case_save: service.engineeringQualityProfileCaseSave.bind(service),
      craft_engineering_quality_profile_activate: service.engineeringQualityProfileActivate.bind(service),
      craft_engineering_quality_profile_trial_context: service.engineeringQualityProfileTrialContext.bind(service),
      craft_engineering_quality_profile_contribution: service.engineeringQualityProfileContribution.bind(service),
      craft_engineering_quality_profile_review_aggregate: service.engineeringQualityProfileReviewAggregate.bind(service),
      craft_engineering_quality_profile_evaluation_plan: service.engineeringQualityProfileEvaluationPlan.bind(service),
      craft_engineering_quality_profile_evaluation_record: service.engineeringQualityProfileEvaluationRecord.bind(service),
      craft_engineering_quality_profile_evaluation_evaluate: service.engineeringQualityProfileEvaluationEvaluate.bind(service),
      craft_engineering_quality_profile_evaluation_get: service.engineeringQualityProfileEvaluationGet.bind(service),
      craft_knowledge_memory_install_builtins: service.knowledgeMemoryInstallBuiltins.bind(service),
      craft_knowledge_bootstrap_install: service.knowledgeMemoryInstallBuiltins.bind(service),
      craft_knowledge_source_register: service.knowledgeSourceRegister.bind(service),
      craft_knowledge_source_ingest: service.knowledgeSourceIngest.bind(service),
      craft_knowledge_expiry_sweep: service.knowledgeExpirySweep.bind(service), craft_knowledge_conflict_resolve: service.knowledgeConflictResolve.bind(service),
      craft_knowledge_source_list: service.knowledgeSourceList.bind(service), craft_knowledge_source_transition: service.knowledgeSourceTransition.bind(service),
      craft_memory_ledger_remember: service.memoryLedgerRemember.bind(service), craft_memory_ledger_get: service.memoryLedgerGet.bind(service), craft_memory_ledger_list: service.memoryLedgerList.bind(service), craft_memory_ledger_transition: service.memoryLedgerTransition.bind(service), craft_memory_ledger_compat_bind: service.memoryLedgerCompatBind.bind(service),
      craft_memory_candidate_propose: service.memoryCandidatePropose.bind(service), craft_memory_candidate_review: service.memoryCandidateReview.bind(service), craft_memory_ledger_remember_approved: service.memoryLedgerRememberApproved.bind(service), craft_memory_capture_user_statement: service.memoryCaptureUserStatement.bind(service),
      craft_memory_policy_save: service.memoryPolicySave.bind(service), craft_memory_policy_get: service.memoryPolicyGet.bind(service),
      craft_memory_governance: (a) => {
        if (a.action === "topics") return service.memoryGovernance.topicSuggestions(a);
        if (a.action === "confirm") return service.memoryGovernance.confirm(a);
        if (a.action === "tasks") return service.memoryGovernance.governanceTasks(a);
        throw new Error("Unsupported Memory governance action");
      },
      craft_memory_conflict_list: service.memoryConflictList.bind(service), craft_memory_conflict_resolve: service.memoryConflictResolve.bind(service), craft_memory_expiry_sweep: service.memoryExpirySweep.bind(service), craft_memory_session_finalize: service.memorySessionFinalize.bind(service),
      craft_context_resolution_feedback: (a) => service.contextResolutionFeedback(componentArgs(a)),
      craft_context_resolution_resolve: (a) => service.contextResolutionResolve(componentArgs(a)), craft_context_resolution_get: service.contextResolutionGet.bind(service),
      craft_scope_identity_resolve_project: service.scopeIdentityResolveProject.bind(service), craft_scope_alias_migrate: service.scopeAliasMigrate.bind(service),
      craft_context_working_set_resolve: service.contextWorkingSetResolve.bind(service), craft_context_working_set_get: service.contextWorkingSetGet.bind(service),
      craft_decision_context_gate_open: (a) => service.decisionContextGateOpen(componentArgs(a)), craft_decision_context_gate_get: service.decisionContextGateGet.bind(service),
      craft_retrieval_adapter_configure: service.retrievalAdapterConfigure.bind(service), craft_retrieval_adapter_evaluate: service.retrievalAdapterEvaluate.bind(service),
      craft_memory_maintenance_schedule: service.memoryMaintenanceSchedule.bind(service),
      craft_turn_policy_save: service.turnPolicySave.bind(service), craft_turn_policy_get: service.turnPolicyGet.bind(service),
      craft_turn_proposal_submit: service.turnProposalSubmit.bind(service), craft_turn_host_adapter_save: service.turnHostAdapterSave.bind(service), craft_turn_hook_plan: service.turnHookPlan.bind(service),
      craft_turn_intake_assess: service.turnIntakeAssess.bind(service), craft_turn_receipt_get: service.turnReceiptGet.bind(service),
      craft_turn_memory_candidate_list: service.turnMemoryCandidateList.bind(service), craft_turn_memory_candidate_decide: service.turnMemoryCandidateDecide.bind(service),
      craft_turn_evaluation_case_save: service.turnEvaluationCaseSave.bind(service), craft_turn_evaluation_run: service.turnEvaluationRun.bind(service),
      craft_work_runtime_mode_configure: service.workRuntimeModeConfigure.bind(service), craft_work_runtime_mode_prepare: service.workRuntimeModePrepare.bind(service), craft_work_runtime_mode_get: service.workRuntimeModeGet.bind(service),
      craft_continual_harness_view_create: service.continualHarnessViewCreate.bind(service), craft_continual_harness_refine: service.continualHarnessRefine.bind(service),
      craft_continual_harness_submit: service.continualHarnessSubmit.bind(service), craft_continual_harness_shadow: service.continualHarnessShadow.bind(service),
      craft_continual_harness_authorize_canary: service.continualHarnessAuthorizeCanary.bind(service), craft_continual_harness_observe_canary: service.continualHarnessObserveCanary.bind(service),
      craft_continual_harness_rollback: service.continualHarnessRollback.bind(service), craft_continual_harness_get: service.continualHarnessGet.bind(service),
      craft_continual_harness_signals: service.continualHarnessSignals.bind(service), craft_continual_harness_resolve: service.continualHarnessResolve.bind(service),
      craft_stateful_compute_host_register: service.statefulComputeHostRegister.bind(service), craft_stateful_compute_session_prepare: service.statefulComputeSessionPrepare.bind(service),
      craft_stateful_compute_dispatch: service.statefulComputeDispatch.bind(service), craft_stateful_compute_observe: service.statefulComputeObserve.bind(service),
      craft_stateful_compute_delegate: service.statefulComputeDelegate.bind(service), craft_stateful_compute_report: service.statefulComputeReport.bind(service),
      craft_stateful_compute_cancel: service.statefulComputeCancel.bind(service),
      craft_stateful_compute_session_get: service.statefulComputeSessionGet.bind(service),
      craft_uncertainty_policy_save: service.uncertaintyPolicySave.bind(service), craft_uncertainty_resolve: service.uncertaintyResolve.bind(service), craft_uncertainty_adjudicate: service.uncertaintyAdjudicate.bind(service),
      craft_action_gate_decide: service.actionGateDecide.bind(service), craft_action_gate_record_approval: service.actionGateRecordApproval.bind(service),
      craft_action_gate_accept_proposal: service.actionGateAcceptProposal.bind(service), craft_action_gate_rule_get: service.actionGateRuleGet.bind(service),
      craft_action_gate_rule_list: service.actionGateRuleList.bind(service),
      craft_authorization_acknowledge: service.authorizationAcknowledge.bind(service), craft_authorization_authorize: service.authorizationAuthorize.bind(service),
      craft_authorization_check: service.authorizationCheck.bind(service), craft_authorization_consume: service.authorizationConsume.bind(service),
      craft_authorization_revoke: service.authorizationRevoke.bind(service), craft_authorization_get: service.authorizationGet.bind(service),
      craft_authorization_list: service.authorizationList.bind(service), craft_authorization_trail: service.authorizationTrail.bind(service),
      craft_receipt_issue: service.receiptIssue.bind(service), craft_receipt_get: service.receiptGet.bind(service),
      craft_receipt_list: service.receiptList.bind(service), craft_receipt_assess: service.receiptAssess.bind(service),
      craft_receipt_trend: service.receiptTrend.bind(service), craft_receipt_remediation: service.receiptRemediation.bind(service),
      craft_subscription_drift_register: service.subscriptionDriftRegister.bind(service), craft_subscription_drift_check: service.subscriptionDriftCheck.bind(service),
      craft_subscription_drift_ingest: service.subscriptionDriftIngest.bind(service), craft_subscription_drift_reactivate: service.subscriptionDriftReactivate.bind(service),
      craft_subscription_drift_sweep: service.subscriptionDriftSweep.bind(service), craft_subscription_drift_get: service.subscriptionDriftGet.bind(service),
      craft_subscription_drift_list: service.subscriptionDriftList.bind(service),
      craft_prepared_state_prepare: service.preparedStatePrepare.bind(service), craft_prepared_state_get: service.preparedStateGet.bind(service),
      craft_prepared_state_release: service.preparedStateRelease.bind(service),
      craft_adjudication_enqueue: service.adjudicationEnqueue.bind(service), craft_adjudication_view: service.adjudicationView.bind(service),
      craft_adjudication_resolve: service.adjudicationResolve.bind(service), craft_adjudication_authorizations: service.adjudicationAuthorizations.bind(service),
      craft_hatch_session_open: service.hatchSessionOpen.bind(service), craft_hatch_session_get: service.hatchSessionGet.bind(service),
      craft_hatch_object: service.hatchObject.bind(service), craft_hatch_object_get: service.hatchObjectGet.bind(service),
      craft_hatch_object_list: service.hatchObjectList.bind(service), craft_hatch_fields_request: service.hatchFieldsRequest.bind(service),
      craft_hatch_fields_complete: service.hatchFieldsComplete.bind(service),
      craft_reference_pilot_save: service.referencePilotSave.bind(service), craft_release_qualification_plan: service.releaseQualificationPlan.bind(service), craft_release_qualification_record: service.releaseQualificationRecord.bind(service), craft_release_qualification_evaluate: service.releaseQualificationEvaluate.bind(service), craft_platform_ideal_state_assess: service.platformIdealStateAssess.bind(service),
      craft_verification_plan: service.verificationPlan.bind(service), craft_verification_receipt_record: service.verificationReceiptRecord.bind(service), craft_verification_assess: service.verificationAssess.bind(service), craft_verification_get: service.verificationGet.bind(service),
      craft_capability_connector_register: service.capabilityConnectorRegister.bind(service), craft_capability_connector_discover: service.capabilityConnectorDiscover.bind(service),
      craft_capability_connector_update: service.capabilityConnectorUpdate.bind(service),
      craft_capability_connector_health_record: service.capabilityConnectorHealthRecord.bind(service),
      craft_capability_connector_revoke: service.capabilityConnectorRevoke.bind(service),
      craft_capability_connector_approve: service.capabilityConnectorApprove.bind(service), craft_capability_connector_list: service.capabilityConnectorList.bind(service),
      craft_capability_connector_ticket_issue: service.capabilityConnectorTicketIssue.bind(service), craft_capability_connector_ticket_consume: service.capabilityConnectorTicketConsume.bind(service),
      craft_expert_profile_save: service.expertProfileSave.bind(service), craft_context_capsule_create: service.contextCapsuleCreate.bind(service),
      craft_expert_subagent_create: service.expertSubagentCreate.bind(service), craft_expert_subagent_report: service.expertSubagentReport.bind(service),
      craft_expert_subagent_run: (a) => service.expertSubagentRun(a),
      craft_evaluation_reliability_assess: service.evaluationReliabilityAssess.bind(service), craft_judge_adapter_save: service.judgeAdapterSave.bind(service),
      craft_judge_calibration_record: service.judgeCalibrationRecord.bind(service), craft_judge_promotion_eligible: service.judgePromotionEligible.bind(service), craft_evaluation_judge_gate: service.evaluationJudgeGate.bind(service),
      craft_adaptation_candidate_create: service.adaptationCandidateCreate.bind(service), craft_adaptation_candidate_authorize_canary: service.adaptationCandidateAuthorizeCanary.bind(service), craft_feedback_intake_create: service.feedbackIntakeCreate.bind(service),
      craft_feedback_case_approve: service.feedbackCaseApprove.bind(service), craft_canary_start: service.canaryStart.bind(service), craft_canary_observe: service.canaryObserve.bind(service),
      craft_host_profile_list: () => service.hostProfileList(),
      craft_host_profile_resolve: (a) => service.hostProfileResolve(a),
      craft_workflow_registry_scan: (a) => service.workflowRegistryScan(a),
      craft_workflow_retirement_plan: (a) => service.workflowRetirementPlan(a),
      craft_knowledge_index_sync: (a) => service.knowledgeIndexSync(a),
      craft_knowledge_search: (a) => service.knowledgeSearchScoped(a),
      craft_execution_budget_plan: (a) => service.executionBudgetPlan(a),
      craft_hook_catalog: (a) => service.hookCatalog(a),
      craft_hook_run: (a) => service.hookRun(a),
      craft_evaluation_contract_define: (a) => service.evaluationContractDefine(a),
      craft_evaluation_contract_record: (a) => service.evaluationContractRecord(a),
      craft_evaluation_contract_get: (a) => service.evaluationContractGet(a),
      craft_model_provider_list: () => service.modelProviderList(),
      craft_metrics_report: (a) => service.metricsReport(a),
      craft_usage_report: (a) => service.usageReport(a),
      craft_settings_get: async () => service.settingsGet(),
      craft_settings_update: async (a) => service.settingsUpdate(a),
      craft_settings_reset: async () => service.settingsReset(),
      craft_launch_gate: (a) => service.launchGate(a),
      craft_knowledge_scope_set: (a) => service.knowledgeScopeSet(a),
      craft_knowledge_scope_list: (a) => service.knowledgeScopeList(a),
      craft_knowledge_scope_forget: () => service.knowledgeScopeForget(),
      craft_model_provider_get: (a) => service.modelProviderGet(a),
      craft_agent_loop_plan: (a) => service.agentLoopPlan(a),
      craft_asset_route: (a) => service.assetRoute(a),
      craft_model_independence_compare: (a) => service.modelIndependenceCompare(a),
      craft_autonomous_runtime_prepare: (a) => service.autonomousRuntimePrepare(a),
      craft_autonomous_runtime_run: (a) => service.autonomousRuntimeRun(a),
      craft_autonomous_runtime_checkpoint: (a) => service.autonomousRuntimeCheckpoint(a),
      craft_autonomous_runtime_resume: (a) => service.autonomousRuntimeResume(a),
      craft_autonomous_runtime_cancel: (a) => service.autonomousRuntimeCancel(a),
      craft_autonomous_runtime_get: (a) => service.autonomousRuntimeGet(a),
      craft_capability_lifecycle_register: (a) => service.capabilityLifecycleRegister(a),
      craft_capability_lifecycle_install: (a) => service.capabilityLifecycleInstall(a),
      craft_capability_lifecycle_activate: (a) => service.capabilityLifecycleActivate(a),
      craft_capability_lifecycle_disable: (a) => service.capabilityLifecycleDisable(a),
      craft_capability_lifecycle_upgrade: (a) => service.capabilityLifecycleUpgrade(a),
      craft_capability_lifecycle_retire: (a) => service.capabilityLifecycleRetire(a),
      craft_capability_lifecycle_resolve: (a) => service.capabilityLifecycleResolve(a),
      craft_capability_lifecycle_list: () => service.capabilityLifecycleList(),
      craft_capability_intake_discover: service.capabilityIntakeDiscover.bind(service), craft_capability_intake_scan: service.capabilityIntakeScan.bind(service),
      craft_capability_intake_conformance: service.capabilityIntakeConformance.bind(service), craft_capability_intake_approve: service.capabilityIntakeApprove.bind(service),
      craft_capability_intake_activate: service.capabilityIntakeActivate.bind(service), craft_capability_intake_revoke: service.capabilityIntakeRevoke.bind(service),
      craft_capability_intake_upgrade_plan: service.capabilityIntakeUpgradePlan.bind(service), craft_capability_intake_get: service.capabilityIntakeGet.bind(service), craft_capability_intake_list: service.capabilityIntakeList.bind(service),
      craft_memory_remember_episode: (a) => service.memoryConsolidationRemember(a),
      craft_memory_consolidate: service.memoryConsolidateGoverned.bind(service),
      craft_memory_resolve: (a) => service.memoryConsolidationResolve(a),
      craft_memory_search: (a) => service.memoryConsolidationSearch(a),
      craft_memory_maintenance_signal: (a) => service.memoryMaintenanceSignal(a),
      craft_memory_maintenance_run: (a) => mountedComponent && (!a.scope_kind || !a.scope_id) ? { skipped: true, reason: "scope_unavailable" } : service.memoryMaintenanceRun(a),
      craft_memory_maintenance_cycle: (a) => service.memoryMaintenanceCycle(a),
      craft_memory_maintenance_get: (a) => service.memoryMaintenanceGet(a),
      craft_remote_interop_prepare: (a) => service.remoteInteropPrepare(a),
      craft_remote_interop_dispatch: (a) => service.remoteInteropDispatch(a),
      craft_remote_interop_report: (a) => service.remoteInteropReport(a),
      craft_remote_interop_get: (a) => service.remoteInteropGet(a),
      craft_platform_member_save: (a) => service.platformMemberSave(a),
      craft_platform_authorize: (a) => service.platformAuthorize(a),
      craft_platform_observe: (a) => service.platformObserve(a),
      craft_platform_observability_export: (a) => service.platformObservabilityExport(a),
      craft_runtime_truth_standardize: (a) => service.runtimeTruthStandardize(a),
      craft_runtime_truth_otlp: (a) => service.runtimeTruthOtlp(a),
      craft_runtime_truth_export: (a) => service.runtimeTruthExport(a),
      craft_runtime_truth_compact: (a) => service.runtimeTruthCompact(a),
      craft_runtime_truth_compaction_get: (a) => service.runtimeTruthCompactionGet(a),
      craft_runtime_truth_compaction_list: (a) => service.runtimeTruthCompactionList(a),
      craft_runtime_truth_work_note: (a) => service.runtimeTruthWorkNote(a),
      craft_runtime_truth_work_note_get: (a) => service.runtimeTruthWorkNoteGet(a),
      craft_runtime_attempt_prepare: service.runtimeAttemptPrepare.bind(service), craft_runtime_attempt_dispatch: service.runtimeAttemptDispatch.bind(service),
      craft_runtime_attempt_receipt_pending: service.runtimeAttemptReceiptPending.bind(service), craft_runtime_attempt_record_receipt: service.runtimeAttemptRecordReceipt.bind(service),
      craft_runtime_attempt_observe: service.runtimeAttemptObserve.bind(service), craft_runtime_attempt_resolve_effect: service.runtimeAttemptResolveEffect.bind(service),
      craft_runtime_attempt_recover: service.runtimeAttemptRecover.bind(service), craft_runtime_attempt_cancel: service.runtimeAttemptCancel.bind(service), craft_runtime_attempt_get: service.runtimeAttemptGet.bind(service),
      craft_os_security_plan: (a) => service.osSecurityPlan(a),
      craft_os_security_verify: (a) => service.osSecurityVerify(a),
      craft_mcp_registry_source_register: (a) => service.mcpRegistrySourceRegister(a),
      craft_mcp_registry_server_ingest: (a) => service.mcpRegistryServerIngest(a),
      craft_mcp_registry_health_record: (a) => service.mcpRegistryHealthRecord(a), craft_mcp_registry_sync: (a) => service.mcpRegistrySync(a),
      craft_mcp_registry_revoke: (a) => service.mcpRegistryRevoke(a),
      craft_a2a_transport_dispatch: (a) => service.a2aTransportDispatch(a), craft_a2a_transport_task_get: (a) => service.a2aTransportTaskGet(a), craft_a2a_transport_task_cancel: (a) => service.a2aTransportTaskCancel(a),
      craft_a2a_v1_discover: (a) => service.a2aV1Discover(a), craft_a2a_v1_submit: (a) => service.a2aV1Submit(a), craft_a2a_v1_task_get: (a) => service.a2aV1TaskGet(a), craft_a2a_v1_cancel: (a) => service.a2aV1Cancel(a),
      craft_remote_tenant_register: (a) => service.remoteTenantRegister(a), craft_remote_task_bind: (a) => service.remoteTaskBind(a), craft_remote_task_authorize: (a) => service.remoteTaskAuthorize(a), craft_remote_task_revoke: (a) => service.remoteTaskRevoke(a), craft_remote_task_get: (a) => service.remoteTaskGet(a),
      craft_org_sync_prepare: (a) => service.orgSyncPrepare(a),
      craft_org_sync_apply: (a) => service.orgSyncApply(a),
      craft_project_brain_open: (a) => service.projectBrainOpen(a),
      craft_project_brain_get: (a) => service.projectBrainGet(a),
      craft_project_brain_refresh: (a) => service.projectBrainRefresh(a),
      craft_project_goal_save: (a) => service.projectBrainGoalSave(a),
      craft_project_decision_save: (a) => service.projectBrainDecisionSave(a),
      craft_project_material_bind: (a) => service.projectBrainMaterialBind(a),
      craft_project_outcome_record: (a) => service.projectBrainOutcomeRecord(a),
      craft_project_experience_record: (a) => service.projectBrainExperienceRecord(a),
      craft_work_session_prepare: (a) => service.workSessionPrepare(a),
      craft_work_session_get: (a) => service.workSessionGet(a),
      craft_work_session_refresh: (a) => service.workSessionRefresh(a),
      craft_work_session_bind_launch: (a) => service.workSessionBindLaunch(a),
      craft_work_session_bind_dispatch: (a) => service.workSessionBindDispatch(a),
      craft_work_session_complete: (a) => service.workSessionComplete(a),
      craft_workbench_experience_query: (a) => service.workbenchExperienceQuery(a),
      craft_workbench_experience_get: (a) => service.workbenchExperienceGet(a),
      craft_workbench_experience_review: (a) => service.workbenchExperienceReview(a),
      craft_workbench_trace_replay_plan: (a) => service.workbenchTraceReplayPlan(a),
      craft_workbench_command_execute: service.workbenchCommandExecute.bind(service), craft_workbench_command_get: service.workbenchCommandGet.bind(service), craft_workbench_command_list: service.workbenchCommandList.bind(service),
      craft_long_task_suspend: (a) => service.longTaskSuspend(a),
      craft_long_task_wake: (a) => service.longTaskWake(a),
      craft_long_task_resume: (a) => service.longTaskResume(a),
      craft_long_task_get: (a) => service.longTaskGet(a),
      craft_long_task_list: (a) => service.longTaskList(a),
      craft_long_task_tick: (a) => service.longTaskTick(a),
      craft_context_manifest_save: (a) => service.contextManifestSave(a),
      craft_context_manifest_get: (a) => service.contextManifestGet(a),
      craft_context_manifest_audit: (a) => service.contextManifestAudit(a),
      craft_replay_runner_prepare: (a) => service.replayRunnerPrepare(a),
      craft_replay_runner_execute: (a) => service.replayRunnerExecute(a),
      craft_replay_runner_get: (a) => service.replayRunnerGet(a),
      craft_local_service_configure: (a) => service.localRuntimeServiceConfigure(a),
      craft_local_service_start: (a) => service.localRuntimeServiceStart(a),
      craft_local_service_stop: (a) => service.localRuntimeServiceStop(a),
      craft_local_service_tick: (a) => service.localRuntimeServiceTick(a),
      craft_local_service_get: (a) => service.localRuntimeServiceGet(a),
      craft_automation_job_save: (a) => service.procedureAutomationSave(a),
      craft_automation_job_pause: (a) => service.procedureAutomationPause(a),
      craft_automation_job_run: (a) => service.procedureAutomationRun(a),
      craft_automation_job_receipt_record: (a) => service.procedureAutomationReceiptRecord(a),
      craft_automation_job_tick: (a) => service.procedureAutomationTick(a),
      craft_automation_job_get: (a) => service.procedureAutomationGet(a),
      craft_automation_job_eligibility: (a) => service.procedureAutomationEligibility(a),
      craft_ticket_dispatch_scan: (a) => service.ticketDispatchScan(a),
      craft_ticket_dispatch_evaluate: (a) => service.ticketDispatchEvaluate(a),
      craft_forge_policy_save: (a) => service.forgePolicySave(a),
      craft_forge_action_prepare: (a) => service.forgeActionPrepare(a),
      craft_forge_action_get: (a) => service.forgeActionGet(a),
      craft_project_bundle_export: (a) => service.projectBundleExport(a),
      craft_project_bundle_verify: (a) => service.projectBundleVerify(a),
      craft_knowledge_memory_bundle: (a) => service.knowledgeMemoryBundleManage(a),
      craft_feedback_learning_record: (a) => service.feedbackLearningRecord(a),
      craft_feedback_learning_resolve: (a) => service.feedbackLearningResolve(a),
      craft_domain_evaluator_save: (a) => service.domainEvaluatorSave(a),
      craft_domain_evaluator_evaluate: (a) => service.domainEvaluatorEvaluate(a),
      craft_handoff_manifest_create: (a) => service.handoffManifestCreate(a),
      craft_handoff_manifest_get: (a) => service.handoffManifestGet(a),
      craft_cost_price_save: (a) => service.costPriceSave(a),
      craft_cost_usage_record: (a) => service.costUsageRecord(a),
      craft_cost_ledger_report: (a) => service.costLedgerReport(a),
      craft_verified_work_prepare: (a) => service.verifiedWorkPrepare(a),
      craft_verified_work_authorize: (a) => service.verifiedWorkAuthorize(a),
      craft_verified_work_action: (a) => service.verifiedWorkAction(a),
      craft_verified_work_reobserve: (a) => service.verifiedWorkReobserve(a),
      craft_verified_work_deliver: (a) => service.verifiedWorkDeliver(a),
      craft_verified_work_resume: (a) => service.verifiedWorkResume(a),
      craft_verified_work_handoff: (a) => service.verifiedWorkHandoff(a),
      craft_verified_work_get: (a) => service.verifiedWorkGet(a),
      craft_sandbox_conformance_save: (a) => service.sandboxConformanceSave(a),
      craft_sandbox_conformance_admit: (a) => service.sandboxConformanceAdmit(a),
      craft_sandbox_conformance_get: (a) => service.sandboxConformanceGet(a),
      craft_trace_explorer_query: (a) => service.traceExplorerQuery(a),
      craft_action_gateway_prepare: (a) => service.actionGatewayPrepare(a),
      craft_action_gateway_execute: (a) => service.actionGatewayExecute(a),
      craft_action_gateway_get: (a) => service.actionGatewayGet(a),
      craft_acceptance_gate_prepare: (a) => service.acceptanceGatePrepare(a),
      craft_acceptance_gate_assess: (a) => service.acceptanceGateAssess(a),
      craft_acceptance_gate_outcome: (a) => service.acceptanceGateOutcome(a),
      craft_acceptance_gate_get: (a) => service.acceptanceGateGet(a),
      craft_durable_worker_configure: (a) => service.durableWorkerConfigure(a),
      craft_durable_worker_start: (a) => service.durableWorkerStart(a),
      craft_durable_worker_stop: (a) => service.durableWorkerStop(a),
      craft_durable_worker_enqueue: (a) => service.durableWorkerEnqueue(a),
      craft_durable_worker_tick: (a) => service.durableWorkerTick(a),
      craft_durable_worker_recover: (a) => service.durableWorkerRecover(a),
      craft_durable_worker_get: (a) => service.durableWorkerGet(a),
      craft_provider_route_plan: (a) => service.providerRoutePlan(a),
      craft_provider_route_record: (a) => service.providerRouteRecord(a),
      craft_provider_route_get: (a) => service.providerRouteGet(a),
      craft_a2a_message_send: (a) => service.a2aMessageSend(a),
      craft_a2a_message_stream: (a) => service.a2aMessageStream(a),
      craft_a2a_task_list: (a) => service.a2aTaskList(a),
    };
}
